<?php namespace ProcessWire;

use Purl\Url;

include_once(__DIR__.'/CodeTablesResponse.php');

class CodeTables extends WireData implements Module {

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Codes Tables Management',
			'version' => 101,
			'summary' => 'Module for Codes Tables Management',
			'singular' => true,
			'autoload' => true,
			'installs' => array(
				'CodeTablesAr',
				'CodeTablesIn',
				'CodeTablesSo',
			)
		);
	}

	/**
	 * ProcessWire Installer Function
	 * NOTE: Runs when installed through ProcessWire
	 * @return void
	 */
	public function ___install() {

	}

	/**
	 * ProcessWire removal Function
	 * NOTE: Runs when removed through ProcessWire
	 * @return void
	 */
	public function ___uninstall() {

	}

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');

		foreach ($info['installs'] as $module_name) {
			$modules->install($module_name);
		}
	}

	/**
	 * Sends Dplus Cobol that Code Table has been Update
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return void
	 */
	public function update_dplus_cobol($table, $code) {
		$config = $this->wire('config');
		$dplusdb = $this->wire('modules')->get('DplusConnectDatabase')->db_name;
		$table = strtoupper($table);
		$data = array("DBNAME=$dplusdb", 'UPDATECODETABLE', "TABLE=$table", "CODE=$code");
		$requestor = $this->wire('modules')->get('DplusRequest');
		$requestor->write_dplusfile($data, session_id());
		$requestor->cgi_request($this->wire('config')->cgis['database'], session_id());
	}
}
