<?php namespace ProcessWire;

include_once(__DIR__.'/vendor/autoload.php');

class CodeTables extends WireData implements Module {

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Codes Tables Management',
			'version' => 101,
			'summary' => 'Module for Codes Tables Management',
			'singular' => true,
			'autoload' => true,
		);
	}

	public function getCodeTable($menu, $table) {
		$ns = "\\Dplus\\Codes\\" . ucfirst($menu);
		$class = $ns . "\\" . ucfirst($table);

		if (class_exists($class) === false) {
			return false;
		}
		return $class::instance();
	}
}
