<?php namespace ProcessWire;

/**
 * Mci
 *
 * Parent Module to Install Sub Mcn Modules
 */
class Mci extends WireData implements Module {

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');
		$modules->refresh();

		foreach ($info['installs'] as $module_name) {
			if (!$modules->isInstalled($module_name)) {
				$result = $modules->install($module_name);
			}
		}
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Mci',
			'version' => 101,
			'summary' => 'Handles Mci Modules Installation & Updates',
			'singular' => true,
			'autoload' => true,
			'installs' => array(
				'Cio'
			)
		);
	}
}
