<?php namespace ProcessWire;

use ItemXrefCustomerNoteQuery, ItemXrefCustomerNote;
use ConfigArQuery, ConfigAr;

include_once(__DIR__.'/../QnotesResponse.php');

/**
 * QnotesItemXrefCustomer
 *
 * Class for Writing and Reading Qnotes for CXM Items
 */
class QnotesItemCxm extends WireData implements Module {
	const MODEL                = 'ItemXrefCustomerNote';
	const MODEL_KEY            = 'key2, sequence, form';
	const DESCRIPTION          = 'CXM Item Notes';
	const DESCRIPTION_RECORD   = 'CXM Item Notes';
	const DESCRIPTION_RESPONSE = 'Item {itemID} Customer {custID} Order Notes';

/* =============================================================
	CRUD Read / Validation Functions
============================================================= */
	/**
	 * Returns Quote Notes Query
	 * @return ItemXrefCustomerNoteQuery
	 */
	public function get_query() {
		return ItemXrefCustomerNoteQuery::create();
	}

	/**
	 * Returns if Notes Exist
	 * @param  string $itemID  Item ID (Internal Item ID)
	 * @param  string $custID  Cust ID
	 * @param  string $form    Forms Code
	 * @return bool
	 */
	public function notes_exist($itemID, $custID, $form) {
		$q = $this->get_query();
		$q->filterByItemid($itemID);
		$q->filterByCustid($custID);
		$q->filterByForm($form);
		return boolval($q->count());
	}

	/**
	 * Returns if Notes Exist
	 * @param  string $itemID  Item ID (Internal Item ID)
	 * @param  string $custID  Cust ID
	 * @return bool
	 */
	public function notes_exist_item($itemID, $custID) {
		$q = $this->get_query();
		$q->filterByItemid($itemID);
		$q->filterByCustid($custID);
		return boolval($q->count());
	}

	/**
	 * Returns Line 1 of Every Note
	 * @param  string $itemID  Item ID (Internal Item ID)
	 * @param  string $custID  Cust ID
	 * @return ItemXrefCustomerNote[]|ObjectCollection
	 */
	public function get_notes_summarized($itemID, $custID) {
		$q = $this->get_query();
		$q->filterByItemid($itemID);
		$q->filterByCustid($custID);
		$q->filterBySequence(1);
		return $q->find();
	}

	/**
	 * Return Notes for Form
	 * @param  string $itemID  Item ID (Internal Item ID)
	 * @param  string $custID  Cust ID
	 * @param  string $form    Forms Code
	 * @return array
	 */
	public function get_notes_form_array($itemID, $custID, $form) {
		$q = $this->get_query();
		$q->select(ItemXrefCustomerNote::get_aliasproperty('note'));
		$q->filterByItemid($itemID);
		$q->filterByCustid($custID);
		$q->filterByForm($form);
		return $q->find()->toArray();
	}

/* =============================================================
	CRUD Functions
============================================================= */
	/**
	 * Takes Input, Processes it, updates Quote Notes in the Database
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function process_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());

		switch ($input->$rm->text('action')) {
			case 'update-notes':
				$this->update_notes_input($input);
				break;
			case 'delete-notes':
				$this->delete_notes_input($input);
				break;
		}
	}

	/**
	 * Takes Input, Processes it, deletes Quote Notes
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function delete_notes_input($input) {
		$rm = strtolower($input->requestMethod());
		$itemID  = $input->$rm->text('itemID');
		$custID  = $input->$rm->text('custID');
		$form    = $input->$rm->text('form');

		$q = $this->get_query();
		$q->filterByItemid($itemID);
		$q->filterByCustid($custID);
		$q->filterByForm($form);

		if ($q->count()) {
			$note = $q->findOne();
		} else {
			$note = ItemXrefCustomerNote::new();
			$note->setItemid($itemID);
			$note->setCustid($custID);
			$note->setForm($form);
			$note->generateKey2();
		}
		$success = $this->delete_notes($itemID, $custID, $form);

		$this->wire('session')->response_qnote = $this->process_response_delete($note, $itemID, $custID, $success);
	}

	/**
	 * Takes Input, Processes it, updates Quote Notes
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function update_notes_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$itemID  = $values->text('itemID');
		$custID  = $input->$rm->text('custID');
		$form = $this->get_form_input($input);
		$note_lines = explode(PHP_EOL, $input->$rm->textarea('note'));
		$lines_saved = array();
		$this->delete_notes($itemID, $custID, $form);

		foreach ($note_lines as $key => $line) {
			$sequence = $key + 1;
			$record = ItemXrefCustomerNote::new();
			$record->setItemid($itemID);
			$record->setCustid($custID);
			$record->generateKey2(); // PK
			foreach (array_keys(ItemXrefCustomerNote::FORMS_LABELS) as $formfield) {
				$func = 'set'.ucfirst($formfield);
				$record->$func($values->yn($formfield));
			}
			$record->generateForm();
			$record->setSequence($sequence); // PK
			$record->setNote($line);
			$record->setDate(date('Ymd'));
			$record->setTime(date('His'));
			$record->setDummy('P');
			$lines_saved[$sequence] = $record->save();
		}
		$this->wire('session')->response_qnote = $this->process_responses($record, $itemID, $custID, $lines_saved);
	}

	/**
	 * Return Form Code based on Input
	 * @param  WireInput $input Input Data
	 * @return string
	 */
	public function get_form_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$note = ItemXrefCustomerNote::new();
		$note->setItemid($values->text('itemID'));
		$note->setCustid($values->text('custID'));

		foreach (array_keys(ItemXrefCustomerNote::FORMS_LABELS) as $formfield) {
			$func = 'set'.ucfirst($formfield);
			$note->$func($values->yn($formfield));
		}
		$note->generateForm();
		return $note->form;
	}

	/**
	 * Delete Notes for Item
	 * @param  string $itemID  Item ID (Internal Item ID)
	 * @param  string $custID  Cust ID
	 * @param  string $form    Forms Code
	 * @return array
	 */
	public function delete_notes($itemID, $custID, $form) {
		$q = $this->get_query();
		$q->filterByItemid($itemID);
		$q->filterByCustid($custID);
		$q->filterByForm($form);

		if ($q->count()) {
			return $q->delete();
		}
		return true;
	}

	/**
	 * Return Code Table Response based on the number of lines that were written to the database
	 * @param  string $itemID       Item ID (Internal Item ID)
	 * @param  string $custID       Cust ID
	 * @param  array  $lines_saved  array of line numbers and if they got saved e.g. (1 => true, 2 => false)
	 * @return CodeTableResponse
	 */
	protected function process_responses(ItemXrefCustomerNote $note, $itemID, $custID, array $lines_saved) {
		$message = $this->get_response_message_base($itemID, $custID);

		$response = new QnotesResponse();
		$response->set_key("$itemID-$custID-{$note->key2}");

		if (in_array(false, $lines_saved)) {
			$lines_error =
			array_filter($lines_saved, function($value, $key) {
				return  $value == false;
			}, ARRAY_FILTER_USE_BOTH);
			$message .= implode(", ", array_keys($lines_error));
			$message .= " were not able to be saved";

			if (sizeof($lines_error)) {
				$response->set_error(true);
			}
		} else {
			$response->set_success(true);
			$message .= " were able to be saved";
		}

		$response->set_action(QnotesResponse::CRUD_UPDATE);
		$response->set_message($message);

		// IF there are lines saved
		if (sizeof($lines_saved)) {
			$this->wire('modules')->get('Qnotes')->update_dplus_cobol($note->type, $note->key2, $note->form);
		}
		return $response;
	}

	/**
	 * Return QnoteResponse based if Notes were able to be Deleted
	 * @param  ItemXrefCustomerNote  $note         Attributes are needed to generate key
	 * @param  string             $itemID       Item ID (Internal Item ID)
	 * @param  string             $custID       Whse ID
	 * @param  array              $success      Were Notes able to be deleted?
	 * @return QnoteResponse
	 */
	public function process_response_delete(ItemXrefCustomerNote $note, $itemID, $custID, bool $success) {
		$message = $this->get_response_message_base($itemID, $custID);

		$response = new QnotesResponse();
		$response->set_key("$itemID-$custID-{$note->key2}");

		if ($success) {
			$response->set_success(true);
			$message .= " were able to be deleted";
		} else {
			$response->set_success(true);
			$message .= " were not able to be deleted";
		}

		$response->set_action(QnotesResponse::CRUD_DELETE);
		$response->set_message($message);

		// IF there are lines saved
		if ($success) {
			$this->wire('modules')->get('Qnotes')->update_dplus_cobol($note->type, $note->key2, $note->form);
		}
		return $response;
	}

/* =============================================================
	Supplemental Functions
============================================================= */
	/**
	 * Return Message with provided Item ID and Cust ID
	 * @param  string $itemID Item ID (Internal Item ID)
	 * @param  string $custID Cust ID
	 * @return string
	 */
	public function get_response_message_base($itemID, $custID) {
		$message = self::DESCRIPTION_RESPONSE;
		$replace = array('{itemID}', '{custID}');
		$values  = array($itemID, $custID);
		return str_replace($replace, $values, $message);
	}

	/**
	 * Return Key Value array for forms
	 * @return array
	 */
	public function get_forms() {
		return ItemXrefCustomerNote::FORMS_LABELS;
	}

	/**
	 * Return Key Value array for forms, with shortened labels
	 * @return array
	 */
	public function get_forms_shortlabels() {
		return ItemXrefCustomerNote::FORMS_LABELS_SHORT;
	}

	/**
	 * Return the Max Number of columns for Note Type
	 * @return int
	 */
	public function get_column_count() {
		$config_ar = ConfigArQuery::create()->findOne();
		return $config_ar->columns_notes_invoice;
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Qnotes CXM',
			'version' => 101,
			'summary' => 'Dplus Qnotes CXM',
			'singular' => true,
			'autoload' => true,
			'requires' => array('Qnotes')
		);
	}
}
