<?php namespace ProcessWire;

/**
 * Module for configuring the BINR process
 */
class ConfigsBinr extends Process implements ConfigurableModule {
	const CONFIG_FIELDS = array(
		'default_qtyonhand' => array(
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Use Qty on hand as default qty?',
			'description' => 'Defaults Qty to the Qty On Hand',
			'notes'       => "Defaults Qty to the Qty On Hand"
		),
		'use_qtyonly' => array(
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Force Qty to be Qty?',
			'description' => 'Forces Qty to be Qty, makes input readonly',
			'notes'       => "Forces Qty to be Qty, makes input readonly"
		),
	);

	const DEFAULT_CONFIG = array(
		'default_qtyonhand' => false,
		'use_qtyonly' => false,
	);

	/* =============================================================
			ProcessWire Module Functions
	=============================================================== */
	public function init() {
		parent::init();

		foreach(self::DEFAULT_CONFIG as $key => $value) {
			if (isset($this->data[$key])) {
				$this->data[$key] = $this->data[$key];
			} else {
				$this->data[$key] = $value;
			}
		}
	}

	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso Binr Config Module',
			'version' => 101,
			'summary' => 'Handles Dplus Warehouse Binr Configurations',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages')
		);
	}

	static public function getModuleConfigInputfields(array $data) {
		$modules = wire('modules');
		$fields = new InputfieldWrapper();
		$data = array_merge(self::DEFAULT_CONFIG, $data);

		$traits = self::CONFIG_FIELDS['default_qtyonhand'];
		$f = $modules->get('InputfieldCheckbox');
		$f->attr('name', 'default_qtyonhand');
		$f->attr('checked', $data['default_qtyonhand'] ? 'checked' : '' );
		$f->label = __($traits['label']);
		$f->description = __($traits['description']);
		$f->notes = _($traits['notes']);
		$fields->add($f);

		$traits = self::CONFIG_FIELDS['use_qtyonly'];
		$f = $modules->get('InputfieldCheckbox');
		$f->attr('name', 'use_qtyonly');
		$f->attr('checked', $data['use_qtyonly'] ? 'checked' : '' );
		$f->label = __($traits['label']);
		$f->description = __($traits['description']);
		$f->notes = _($traits['notes']);
		$fields->add($f);
		return $fields;
	}
}
