<?php namespace ProcessWire;

/**
 * Module for Warehouse Inventory configurations
 */
class ConfigsWarehouseInventory extends Process implements ConfigurableModule {
/* =============================================================
		ProcessWire Module Functions
=============================================================== */

	const CONFIG_FIELDS = array(
		'allow_negativeinventory' => array(
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Allow Negative Inventory?',
			'description' => 'Allow Negative Inventory',
			'notes'       => "Negative Inventory will be allowed on Serialized and Normal Items"
		),
		'show_inventoryresults' => array(
			'type'        => 'select',
			'label'       => 'Inventory Results Format',
			'description' => 'Format to show Inventory Results',
			'notes'       => "Format to show Inventory Results",
			'options' => array(
				'lotserial' => 'Lot / Serial Breakdown',
				'bin'       => 'Bin Breakdown'
			)
		)
	);

	const DEFAULT_CONFIG = array(
		'allow_negativeinventory' => false,
		'show_inventoryresults'   => 'lotserial'
	);


	public function init() {
		parent::init();

		foreach(self::DEFAULT_CONFIG as $key => $value) {
			if (isset($this->data[$key])) {
				$this->data[$key] = $this->data[$key];
			} else {
				$this->data[$key] = $value;
			}
		}
	}

	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso Warehouse Inventory Config Module',
			'version' => 101,
			'summary' => 'Handles Dplus Warehouse Inventory Configurations',
			'singular' => true,
			'autoload' => true
		);
	}

	static public function getModuleConfigInputfields(array $data) {
		$modules = wire('modules');
		$fields = new InputfieldWrapper();
		$data = array_merge(self::DEFAULT_CONFIG, $data);

		$traits = self::CONFIG_FIELDS['allow_negativeinventory'];
		$f = $modules->get('InputfieldCheckbox');
		$f->attr('name', 'allow_negativeinventory');
		$f->attr('checked', $data['allow_negativeinventory'] ? 'checked' : '' );
		$f->label = __($traits['label']);
		$f->description = __($traits['description']);
		$f->notes = _($traits['notes']);
		$fields->add($f);

		return $fields;
	}
}
