<?php namespace ProcessWire;

/**
 * Module for Warehouse Picking configurations
 */
class ConfigsWarehousePicking extends Process implements ConfigurableModule {
/* =============================================================
		ProcessWire Module Functions
=============================================================== */

	const CONFIG_FIELDS = array(
		'picking_method' => array(
			'type'        => 'select',
			'label'       => 'Customer Picking Method',
			'description' => 'Picking Method',
			'notes'       => "Unguided: User will not be guided through the order
			Guided: User will be guided through the order",
			'options' => array('guided' => 'Guided', 'unguided' => 'Unguided')
		),
		'use_singleunitqty' => array(
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Use Qty unit of 1',
			'description' => 'Use Qty unit of 1',
			'notes'       => 'Disables use of scanning barcodes with different unit quantities'
		),
		'verify_whseitempicks' => array(
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Verify Picked Items?',
			'description' => 'Verify Picked Items',
			'notes'       => 'Enables Lot Reference / Expire / Production date changes'
		),
	);

	const DEFAULT_CONFIG = array(
		'picking_method'    => 'unguided',
		'use_singleunitqty' => true,
		'verify_whseitempicks' => false,
	);

	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso Warehouse Picking Config Module',
			'version' => 101,
			'summary' => 'Handles Dplus Warehouse Picking Configurations',
			'singular' => true,
			'autoload' => true
		);
	}

	static public function getModuleConfigInputfields(array $data) {
		$modules = wire('modules');
		$fields = new InputfieldWrapper();
		$data = array_merge(self::DEFAULT_CONFIG, $data);

		$traits = self::CONFIG_FIELDS['picking_method'];
		$f = $modules->get("InputfieldSelect");
		$f->attr('name', 'picking_method');
		$f->label = __($traits['label']);
		$f->description = __($traits['description']);
		$f->notes = _($traits['notes']);
		$f->addOptions($traits['options']);
		$f->value = $data['picking_method'];
		$fields->add($f);

		$traits = self::CONFIG_FIELDS['use_singleunitqty'];
		$f = $modules->get('InputfieldCheckbox');
		$f->attr('name', 'use_singleunitqty');
		$f->attr('checked', $data['use_singleunitqty'] ? 'checked' : '' );
		$f->label = __($traits['label']);
		$f->description = __($traits['description']);
		$f->notes = _($traits['notes']);
		$fields->add($f);

		$traits = self::CONFIG_FIELDS['verify_whseitempicks'];
		$f = $modules->get('InputfieldCheckbox');
		$f->attr('name', 'verify_whseitempicks');
		$f->attr('checked', $data['verify_whseitempicks'] ? 'checked' : '' );
		$f->label = __($traits['label']);
		$f->description = __($traits['description']);
		$f->notes = _($traits['notes']);
		$fields->add($f);

		return $fields;
	}
}
