<?php namespace ProcessWire;

use ConfigSalesOrderQuery, ConfigSalesOrder;

/**
 * Module for Warehouse Inventory configurations
 */
class ConfigsWarehouseInventory extends Process implements ConfigurableModule {

/* =============================================================
		ProcessWire Module Functions
=============================================================== */

	const CONFIG_FIELDS = array(
		'allow_negativeinventory' => array(
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Allow Negative Inventory?',
			'description' => 'Allow Negative Inventory',
			'notes'       => "Negative Inventory will be allowed on Serialized and Normal Items"
		),
		'show_inventoryresults' => array(
			'type'        => 'select',
			'label'       => 'Inventory Results Format',
			'description' => 'Format to show Inventory Results',
			'notes'       => "Format to show Inventory Results",
			'options' => array(
				'lotserial' => 'Lot / Serial Breakdown',
				'bin'       => 'Bin Breakdown'
			)
		),
		'physicalcount_savebin' => array(
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Keep Bin Saved after submission?',
			'description' => 'Populates Bin based on last submit',
			'notes'       => "Populates Bin based on last submit"
		),
		'receive_lotserial_as_single' => array(
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Receive Lots as Single Items?',
			'description' => 'Receive Lots as Single Items',
			'notes'       => "Receive Lots as Single Items"
		),
		'receive_force_bin_itemlookup' => array(
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Require Bin when looking up Item in Receving?',
			'description' => 'Choose to Require the bin ID at Item Search',
			'notes'       => ""
		),
		'receive_disregard_bin' => array(
			'type'        => 'checkbox',
			'label'       => 'Hide / Readonly Bin when Looking up',
			'description' => 'Disregard Bin when Looking up',
			'notes'       => ""
		),
	);

	const DEFAULT_CONFIG = array(
		'allow_negativeinventory' => false,
		'show_inventoryresults'   => 'lotserial',
		'physicalcount_savebin'   => true,
		'receive_lotserial_as_single' => false,
		'receive_force_bin_itemlookup' => false,
		'receive_disregard_bin'   => false
	);

	/**
	 * Return number of decimals used for item quantities
	 * @return int
	 */
	public function decimal_places() {
		return ConfigSalesOrderQuery::create()->findOne()->decimal_places;
	}

	/* =============================================================
			ProcessWire Module Functions
	=============================================================== */
	public function init() {
		parent::init();
		$this->wire('modules')->get('ConfigsFields')->init_config($this);
	}

	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso Warehouse Inventory Config Module',
			'version' => 101,
			'summary' => 'Handles Dplus Warehouse Inventory Configurations',
			'singular' => true,
			'autoload' => true
		);
	}

	static public function getModuleConfigInputfields(array $data) {
		$modules = wire('modules');
		$fieldmaker = $modules->get('ConfigsFields');
		$fields = new InputfieldWrapper();
		$data = array_merge(self::DEFAULT_CONFIG, $data);

		foreach (self::CONFIG_FIELDS as $name => $traits) {
			$f = $fieldmaker->get_module_config_inputfield($traits, $name, $data[$name]);
			$fields->add($f);
		}
		return $fields;
	}
}
