<?php namespace ProcessWire;

/**
 * Configs
 *
 * Installs sub-modules
 * Exports Config Values, app configurations
 * Imports configs
 *
 * @property string $exportPath  path that configs dump are exported to
 * @property string $exportUrl   URL  that configs DB dump is exported to
 */
class Configs extends Process {
	const EXTRA_MODULES = array(
		'DplusConnectDatabase',
		'DplusOnlineDatabase',
		'FilterUserActions',
		'FilterBookings'
	);

	const CONFIG_PROPERTIES = array(
		'company',
		'companynbr'
	);

	const CONFIG_ZIP  = 'configs.zip';

	const CONFIG_FILE = 'configs.json';

	const CONFIG_TEMPLATE_CUSTOMER = 'config-customer';

	protected $exportPath;

	protected $exportURL;

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');
		$modules->refresh();

		foreach ($info['installs'] as $module_name) {
			$modules->install($module_name);
		}
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Configs Module',
			'version' => 101,
			'summary' => 'Handles Dplus Application Configurations',
			'singular' => true,
			'autoload' => true,
			'icon'     => 'cogs',
			'page' => array(
				'name' => 'configs-export',
				'parent' => 'setup',
			),
			'requires' => array(),
			'installs' => array(
				'ConfigsCi', 'ConfigsIi',
				'ConfigsSalesOrders',
				'ConfigsWarehouseInventory', 'ConfigsBinr',
				'ConfigsWarehouseLabelPrinting', 'ConfigsWarehousePicking'
			),
		);
	}

	public function init() {
		$this->tmpdir     = __DIR__ . '/configs/';
		$this->exportdir  = 'backups/export-configs/';
		$this->exportPath = $this->config->paths->assets . $this->exportdir;
		$this->exportURL  = $this->config->urls->assets  . $this->exportdir;
	}

/* =============================================================
	Module Form Functions
============================================================= */
	/**
	 * Build the initial form used by the profile exporter
	 */
	protected function buildForm() {
		/** @var InputfieldForm $form */
		$form = $this->modules->get('InputfieldForm');

		$info = self::getModuleInfo();
		$form->description = $info['summary'];

		/** @var InputfieldSubmit $f */
		$f = $this->modules->get('InputfieldSubmit');
		$f->attr('name', 'submit_export');
		$f->attr('value', $this->_('Start Export'));
		$f->icon = 'download';
		$form->add($f);

		if (is_file($this->exportPath.self::CONFIG_ZIP)) {
			$f = $this->modules->get('InputfieldSubmit');
			$f->attr('name', 'submit_import');
			$f->attr('value', $this->_('Start Import'));
			$f->icon = 'upload';
			$form->add($f);
		}
		return $form;
	}

	/**
	 * Present the instructions and initial info collection form
	 * @return string
	 */
	public function ___execute() {
		$form = $this->buildForm();

		if ($this->input->post('submit_export') || $this->input->post('submit_import')) {
			$out = $this->processInput($form);
			if($out) return $out;
		}

		return $form->render();
	}

	/**
	 * Process the initial info collection form and begin export
	 * @param  InputfieldForm $form
	 * @return bool
	 * @throws WireException
	 */
	protected function processInput($form) {
		// process form
		$form->processInput($this->input->post);
		if($form->getErrors()) return false;

		if ($this->input->post('submit_export')) {
			$form = $this->formImportExport();
			$out =
				"<h2>" . $this->_('The next step will copy/archive all of your site config files, and values') . "</h2>" .
				"<p>" . $this->_('It will not make any changes to your current site. If your site has a lot of files, this could take while, so please be patient.') . "</p>" .
				$form->render();
		}

		if ($this->input->post('submit_import')) {
			$form = $this->formImportExport('import');
			$out =
				"<h2>" . $this->_('The next step will import all of your site config values and files') . "</h2>" .
				"<p>" . $this->_('This could take while, so please be patient.') . "</p>" .
				$form->render();
		}

		return $out;
	}

	private function formImportExport($action = 'export') {
		// present screen for next step
		/** @var InputfieldForm $form */
		$form = $this->modules->get('InputfieldForm');
		$form->attr('action', "./$action/");

		/** @var InputfieldSubmit $f */
		$f = $this->modules->get('InputfieldSubmit');
		$f->attr('name', "submit_$action");
		$f->attr('value', ucfirst($action));
		$f->icon = 'angle-right';
		$form->add($f);
		return $form;
	}

	/**
	 * Copy Configs
	 * @return string
	 */
	public function ___executeExport() {
		$this->export_configs();
		set_time_limit(3600);

		$made  = $this->makeZipfile();
		$moved = $this->moveZipfile();

		if (is_file($this->exportPath.self::CONFIG_ZIP)) {
			$this->cleanupTmpDirectory();
			$out =
				"<h2>Your Configs have been Exported</h2>" .
				"<p><a href='../download/configs.zip'>{$this->exportURL}configs.zip</a></p>" .
				$this->button("../download/configs.zip", sprintf($this->_('Download'), "configs.zip"), 'cloud-download') .
				$this->removeButton();
		} else {
			$this->error($this->_('ZIP file creation failed. Try saving to server directory instead.'));
			$out = "<p>" . $this->button('../') . "</p>";
		}
		return $out;
	}

	/**
	 * Copy Configs
	 * @return string
	 */
	public function ___executeImport() {
		if (is_file($this->exportPath.self::CONFIG_ZIP)) {
			$this->import();
			$out =
				"<h2>Your Configs have been Imported</h2>" .
				$this->removeButton();
		} else {
			$this->error($this->_('Import from ZIP file failed.'));
			$out = "<p>" . $this->button('../') . "</p>";
		}
		return $out;
	}

	/**
	 * Download site configs
	 */
	public function ___executeDownload() {
		$file = $this->sanitizer->pageName($this->input->urlSegment2);
		if(!$file) throw new WireException("No file specified");
		$file = basename($file, '.zip') . '.zip';
		$pathname = $this->exportPath . $file;
		if(!is_file($pathname)) throw new WireException("Invalid file: $pathname");
		wireSendFile($pathname);
	}

	/**
	 * Remove existing profile
	 * @return string
	 */
	public function ___executeRemove() {
		if (wireRmdir($this->exportPath, true)) {
			$this->message($this->_('Removed existing configs') . " - $this->exportURL");
			$this->session->redirect('../');
			return '';
		} else {
			$this->error($this->_('Error removing existing configs') . " - $this->exportURL");
			return $this->button('../');
		}
	}

	/**
	 * Render a button
	 * @param string $href
	 * @param string $label
	 * @param string $icon
	 * @param string $class
	 * @return string
	 */
	protected function button($href, $label = '', $icon = 'angle-right', $class = '') {
		if(empty($label)) $label = $this->labels['continue'];
		$btn = $this->modules->get('InputfieldButton');
		$btn->href = $href;
		$btn->icon = $icon;
		if($class) $btn->addClass($class);
		$btn->value = $label;
		return $btn->render();
	}

	/**
	 * Render a "remove" button with JS confirm dialog
	 * @return string
	 */
	protected function removeButton() {
		$btn = $this->modules->get('InputfieldButton');
		$btn->href = $this->wire('page')->url . 'remove/';
		$btn->icon = 'trash-o';
		$btn->value = 'Remove';
		$btn->addClass('ui-priority-secondary');
		return $btn->render();
	}

/* =============================================================
	Module Form Functions
============================================================= */
	/**
	 * Return Module Config Data for every module
	 * @param  string $name Module Name
	 * @return array
	 */
	public function getConfigModulesData() {
		$info = self::getModuleInfo();
		$modules = array_merge($info['installs'], self::EXTRA_MODULES);
		$data = array();

		foreach ($modules as $name) {
			if ($this->wire('modules')->isInstalled($name)) {
				$data[$name] = $this->wire('modules')->getConfig($name);
			}
		}
		return $data;
	}

	/**
	 * Return ProcessWire\Page('template=config-customer') data
	 * @return array
	 */
	public function getPwCustomerData() {
		$pw_cust = $this->getPwCustomer();
		$data = array();
		$data['company_name'] = $pw_cust->company_name;
		$data['address']      = $pw_cust->address;
		$data['images'] = [
			'logo_large' => $this->getLogoImageName($pw_cust, 'logo_large'),
			'logo_small' => $this->getLogoImageName($pw_cust, 'logo_small')
		];
		return $data;
	}

	/**
	 * Return Image Name for image property
	 * @param  Page        $pw_cust [description]
	 * @param  string      $prop    'logo_large' | 'logo_small'
	 * @return string|null
	 */
	public function getLogoImageName(Page $pw_cust, $prop) {
		if ($pw_cust->has($prop) === false) {
			return false;
		}
		if (get_class($pw_cust->$prop) == 'ProcessWire\Pageimage') {
			return $pw_cust->$prop ? $pw_cust->$prop->basename : false;
		}

		if (get_class($pw_cust->$prop) == 'ProcessWire\Pageimages') {
			return $pw_cust->$prop ? $pw_cust->$prop->first()->basename : false;
		}
		return false;
	}

	/**
	 * Return config-customer page
	 * @return Page
	 */
	public function getPwCustomer() {
		return $this->wire('pages')->get('template=' . self::CONFIG_TEMPLATE_CUSTOMER);
	}

	/**
	 * Return Config file (config.php) Data
	 * @return array
	 */
	public function getPwConfigData() {
		$config = $this->wire('config');
		$data = array();

		foreach (self::CONFIG_PROPERTIES as $property)  {
			$data[$property] = $config->$property;
		}
		return $data;
	}

	/**
	 * Return Application Configuration Data Including Module Configs
	 * @return array
	 */
	public function getAllConfigsData() {
		$data = array();
		$data['configs']         = $this->getConfigModulesData();
		$data['config-file']     = $this->getPwConfigData();
		$data['config-customer'] = $this->getPwCustomerData();
		return $data;
	}

	/**
	 * Writes Configs File for Config Data
	 * @return array Application Configuration Data
	 */
	public function writeConfigsJson() {
		$data = $this->getAllConfigsData();
		$dir  = $this->getTmpDirectory();
		$file = $dir . self::CONFIG_FILE;
		file_put_contents($file, json_encode($data, JSON_PRETTY_PRINT));
		return $data;
	}

	/**
	 * Exports config-customer PW Images to configs directory
	 * @return void
	 */
	public function exportPwConfigCustomer() {
		$dir = $this->getTmpDirectory();
		$pw_cust = $this->getPwCustomer();

		if ($pw_cust->logo_large) {
			$imagefile = $pw_cust->logo_large->first();
			copy($imagefile->filename(), $dir . $imagefile->basename);
		}

		if ($pw_cust->logo_small) {
			$imagefile = $pw_cust->logo_small->first();
			copy($imagefile->filename(), $dir . $imagefile->basename);
		}
	}

	/**
	 * Exports Config Files
	 * @return array Configs Data
	 */
	public function export_configs() {
		$this->exportPwConfigCustomer();
		return $this->writeConfigsJson();
	}

	/**
	 * Return the Directory all the Export Files will be written to
	 * @return string
	 */
	public function getExportDirectory() {
		$dir = $this->exportPath;
		if (!file_exists($dir)) {
			mkdir($dir);
		}
		return $dir;
	}

	/**
	 * Return the Directory all the Export Files will be written to
	 * @return string
	 */
	public function getImportDirectory() {
		$dir = $this->exportPath;
		$dir .= 'configs/';
		if (!file_exists($dir)) {
			mkdir($dir);
		}
		return $dir;
	}

	/**
	 * Return the Directory all the Export Files will be written to
	 * @return string
	 */
	public function getTmpDirectory() {
		$dir = $this->tmpdir;
		if (!file_exists($dir)) {
			mkdir($dir);
		}
		return $dir;
	}

	/**
	 * Returns Exported configs.json file
	 * @return array
	 */
	public function getImportJsonExist() {
		$dir = $this->getImportDirectory();
		$configfile = $dir . self::CONFIG_FILE;
		return file_exists($configfile);
	}

	/**
	 * Returns Exported configs.json file
	 * @return array
	 */
	public function getImportJson() {
		$dir = $this->getImportDirectory();
		$configfile = $dir . self::CONFIG_FILE;
		return json_decode(file_get_contents($configfile), true);
	}

	/**
	 * Processes Export Config File and Imports the Config Data
	 * @return array
	 */
	public function import() {
		$this->unzipExportZip();
		$json = $this->getImportJson();
		$data['json'] = $json;
		$data['results'] = array();
		$this->importPwCustomerData($json);
		$this->importPwCustomerImages($json);
		$data['results']['modules'] = $this->importConfigModulesData($json);
		return $data;
	}

	/**
	 * Unzip Exported Zip into Import Directory
	 * @return array
	 */
	public function unzipExportZip() {
		$dir = $this->getExportDirectory();
		return $this->wire('files')->unzip($dir.self::CONFIG_ZIP, $dir);
	}

	/**
	 * Sets the config-customer PW Page values
	 * @param  array  $data config.json data
	 * @return bool         Was Succesful?
	 */
	public function importPwCustomerData(array $data) {
		if (array_key_exists('config-customer', $data)) {
			$custdata = $data['config-customer'];
			$pw_cust = $this->getPwCustomer();
			$pw_cust->of(false);

			foreach ($custdata as $key => $value)  {
				if ($key != 'images') {
					$pw_cust->$key = $value;
				}
			}
			return $pw_cust->save();
		}
		return false;
	}

	/**
	 * Sets the config-customer Page Images
	 * @param  array  $data config.json data
	 * @return bool         Did Images save?
	 */
	public function importPwCustomerImages(array $data) {
		if (array_key_exists('config-customer', $data)) {
			$dir = $this->getExportDirectory();
			$custdata = $data['config-customer'];
			$pw_cust = $this->getPwCustomer();
			$pw_cust->of(false);

			if ($custdata['images']['logo_large']) {
				$file = $dir . $custdata['images']['logo_large'];
				$pw_cust->logo_large->deleteAll();
				$pw_cust->logo_large = $file;
			}

			if ($custdata['images']['logo_small']) {
				$file = $dir . $custdata['images']['logo_small'];
				$pw_cust->logo_large->deleteAll();
				$pw_cust->logo_large = $file;
			}
			return $pw_cust->save();
		}
		return false;
	}

	/**
	 * Imports Each Config Modules Data
	 * @param  array  $data array
	 * @return array
	 */
	public function importConfigModulesData(array $data) {
		$results = array();
		$modules = $this->wire('modules');

		if (array_key_exists('configs', $data)) {
			foreach ($data['configs'] as $class => $configdata) {
				if ($modules->isInstalled($class)) {
					if ($configdata) {
						$results[$class] = $modules->saveConfig($class, $configdata);
					} else {
						$results[$class] = 'Empty Config Data';
					}
				} else {
					$results[$class] = "Not Installed";
				}
			}
		}
		return $results;
	}

	/**
	 * Removes Config files after 6 days for security
	 * @return void
	 */
	public function cleanupExportDirectory() {
		$dir = $this->getExportDirectory();
		$configfile = $dir . self::CONFIG_FILE;

		if (file_exists($configfile)) {
			$lastmodified = filemtime($configfile);
			$lastmodified_date = date('Y-m-d', $lastmodified);

			if (strtotime('now') > strtotime("$lastmodified_date +6 days")) {
				$this->deleteFiles($dir);
			}
		}
	}

	/**
	 * Removes Files in a given directory
	 * @param  string $directory Directory Path
	 * @return void
	 */
	public function deleteFiles($directory) {
		if (is_dir($directory)) {
			$files = glob($directory . '*', GLOB_MARK); //GLOB_MARK adds a slash to directories returned

			foreach($files as $file){
				$this->deleteFiles($file);
			}
			rmdir($directory);
		} elseif(is_file($directory)) {
			unlink($directory);
		}
	}

	/**
	 * Create Zip File from Tmp Config Directory
	 * @return bool
	 */
	private function makeZipfile() {
		$this->getTmpDirectory();

		$zipfile = $this->tmpdir . self::CONFIG_ZIP;
		// templates and modules
		$files = array($this->getTmpDirectory());
		$options = array(
			'exclude' => $this->getTmpDirectory(),
			'allowEmptyDirs' => false
		);
		$result = wireZipFile($zipfile, $files, $options);
		$errors = $result['errors'];
		return $result;
	}

	/**
	 * Remove files from Tmp Directory
	 * @return bool
	 */
	private function cleanupTmpDirectory() {
		return $this->deleteFiles($this->getTmpDirectory());
	}

	/**
	 * Move Zip file from Tmp Directory to final directory
	 * @return bool
	 */
	private function moveZipfile() {
		$this->getExportDirectory();
		return rename($this->tmpdir.self::CONFIG_ZIP, $this->exportPath.self::CONFIG_ZIP);
	}
}
