<?php namespace ProcessWire;

use PurchaseOrder, SalesOrder;

/**
 * DplusSanitizer
 *
 * Module for Adding Hooks to the Sanitizer Class
 */
class DplusSanitizer extends WireData implements Module {

	public function init() {
		$this->addHook('Sanitizer::yn', function(HookEvent $event) {
			$sanitizer = $event->object;
			$value = strtoupper($event->arguments(0));
			$event->return = $value == 'Y' ? 'Y' : 'N';
		});

		$this->addHook('Sanitizer::ynbool', function(HookEvent $event) {
			$sanitizer = $event->object;
			$value = strtoupper($event->arguments(0));
			$event->return = $value == 'Y' ? true : false;
		});

		$this->addHook('Sanitizer::phoneus', function(HookEvent $event) {
			$sanitizer = $event->object;
			$value = $event->arguments(0);
			$phone = preg_replace('^\(?([0-9]{3})\)?[-.●]?([0-9]{3})[-.●]?([0-9]{4})$^', '$1-$2-$3' , $value);
			$event->return = $phone;
		});

		$this->addHook('Sanitizer::ponbr', function(HookEvent $event) {
			$sanitizer = $event->object;
			$value = $event->arguments(0);
			$ponbr = str_pad($value, PurchaseOrder::LENGTH , "0", STR_PAD_LEFT);
			$event->return = $ponbr;
		});

		$this->addHook('Sanitizer::ordn', function(HookEvent $event) {
			$sanitizer = $event->object;
			$value = $event->arguments(0);
			$ponbr = str_pad($value, SalesOrder::LENGTH , "0", STR_PAD_LEFT);
			$event->return = $ponbr;
		});
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Sanitizer',
			'version' => 101,
			'summary' => 'Adds Hooks to the Sanitizer Class',
			'singular' => true,
			'autoload' => true,
		);
	}
}
