<?php
	use LogpermQuery;
	use Logperm;
	use LogmQuery;
	use Logm;

	class DplusUser extends WireData implements Module {
		private $className;
		public static $user_roles = array(
			'default' => array(
				'dplus-code' => '',
				'label' => 'Default',
				'homepage' => ''
			),
			'sales-manager' => array(
				'dplus-code' => 'slsmgr',
				'label' => 'Sales Manager',
				'homepage' => ''
			),
			'sales-rep' => array(
				'dplus-code' => 'slsrep',
				'label' => 'Sales Rep',
				'homepage' => ''
			),
			'warehouse' => array(
				'dplus-code' => 'whse',
				'label' => 'Warehouse',
				'homepage' => ''
			),
			'warehouse-manager' => array(
				'dplus-code' => 'whsmgr',
				'label' => 'Warehouse Manager',
				'homepage' => ''
			)
		);

		public static function getModuleInfo() {
			return array(
				'title' => 'Dplus User Extension',
				'version' => 101,
				'summary' => 'Extends User for Dplus',
				'singular' => true,
				'autoload' => true,
			);
		}

		public function init() {
			$this->add_hooks();
		}

		public function install() {
			foreach (self::$user_roles as $code => $user_role) {
				if ($this->wire('roles')->find('name='.$user_role['dplus-code'])->count) {
					$role = $this->wire('roles')->get('name='.$user_role['dplus-code']);
				} else {
					$role = new Role();
					$role->name = $user_role['dplus-code'];
				}

				$role->code = $code;
				$role->title = $role->headline = $user_role['label'];
				$role->homepage = $user_role['homepage'];
				$role->save();
			}
		}

		/**
		 * Properties are protected from modification without function, but
		 * We want to allow the property values to be accessed
		 * @param  string $property The property trying to be accessed
		 * @return mixed		   Property value or Error
		 */
		public function __get($property) {
			if (property_exists($this, $property)) {
				return $this->$property;
			} else {
				if ($property != 'name') {
					$this->error("This property ($property) does not exist");
					return false;
				}
			}
		}

		public function add_hooks() {
			$this->addHook('User::setup', function($event) {
				$user = $event->object;
				$sessionID = $event->arguments(0);
				$event->return = $this->setup_user($user, $sessionID);
			});
		}

		/**
		 * Sets User Properties needed for Dplus Online and functons
		 * @param  User   $user
		 * @param  string $sessionID User SessionID
		 * @return string
		 */
		public function setup_user(User $user, $sessionID) {
			$q = LogpermQuery::create();

			if ($q->is_loggedin($sessionID)) {
				$user->loggedin = true;
				$this->setup_user_logperm($user, $sessionID);
				$this->setup_user_logm($user);
			} else {
				$user->loggedin = false;
			}
		}

		/**
		 * Sets User Properties for Login Id, and Login Name
		 * @uses  LogPermQuery
		 * 
		 * @param  User   $user
		 * @param  string $sessionID User SessionID
		 * @return void

		 */
		public function setup_user_logperm(User $user, $sessionID) {
			$q = LogpermQuery::create();
			$logperm = $q->findOneBySessionid($sessionID);
			$user->loginid = $logperm->loginid;
			$user->fullname = $logperm->loginname;
		}

		/**
		 * Sets User Properties and role(s) based out of Logm
		 * Then calls a function based on the Logm User role to add additional Properties
		 * @param  User $user
		 * @return void
		 */
		private function setup_user_logm(User $user) {
			$logmuser = LogmQuery::create()->findOneByLoginid($user->loginid);
			$role = strtolower($logmuser->role);
			$user->addRole($role);
			$user->dplusrole = $role;
			$user->roleid   = $logmuser->roleid;
			$user->company  = $logmuser->company;
			$user->email    = $logmuser->email;
			
			$function = "setup_user_$role";

			if (method_exists($this, $function)) {
				$this->$function($user);
			}
		}

		/**
		 * Sets User Properties needed for a Sales Rep User
		 * @param  User $user
		 * @return void
		 */
		private function setup_user_slsrep(User $user) {
			$logmuser = LogmQuery::create()->findOneByLoginid($user->loginid);
			$user->repid = $logmuser->roleid;
		}

		/**
		 * Sets User Properties needed for a Sales Manager User
		 * @uses self::setup_user_slsrep()
		 * 
		 * @param  User $user
		 * @return void
		 */
		private function setup_user_slsmgr(User $user) {
			$this->setup_user_slsrep($user);
		}
	}