<?php namespace ProcessWire;

include_once(__DIR__.'/vendor/autoload.php');

use Dplus\Mar;
use Dplus\PhoneBook;

/**
 * Dplus
 */
class Dplus extends WireData implements Module {
	public function init() {
		$this->mar        = Mar\Factory::instance();
		$this->phoneBooks = PhoneBook\Factory::instance();
	}

	public static function getModuleInfo() {
		$infoArray = array(
			'title' => __('Dplus'),
			'version' => 115,
			'summary' => __("Autoloads Dplus"),
			'autoload' => true,
			'singular' => true,
			'author' => 'pauldro',
			'icon' => 'database'
		);
		return $infoArray;
	}
}
