<?php namespace ProcessWire;

	use QuoteQuery, Quote;

	use Propel\Runtime\ActiveQuery\Criteria;

	class FilterQuotes extends WireData implements Module {

		/**
		 * Query
		 * @var QuoteQuery
		 */
		protected $query;

		/**
		 * Returns Query
		 * @return QuoteQuery
		 */
		public function get_query() {
			return $this->query;
		}

		/**
		 * Initializes Query
		 * NOTE: Filters by Sales Rep if provided user is a Sales rep
		 *
		 * @param  User   $user User to Check if they are a Sales Person
		 * @return void
		 */
		public function init_query(User $user) {
			$this->query = QuoteQuery::create();

			if ($user->is_salesrep()) {
				$this->query->filterbySalesPerson($user->roleid);
			}
		}

		/**
		 * Applies Filters to the Query
		 * NOTE:: Filters include TODO::
		 *
		 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
		 * @return void
		 */
		public function filter_query(WireInput $input) {
			$this->filter_custid($input);
			$this->filter_shiptoid($input);

			if ($input->get->filter) {

			} else {
				$input->get->status = array();
			}
		}

		/**
		 * Filters Query by Customer ID
		 *
		 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
		 * @return void
		 */
		public function filter_custid($input) {
			if ($input->get->custID) {
				if (is_array($input->get->custID)) {
					$filter = $input->get->array('custID');
				} else {
					$filter = $input->get->text('custID');
				}
				$this->query->filterByCustid($filter);
			}
		}

		/**
		 * Filters Query by Customer ShiptoID
		 *
		 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
		 * @return void
		 */
		public function filter_shiptoid($input) {
			if ($input->get->shiptoID && $input->get->custID) {
				if (is_array($input->get->shiptoID)) {
					$filter = $input->get->array('shiptoID');
				} else {
					$filter = $input->get->text('shiptoID');
				}
				$this->query->filterByShiptoid($filter);
			}
		}

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
		/**
		 * ProcessWire Module Info
		 *
		 * @return void
		 */
		public static function getModuleInfo() {
			return array(
				'title' => 'Dpluso filter Quotes Module',
				'version' => 101,
				'summary' => 'Handles Quotes Filtering',
				'singular' => true,
				'autoload' => true,
			);
		}
	}
