<?php namespace ProcessWire;

use DplusUserQuery, DplusUser;

/**
 * ValidateMsa
 * Module to validate MSA Codes
 */
class ValidateMsa extends WireData implements Module {
	/**
	 * Validate Login ID
	 * @param  string $loginID Login ID
	 * @return bool
	 */
	public function loginid($loginID) {
		$q = DplusUserQuery::create();
		$q->filterByLoginid($loginID);
		return boolval($q->count());
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Lookup Module',
			'version' => 101,
			'summary' => 'Handles Lookup Modules Installation & Updates',
			'singular' => true,
			'autoload' => true,
			'installs' => array()
		);
	}

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');
		$modules->refresh();

		foreach ($info['installs'] as $module_name) {
			if (!$modules->isInstalled($module_name)) {
				$result = $modules->install($module_name);
			}
		}
	}
}
