<?php namespace ProcessWire;

/**
 * Lookup
 *
 * Parent Module to Install Sub Lookup Modules
 */
class Lookup extends WireData implements Module {

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');
		$modules->refresh();

		foreach ($info['installs'] as $module_name) {
			if (!$modules->isInstalled($module_name)) {
				$result = $modules->install($module_name);
			}
		}
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Lookup Module',
			'version' => 101,
			'summary' => 'Handles Lookup Modules Installation & Updates',
			'singular' => true,
			'autoload' => true,
			'installs' => array(
				'LookupCustomer',
				'LookupItem',
				'LookupSalesOrder',
				'LookupVendor',
				'LookupQuote',
				'LookupWarehouse',
				'ValidatePurchaseOrderNbr',
				'ValidateSalesOrder',
				'ValidateVendorId',
				'ValidateAr',
				'ValidateAp',
				'ValidateItm',
				'ValidatePo',
				'ValidateCxm'
			)
		);
	}
}
