<?php namespace ProcessWire;

use Propel\Runtime\ActiveQuery\Criteria;

use WarehouseQuery, Warehouse;

/**
 * Lookup Warehouse
 *
 * Class for Looking up / Validating Warehouse
 *
 * @property string $exists  Warehouse Exists
 * @property string $whseID  Warehouse ID
 * @property string $request What was sent to find Sales Order / Invoice Number
 * @property string $source  so_head | so_head_hist
 */
class LookupWarehouse extends WireData implements Module {
	public function __construct() {
		$this->exists  = false;
		$this->whseID  = '';
	}

	/**
	 * Returns if Sales Order Number exists in the Sales Order table
	 * @property string $whseID  Warehouse ID
	 * @return bool
	 */
	public function lookup_warehouse($whseID) {
		$q = WarehouseQuery::create();
		$q->filterById($whseID);

		if ($q->count()) {
			$this->exists = true;
			$this->whseID = $whseID;
		} else {
			$this->exists = false;
		}
		return $this->exists;
	}

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Warehouse Lookup Module',
			'version' => 101,
			'summary' => 'Handles Warehouse Lookup',
			'singular' => true,
			'autoload' => true,
			'installs' => array()
		);
	}
}
