<?php namespace ProcessWire;

use Propel\Runtime\ActiveQuery\Criteria;

use ApTermsCodeQuery, ApTermsCode;
use ApBuyerQuery, ApBuyer;
use CountryCodeQuery, CountryCode;
use VendorQuery, Vendor;

/**
 * ValidateAp
 *
 * Class for Validating AP table codes, IDs
 */
class ValidateAp extends WireData implements Module {

	/**
	 * Return if Vendor ID exists
	 * @param  string $vendorID  Vendor ID
	 * @return bool
	 */
	public function vendorid($vendorID) {
		$q = VendorQuery::create();
		$q->filterByVendorid($vendorID);
		return boolval($q->count());
	}

	/**
	 * Return if AP Terms Code Exists
	 * @param  string $code AP Terms Code
	 * @return bool
	 */
	public function termscode($code) {
		$q = ApTermsCodeQuery::create();
		$q->filterByCode($code);
		return boolval($q->count());
	}

	/**
	 * Return if Country Code Exists
	 * @param  string $code Country Code
	 * @return bool
	 */
	public function countrycode($code) {
		$q = CountryCodeQuery::create();
		$q->filterByCode($code);
		return boolval($q->count());
	}

	/**
	 * Return if AP Buyer Code Exists
	 * @param  string $code CAP Buyer Code
	 * @return bool
	 */
	public function buyercode($code) {
		$q = ApBuyerQuery::create();
		$q->filterByCode($code);
		return boolval($q->count());
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Validate AP Module',
			'version' => 101,
			'summary' => 'Validates AP table codes',
			'singular' => true,
			'autoload' => true,
			'installs' => array(),
		);
	}
}
