<?php namespace ProcessWire;

use Propel\Runtime\ActiveQuery\Criteria;

use ShipviaQuery, Shipvia;
use CustomerQuery, Customer;

/**
 * ValidateAr
 *
 * Class for Validating AR table codes, IDs
 *
 * @property bool $exists      Code / ID exists
 */
class ValidateAr extends WireData implements Module {
	public function __construct() {
		$this->exists = false;
	}

	/**
	 * Return true if Customer ID exists Exists
	 * @param  string $custID Customer ID
	 * @return bool
	 */
	public function custid($custID) {
		$q = CustomerQuery::create();
		$q->filterByCustid($custID);

		if ($q->count()) {
			$this->exists = true;
		}
		return $this->exists;
	}

	/**
	 * Return if Ship-Via Code Exists
	 * @param  string $code Ship-Via Code
	 * @return bool
	 */
	public function shipvia($code) {
		$q = ShipviaQuery::create();
		$q->filterByCode($code);

		if ($q->count()) {
			$this->exists = true;
		}
		return $this->exists;
	}



/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Validate AR Module',
			'version' => 101,
			'summary' => 'Validates AR table codes',
			'singular' => true,
			'autoload' => true,
			'installs' => array(),
		);
	}
}
