<?php namespace ProcessWire;

use Propel\Runtime\ActiveQuery\Criteria;
use Purl\Url;

use PurchaseOrderQuery, PurchaseOrder;
use PurchaseOrderDetailReceivingQuery, PurchaseOrderDetailReceiving;
use ApInvoiceDetailQuery, ApInvoiceDetail;
use WarehouseQuery, Warehouse;
use VendorQuery, Vendor;
use ConfigSalesOrderQuery, ConfigSalesOrder;
use ConfigPoQuery, ConfigPo;
use ShipviaQuery, Shipvia;
use ApTermsCodeQuery, ApTermsCode;
use CountryCodesQuery, CountryCodes;

use EditPoHeadQuery, EditPoHead;
use EditPoDetailQuery, EditPoDetail;
use StatesQuery, States;

include_once(__DIR__.'/MpoResponse.php');


/**
 * PurchaseOrderEdit
 *
 * Handles Editing of PO
 * @property string sessionID Session ID
 */
class PurchaseOrderEdit extends WireData implements Module {
	const PERMISSION_DPLUS = 'epo';

	/**
	 * Returns Query for Purchase Order Header Edit
	 * @param  string $ponbr Purchase Order Number
	 * @return EditPoHeadQuery
	 */
	public function get_query_header($ponbr) {
		$q = EditPoHeadQuery::create();
		$q->filterBySessionid($this->sessionID);
		$q->filterByPonbr($ponbr);
		return $q;
	}

	/**
	 * Returns Query for Purchase Order Details Edit
	 * @param  string $ponbr Purchase Order Number
	 * @return EditPoDetailQuery
	 */
	public function get_query_details($ponbr) {
		$q = EditPoDetailQuery::create();
		$q->filterBySessionid($this->sessionID);
		$q->filterByPonbr($ponbr);
		return $q;
	}

	/**
	 * Return if Header and Details are available to Edit
	 * @param  string $ponbr Purchase Order Number
	 * @return bool
	 */
	public function exists_editable($ponbr) {
		return $this->exists_editable_header($ponbr) && $this->exists_editable_details($ponbr);
	}

	/**
	 * Return if PO header is available for editing
	 * @param  string $ponbr Purchase Order Number
	 * @return bool
	 */
	public function exists_editable_header($ponbr) {
		$q = $this->get_query_header($ponbr);
		return boolval($q->count());
	}

	/**
	 * Return if PO items are available for editing
	 * @param  string $ponbr Purchase Order Number
	 * @return bool
	 */
	public function exists_editable_details($ponbr) {
		$q = $this->get_query_details($ponbr);
		return boolval($q->count());
	}

	/**
	 * Return Editable PO Header
	 * @param  string $ponbr Purchase Order Number
	 * @return EditPoHead
	 */
	public function get_editable_header($ponbr) {
		$q = $this->get_query_header($ponbr);
		return $q->findOne();
	}

/* =============================================================
	CRUD Processing Functions
============================================================= */
	/**
	 * Process Input Data and act on upon action
	 * @param  WireInput $input Input Data
	 * @return void
	 */
	public function process_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;

		switch ($values->text('action')) {
			case 'add-item':
				$this->process_input_add_item($input);
				break;
			case 'update-item':
				$this->process_input_update_item($input);
				break;
			case 'update-header':
				$this->process_input_update_header($input);
				break;
			case 'exit':
				break;
		}
	}

	/**
	 * Add Item To Purchase Order
	 * @param WireInput $input Input data
	 * @return void
	 */
	public function process_input_add_item(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$q = $this->get_query_details($values->text('ponbr'));
		$count_before = $q->count();
		$this->request_add_item($values->text('ponbr'), $values->text('itemID'), $values->int('qty'));
		$count_after = $q->count();

		if ($count_after > $count_before) {
			$response = MpoResponse::response_success($values->text('ponbr'), $values->text('itemID') . ' was added to PO');
		} else {
			$response = MpoResponse::response_error($values->text('ponbr'), $values->text('itemID') . ' was not added to PO');
		}
		$this->wire('session')->response_epo = $response;
	}

	/**
	 * Update / Edit Purchase Order Item
	 * @param  WireInput $input Input Data
	 * @return void
	 */
	public function process_input_update_item(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$ponbr = $values->text('ponbr');
		$linenbr = $values->int('linenbr');
		$q = $this->get_query_details($ponbr);
		$item = $q->findOneByLinenbr($linenbr);
		$this->update_item($item, $input);

		if ($item->save()) {
			$this->request_update_item($ponbr, $linenbr);
			$response = MpoResponse::response_success($values->text('ponbr'), "Line #$linenbr was updated");
		} else {
			$response = MpoResponse::response_error($values->text('ponbr'), "Line #$linenbr was not updated");
		}
		$this->wire('session')->response_epo = $response;
	}

	/**
	 * Updates EditPoDetail Record
	 * @param  EditPoDetail $item  Purchase Order Item
	 * @param  WireInput    $input Input Data
	 * @return void
	 */
	protected function update_item(EditPoDetail $item, WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$item->setItemid($values->text('itemID'));
		$item->setDescription($values->text('description'));
		$item->setVendoritemid($values->text('vendoritemID'));
		$item->setWhse($values->text('whse'));
		$item->setQty_ordered($values->text('qty_ordered'));
		$item->setCost($values->text('cost'));
		$item->setCost_total($values->text('cost_total'));
	}

	/**
	 * Update / Edit Purchase Order Header
	 * @param  WireInput $input Input Data
	 * @return void
	 */
	public function process_input_update_Header(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$ponbr = $values->text('ponbr');
		$po = $this->get_editable_header($ponbr);
		$this->update_header($po, $input);

		if ($po->save()) {
			$this->request_update_header($ponbr);
			$response = MpoResponse::response_success($values->text('ponbr'), "PO # $ponbr header was updated");
		} else {
			$response = MpoResponse::response_error($values->text('ponbr'), "PO # $ponbr header was not updated");
		}
		$this->wire('session')->response_epo = $response;
	}

	/**
	 * Updates EditPoHead Record
	 * @param  EditPoHead  $item  Purchase Order
	 * @param  WireInput   $input Input Data
	 * @return void
	 */
	protected function update_header(EditPoHead $po, WireInput $input) {
		$this->init_configs();
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;

		$this->update_header_shipto($po, $input);
		$this->update_header_contact($po, $input);
		$this->update_header_dates($po, $input);
		$this->update_header_validated($po, $input);

		$po->setTax_exempt($values->yn('tax_exempt'));
		$po->setFuturebuy($values->yn('futurebuy'));
		$po->setLandedcost($values->text('landedcost'));
		$po->setReleasenbr($values->text('releasenbr'));
		$po->setReference($values->text('reference'));
		$po->setReference($values->text('reference'));
	}

	/**
	 * Update PO Header Shipto fields
	 * @param  EditPoHead $po    Purchase Order
	 * @param  WireInput  $input Input Data
	 * @return void
	 */
	protected function update_header_shipto(EditPoHead $po, WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;

		$po->setShipto_name($values->text('shipto_name'));
		$po->setShipto_address($values->text('shipto_address'));
		$po->setShipto_address2($values->text('shipto_address2'));
		$po->setShipto_address3($values->text('shipto_address3'));
		$po->setShipto_city($values->text('shipto_city'));
		$po->setShipto_state($values->text('shipto_state'));
		$po->setShipto_zip($values->text('shipto_zip'));
	}

	/**
	 * Update PO Header contact fields
	 * @param  EditPoHead $po    Purchase Order
	 * @param  WireInput  $input Input Data
	 * @return void
	 */
	protected function update_header_contact(EditPoHead $po, WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;

		$po->setContact($values->text('contact'));
		$po->setPhone(str_replace('-', '', $values->text('phone')));
		$po->setFax(str_replace('-', '', $values->text('fax')));
		$po->setEmail($values->text('email'));
	}

	/**
	 * Update PO Header Date fields
	 * @param  EditPoHead $po    Purchase Order
	 * @param  WireInput  $input Input Data
	 * @return void
	 */
	protected function update_header_dates(EditPoHead $po, WireInput $input) {
		$format = PurchaseOrder::FORMAT_DATE;
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;

		$po->setDate_ordered(date($format, strtotime($values->text('date_ordered'))));

		if (!$this->configs->po->edit_date_shipped_detail()) {
			$po->setDate_shipped(date($format, strtotime($values->text('date_shipped'))));
		}

		if (!$this->configs->po->edit_date_acknowledged_detail()) {
			$po->setDate_acknowledged(date($format, strtotime($values->text('date_acknowledged'))));
		}

		if (!$this->configs->po->edit_date_cancel_detail()) {
			$po->setDate_cancel(date($format, strtotime($values->text('date_cancel'))));
		}
	}

	/**
	 * Update PO Header fields that need external validation
	 * @param  EditPoHead $po    Purchase Order
	 * @param  WireInput  $input Input Data
	 * @return void
	 */
	protected function update_header_validated(EditPoHead $po, WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;

		$validate = new WireData();
		$validate->vendor = $this->wire('modules')->get('ValidateVendorId');
		$validate->ar     = $this->wire('modules')->get('ValidateAr');
		$validate->ap     = $this->wire('modules')->get('ValidateAp');

		if ($validate->vendor->validate($values->text('vendorID'))) {
			$po->setVendorid($values->text('vendorID'));
		}

		if ($validate->vendor->validate_shipfrom($po->vendorid, $values->text('shipfromID'))) {
			$po->setShipfromid($values->text('shipfromID'));
		}

		if ($validate->ar->validate_shipvia($values->text('shipvia'))) {
			$po->setShipvia($values->text('shipvia'));
		}

		if (array_key_exists($values->text('freightpaidby'), PurchaseOrder::FREIGHTPAIDBY_DESCRIPTIONS)) {
			$po->setFreightpaidby($values->text('freightpaidby'));
		}

		if (array_key_exists($values->text('fob'), PurchaseOrder::FOB_DESCRIPTIONS)) {
			$po->setFob($values->text('fob'));
		}

		if ($validate->ap->termscode($values->text('termscode'))) {
			$po->setTermscode($values->text('termscode'));
		}

		if ($validate->ar->shipvia($values->text('shipvia'))) {
			$po->setShipvia($values->text('shipvia'));
		}

		if ($validate->ap->countrycode($values->text('currency'))) {
			$po->setCurrency($values->text('currency'));
		}
	}

/* =============================================================
	Dplus Request Functions
============================================================= */
	/**
	 * Send PO Header Update Request
	 * @param  string $ponbr Purchase Order Number
	 * @return void
	 */
	public function request_po_edit($ponbr) {
		$config = $this->wire('config');
		$dplusdb = $this->wire('modules')->get('DplusOnlineDatabase')->db_name;
		$data = array("DBNAME=$dplusdb", 'EDITPURCHASEORDER', "PONBR=$ponbr");
		$requestor = $this->wire('modules')->get('DplusRequest');
		$requestor->write_dplusfile($data, session_id());
		$requestor->cgi_request($config->cgis['default'], $this->sessionID);
	}

	/**
	 * Send PO Add Item Request
	 * @param string $ponbr  Purchase Order Number
	 * @param string $itemID Item ID
	 * @param int    $qty    Qty
	 */
	public function request_add_item($ponbr, $itemID, int $qty = 1) {
		$config = $this->wire('config');
		$dplusdb = $this->wire('modules')->get('DplusOnlineDatabase')->db_name;
		$data = array("DBNAME=$dplusdb", 'ADDPURCHASEORDERLINE', "PONBR=$ponbr", "ITEMID=$itemID", "QTY=$qty");
		$requestor = $this->wire('modules')->get('DplusRequest');
		$requestor->write_dplusfile($data, session_id());
		$requestor->cgi_request($config->cgis['default'], $this->sessionID);
	}

	/**
	 * Send PO Update Item
	 * @param  string $ponbr   Purchase Order Number
	 * @param  int    $linenbr Line Number
	 * @return void
	 */
	public function request_update_item($ponbr, int $linenbr = 0) {
		$config = $this->wire('config');
		$dplusdb = $this->wire('modules')->get('DplusOnlineDatabase')->db_name;
		$data = array("DBNAME=$dplusdb", 'SAVEPURCHASEORDERLINE', "PONBR=$ponbr", "LINE=$linenbr");
		$requestor = $this->wire('modules')->get('DplusRequest');
		$requestor->write_dplusfile($data, session_id());
		$requestor->cgi_request($config->cgis['default'], $this->sessionID);
	}

	/**
	 * Send PO Update Header
	 * @param  string $ponbr   Purchase Order Number
	 * @return void
	 */
	public function request_update_header($ponbr) {
		$config = $this->wire('config');
		$dplusdb = $this->wire('modules')->get('DplusOnlineDatabase')->db_name;
		$data = array("DBNAME=$dplusdb", 'SAVEPURCHASEORDERHEADER', "PONBR=$ponbr");
		$requestor = $this->wire('modules')->get('DplusRequest');
		$requestor->write_dplusfile($data, session_id());
		$requestor->cgi_request($config->cgis['default'], $this->sessionID);
	}

	/**
	 * Sends HTTP GET request to send Dplus Item Search Request
	 * @param  string $q Query or Item ID
	 * @return void
	 */
	public function request_itemsearch($q) {
		$requestor = $this->wire('modules')->get('DplusRequest');
		$url = new Url($this->wire('pages')->get('template=redir,redir_file=ii')->url);
		$url->query->set('action', 'item-search');
		$url->query->set('q', $q);
		$url->query->set('custID', '');
		$url->query->set('sessionID', $this->sessionID);
		$requestor->self_request($url->getUrl());
	}

/* =============================================================
	URL Functions
============================================================= */
	/**
	 * Return Edit PO URL
	 * @param  string $ponbr Purchase Order Number
	 * @return string
	 */
	public function get_po_editURL($ponbr) {
		$url = new Url($this->wire('pages')->get('pw_template=purchase-order-edit')->url);
		$url->query->set('ponbr', $ponbr);
		return $url->getUrl();
	}

	/**
	 * Return Exit PO URL
	 * @param  string $ponbr Purchase Order Number
	 * @return string
	 */
	public function get_po_exitURL($ponbr) {
		$url = new Url($this->wire('pages')->get('pw_template=purchase-order-edit')->url);
		$url->query->set('action', 'exit');
		$url->query->set('ponbr', $ponbr);
		return $url->getUrl();
	}

	/**
	 * Return View PO URL
	 * @param  string $ponbr Purchase Order Number
	 * @return string
	 */
	public function get_po_viewURL($ponbr) {
		$url = new Url($this->wire('pages')->get('pw_template=purchase-order-view')->url);
		$url->query->set('ponbr', $ponbr);
		return $url->getUrl();
	}

/* =============================================================
	Supplemental Functions
============================================================= */
	/**
	 * Loads configs needed into $configs property
	 * @return void
	 */
	public function init_configs() {
		$this->configs = new WireData();
		$this->configs->po = $this->config_po();
	}

	/**
	 * Return Static / Readonly PO
	 * @param  string $ponbr PO Number
	 * @return PurchaseOrder
	 */
	public function get_purchaseorder($ponbr) {
		return PurchaseOrderQuery::create()->findOneByPonbr($ponbr);
	}

	/**
	 * Return if User has Purchase Order Editing Permission
	 * @param  User $user User
	 * @return bool
	 */
	public function user_has_permission(User $user) {
		return $user->has_function(self::PERMISSION_DPLUS);
	}

	/**
	 * Returns if Purchase Order can be Edited
	 * @param  string $ponbr Purchase Order Number
	 * @return bool
	 */
	public function is_po_editable($ponbr) {
		$q = PurchaseOrderQuery::create();
		$q->filterByPonbr($ponbr);
		$q->filterByStatus(PurchaseOrder::STATUS_CLOSED, Criteria::ALT_NOT_EQUAL);
		return boolval($q->count());
	}

	/**
	 * Returns if Purchase Order Exists
	 * @param  string $ponbr Purchase Order Number
	 * @return bool
	 */
	public function exists($ponbr) {
		$validator = $this->wire('modules')->get('ValidatePurchaseOrderNbr');
		return $validator->validate($ponbr);
	}

	/**
	 * Returns Details for JS
	 * @param  string $ponbr Purchase Order Number
	 * @return array
	 */
	public function get_details_array($ponbr) {
		$array = array();
		$items = $this->get_query_details($ponbr);

		foreach ($items as $item) {
			$array[$item->linenbr] = array(
				'linenbr'      => $item->linenbr,
				'itemid'       => $item->itemid,
				'description'  => $item->description,
				'vendoritemid' => $item->vendoritemid,
				'whseid'       => $item->whse,
				'specialorder' => $item->specialorder,
				'uom'          => $item->uom,
				'qty' => array(
					'ordered'  => number_format($item->qty_ordered, $this->decimal_places_qty()),
					'received' => $this->get_qty_received($ponbr, $item->linenbr),
					'invoiced' => $this->get_qty_invoiced($ponbr, $item->linenbr),
				),
				'cost'         => number_format($item->cost, $this->decimal_places_cost()),
				'cost_total'   => number_format($item->cost_total, $this->decimal_places_cost())
			);
		}
		return $array;
	}

	/**
	 * Return Purchase Order Item Qty Received
	 * @param  string $ponbr   Purchase Order Number
	 * @param  int    $linenbr Line Number
	 * @return float|int       Uses ConfigSo::decimal_places
	 */
	public function get_qty_received($ponbr, $linenbr) {
		$q = PurchaseOrderDetailReceivingQuery::create();
		$col = PurchaseOrderDetailReceiving::get_aliasproperty('qty_received');
		$q->withColumn("SUM($col)", 'qty');
		$q->select('qty');
		$q->filterByPonbr($ponbr);
		$q->filterByLinenbr($linenbr);
		return number_format($q->findOne(), $this->decimal_places_qty());
	}

	/**
	 * Return Purchase Order Item Qty Invoiced
	 * @param  string $ponbr   Purchase Order Number
	 * @param  int    $linenbr Line Number
	 * @return float|int       Uses ConfigSo::decimal_places
	 */
	public function get_qty_invoiced($ponbr, $linenbr) {
		$q = ApInvoiceDetailQuery::create();
		$col = ApInvoiceDetail::get_aliasproperty('qty_received');
		$q->withColumn("SUM($col)", 'qty');
		$q->select('qty');
		$q->filterByPonbr($ponbr);
		$q->filterByLinenbr($linenbr);
		return number_format($q->findOne(), $this->decimal_places_qty());
	}

	/**
	 * Return Warehouses
	 * @return Warehouses[]|ObjectCollection
	 */
	public function get_warehouses() {
		return WarehouseQuery::create()->find();
	}

	/**
	 * Return Vendor
	 * @param  string  $vendorID Vendor ID
	 * @return Vendor
	 */
	public function get_vendor($vendorID) {
		return VendorQuery::create()->findOneByVendorid($vendorID);
	}

	/**
	 * Return US States
	 * @return States[]|ObjectCollection
	 */
	public function get_states() {
		return StatesQuery::create()->select(['name', 'abbreviation'])->find();
	}

	/**
	 * Return the number of decimal places for qty values
	 * @return int
	 */
	public function decimal_places_qty() {
		return ConfigSalesOrderQuery::create()->findOne()->decimal_places_qty;
	}

	/**
	 * Return the number of decimal places for qty values
	 * @return int
	 */
	public function decimal_places_price_so() {
		return ConfigSalesOrderQuery::create()->findOne()->decimal_places_price;
	}

	/**
	 * Return the number of decimal places for cost values
	 * @return int
	 */
	public function decimal_places_cost() {
		return $this->configs->po->decimal_places_cost;
	}

	/**
	 * Return Shipvias
	 * @return Shipvia[]|ObjectCollection
	 */
	public function get_shipvias() {
		return ShipviaQuery::create()->find();
	}

	/**
	 * Return Accounts Payable Terms Codes
	 * @return ApTermsCode[]|ObjectCollection
	 */
	public function get_termscodes() {
		return ApTermsCodeQuery::create()->find();
	}

	/**
	 * Return termscode description
	 * @return string
	 */
	public function get_termscode($termscode) {
		return ApTermsCodeQuery::create()->findOneByCode($termscode)->description;
	}

	/**
	 * Return Description Label for Cancel Date
	 * @return string
	 */
	public function get_label_date_cancel() {
		return $this->config_po()->description_date_cancel();
	}

	/**
	 * Return Description Label for Acknowledged Date
	 * @return string
	 */
	public function get_label_date_acknowledged() {
		return $this->config_po()->description_date_acknowledged();
	}

	/**
	 * Return PO Config
	 * @return ConfigPo
	 */
	public function config_po() {
		return $this->wire('modules')->get('ConfigurePo')->config();
	}

	/**
	 * Return Country Codes
	 * @return CountryCodes[]|ObjectCollection
	 */
	public function get_country_codes() {
		return CountryCodesQuery::create()->find();
	}
/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public function init() {
		$this->sessionID = session_id();

		$this->addHook('Page(pw_template=purchase-order-edit)::ii_lookupURL', function($event) {
			$url = new Url($this->wire('pages')->get('pw_template=ii-item-lookup')->httpUrl);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page(pw_template=purchase-order-edit)::itm_jsonURL', function($event) {
			$url = new Url($this->wire('pages')->get('pw_template=itm-json')->httpUrl);
			$url->query->set('json', 'true');
			$event->return = $url->getUrl();
		});

		$this->addHook('Page(pw_template=purchase-order-edit)::vi_jsonURL', function($event) {
			$url = new Url($this->wire('pages')->get('pw_template=vi-json')->httpUrl);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page(pw_template=purchase-order-edit)::po_editURL', function($event) {
			$ponbr = $event->arguments(0);
			$event->return = $this->get_po_editURL($ponbr);
		});

		$this->addHook('Page(pw_template=purchase-order-edit)::po_exitURL', function($event) {
			$ponbr = $event->arguments(0);
			$event->return = $this->get_po_exitURL($ponbr);
		});

		$this->addHook('Page(pw_template=purchase-order-edit)::po_viewURL', function($event) {
			$ponbr = $event->arguments(0);
			$event->return = $this->get_po_viewURL($ponbr);
		});
	}

	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'PurchaseOrderEdit',
			'version' => 101,
			'summary' => 'Handles Purchase Order Editing',
			'singular' => true,
			'autoload' => true,
			'installs' => array()
		);
	}
}
