<?php namespace ProcessWire;

	class DplusRedirPages extends DplusPwPages implements Module {
		protected $fields = array(
			'redir_file' => array(
				'name'  => 'redir_file',
				'type'  => 'text',
				'label' => 'Redirect File Name'
			)
		);

		protected $templates = array(
			'redir' => array(
				'name'   => 'redir',
				'fields' => array('redir_file', 'summary'),
				'paginated' => false
			)
		);

		protected $pages = array(
			'user-redir' => array(
				'template'   => 'redir',
				'name'       => 'redir',
				'title'      => 'redir',
				'summary'    => 'User Dplus Redirects',
				'parent'     => '/user/',
				'redir_file' => 'user'
			),
			'page-redir' => array(
				'template'   => 'redir',
				'name'       => 'redir',
				'title'      => 'redir',
				'summary'    => 'Page Redirects',
				'parent'     => '/',
				'redir_file' => 'redirect'
			),
			'warehouse-redir' => array(
				'template'   => 'redir',
				'name'       => 'redir',
				'title'      => 'redir',
				'summary'    => 'Warehouse Redirects',
				'parent'     => '/',
				'redir_file' => 'warehouse'
			),
			'binr-redir' => array(
				'template'   => 'redir',
				'name'       => 'redir',
				'title'      => 'redir',
				'summary'    => 'Warehouse Redirects',
				'parent'     => '/',
				'redir_file' => 'binr'
			),
		);

		/* =============================================================
		ProcessWire Module Functions
	============================================================= */
		/**
		 * ProcessWire Module Info
		 *
		 * @return void
		 */
		public static function getModuleInfo() {
			return array(
				'title' => 'Dplus Create ProcesWire Redirect Pages',
				'version' => 101,
				'summary' => 'Dplus Create ProcesWire Redirect Pages',
				'singular' => true,
				'autoload' => true,
			);
		}
	}
