<?php namespace ProcessWire;

class WarehouseManagement extends WireData implements Module {

/* =============================================================
	ProcessWire Module Functions
============================================================= */

	public function update() {
		$modules = $this->wire('modules');
		$modules->refresh();
		$moduleinfo = self::getModuleInfo();

		foreach ($moduleinfo['installs'] as $sub) {
			$modules->install($sub);
		}
	}
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso Warehouse Management',
			'version' => 101,
			'summary' => 'Handles Loading Warehouse Management Functions',
			'singular' => true,
			'autoload' => false,
			'installs' => array(
				'Picking',
				'PickingInventoryManager',
				'PickingOrderItems',
				'PickingProvalley'
			)
		);
	}
}
