<?php namespace ProcessWire;

use Dplus\CodeValidators\Mar as MarValidator;

use CustomerShiptoQuery, CustomerShipto;
use CustomerQuery, Customer;
use WarehouseInventoryQuery, WarehouseInventory;

/**
 * LookupItemEntry
 *
 * Class for Looking up / Validating Items through ITM and different X-refs
 * for the purposes of Item Entry
 *
 * @property string $exists  Item Exists
 * @property string $itemID  Item ID associated with Item
 * @property string $request What was sent to find Item
 * @property string $source  itm|cxm
 */
class LookupItemEntry extends LookupItem implements Module {
	public function __construct() {
		parent::__construct();
		$this->message = '';
	}

	const LOOKUPS = array('cxm');

	/**
	 * Validates if string corresponds to an Item
	 * NOTE: Validates if Item is Active
	 * @param  WireInput $input
	 * @return void
	 */
	public function lookup_input(WireInput $input) {
		$itemID = $input->get->itemID ? $input->get->text('itemID') : $input->get->text('q');
		$itemID = strtoupper($itemID);
		$custID = $input->get->text('custID');
		$shiptoID = $input->get->text('shiptoID');

		$this->lookup_itm($itemID);

		if (!$this->exists) {
			$this->lookup_itm_short($itemID);
		}

		if (!$this->exists) {
			foreach (self::LOOKUPS as $lookup) {
				$function = "lookup_input_$lookup";
				$this->$function($itemID, $input);

				if ($this->exists) {
					break;
				}
			}
		}

		if ($this->exists) {
			$this->validate_active($custID, $shiptoID);
		}
		return $this->data;
	}

	/**
	 * Validates Item through CXM using provided Input Data
	 * @param  string    $itemID Item ID
	 * @param  WireInput $input  Input Data
	 * @return string
	 */
	public function lookup_input_cxm($itemID, WireInput $input) {
		$custID = $input->get->text('custID');
		$shiptoID = $input->get->text('shiptoID');
		$this->lookup_cxm($itemID, $custID);
	}

	/**
	 * Return Customer's Corresponding Warehouse ID
	 * @param  string $custID   Customer ID
	 * @param  string $shiptoID Customer Shipto ID
	 * @return string
	 */
	private function customer_whseid($custID, $shiptoID = '') {
		$validate = new MarValidator();

		if ($validate->custid($custID)) {
			if ($shiptoID) {
				$q = CustomerShiptoQuery::create();
				$shipto = $q->filterByCustid($custID)->filterByShiptoid($shiptoID)->findOne();
				return $shipto->warehouse;
			} else {
				$q = CustomerQuery::create();
				$customer = $q->filterByCustid($custID)->findOne();
				return $customer->warehouse;
			}
		}
		return false;
	}

	/**
	 * Return User's Warehouse ID
	 * @return string
	 */
	private function user_warehouse() {
		$user = $this->wire('user');
		return $user->whseid;
	}

	/**
	 * Validate If Item ID is active through custid, or User warehouse
	 * @param  string $custID   Customer ID
	 * @param  string $shiptoID Customer Shipto ID
	 * @return void
	 */
	private function validate_active($custID, $shiptoID = '') {
		$whseID = $this->user_warehouse();

		if ($custID) {
			$whseID = $this->customer_whseid($custID, $shiptoID) ;
		}

		$q = WarehouseInventoryQuery::create();
		$q->select(WarehouseInventory::get_aliasproperty('status'));
		$q->filterByWarehouseid($whseID);
		$q->filterByItemid($this->itemID);
		$status = $q->findOne();

		if (!$status == WarehouseInventory::STATUS_ACTIVE) {
			$this->exists = false;
			$this->message = 'Item is not active';
		}
	}


/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Item Entry Lookup Module',
			'version' => 101,
			'summary' => 'Handles Item Lookup for Item Entry',
			'singular' => true,
			'autoload' => true,
			'installs' => array(),
			'requires' => array('LookupItem')
		);
	}
}
