<?php namespace ProcessWire;
	require_once(__DIR__ . '/DplusoPages.module');

	use Purl\Url;

	class BookingsPages extends DplusoPages implements Module {
		protected $fields = array();

		protected $templates = array(
			'dplus-menu' => array(
				'name'   => 'dplus-menu',
				'fields' => array('dplus_function', 'summary'),
				'paginated' => false
			),
			'dplus-function' => array(
				'name'   => 'dplus-menu',
				'fields' => array('dplus_function', 'pw_template', 'summary'),
				'paginated' => true
			),
			'bookings' => array(
				'name'   => 'bookings',
				'fields' => array(),
			),
			'bookings-customer' => array(
				'name'   => 'bookings-customer',
				'fields' => array(),
			),
			'bookings-day' => array(
				'name'   => 'bookings-day',
				'fields' => array(),
			),
		);

		protected $pages = array(
			'bookings-menu' => array(
				'template'       => 'dplus-menu',
				'name'           => 'sobook',
				'title'          => 'Bookings',
				'summary'        => 'Bookings Menu',
				'parent'         => '/',
				'dplus_function' => ''
			),
			'bookings' => array(
				'template'       => 'dplus-function',
				'name'           => 'bookings',
				'title'          => 'Bookings',
				'summary'        => 'View Bookings',
				'parent'         => '/sobook/',
				'dplus_function' => '',
				'pw_template'    => 'bookings'
			),
			'bookings-day' => array(
				'template'       => 'dplus-function',
				'name'           => 'day',
				'title'          => 'Bookings Day',
				'summary'        => 'View Bookings for Day',
				'parent'         => '/sobook/bookings/',
				'dplus_function' => '',
				'pw_template'    => 'bookings-day'
			),
			'bookings-customer' => array(
				'template'       => 'dplus-function',
				'name'           => 'customer',
				'title'          => 'Customer Bookings',
				'summary'        => 'View Customer Bookings',
				'parent'         => '/sobook/bookings/',
				'dplus_function' => '',
				'pw_template'    => 'bookings-customer'
			),
		);


		public function init_bookingspage() {
			$this->addHook('Page::get_bookingsURL', function($event) {
				$page = $event->object;

				if ($page->pw_template == 'bookings-customer') {
					$event->return = $this->get_bookings_customerURL($page->custID, $page->shiptoID) ;
				} else {
					$event->return = $this->get_bookingsURL();
				}

			});

			$this->addHook('Page::get_bookings_dayURL', function($event) {
				$date = $event->arguments(0);
				$event->return = $this->get_bookings_dayURL($date);
			});

			$this->addHook('Page::get_bookings_day_orderURL', function($event) {
				$date = $event->arguments(0);
				$ordn = $event->arguments(1);
				$event->return = $this->get_bookings_day_orderURL($date, $ordn);
			});

			$this->addHook('Page::get_bookings_customerURL', function($event) {
				$custID   = $event->arguments(0);
				$shiptoID = $event->arguments(1);
				$event->return = $this->get_bookings_customerURL($custID, $shiptoID);
			});

			$this->addHook('Page::get_customerURL', function($event) {
				$custID   = $event->arguments(0);
				$event->return = $this->wire('modules')->get('MciPages')->get_ci_customerURL($custID);
			});

			$this->addHook('Page::get_customershiptoURL', function($event) {
				$custID   = $event->arguments(0);
				$shiptoID = $event->arguments(1);
				$event->return = $this->wire('modules')->get('MciPages')->get_ci_customershiptoURL($custID, $shiptoID);
			});
		}

		public function get_bookingsURL() {
			 return $this->wire('pages')->get('pw_template=bookings')->url;
		}

		public function get_bookings_dayURL($date) {
			$url = new Url($this->wire('pages')->get('pw_template=bookings-day')->url);
			$url->query->set('date', $date);
			return $url->getUrl();
		}

		public function get_bookings_day_orderURL($date, $ordn) {
			$url = new Url($this->wire('pages')->get('pw_template=bookings-day')->url);
			$url->query->set('date', $date);
			$url->query->set('ordn', $ordn);
			return $url->getUrl();
		}

		public function get_bookings_customerURL($custID, $shiptoID = '') {
			$url = new Url($this->wire('pages')->get('pw_template=bookings-customer')->url);
			$url->query->set('custID', $custID);
			$url->query->set('shiptoID', $shiptoID);
			return $url->getUrl();
		}

		public static function getModuleInfo() {
			return array(
				'title' => 'Dplus Online Bookings Pages',
				'version' => 101,
				'summary' => 'Installs and creates Dplus Online Bookings Pages',
				'singular' => true,
				'autoload' => true,
			);
		}
	}
