<?php namespace ProcessWire;
	require_once(__DIR__ . '/DplusoPages.module');

	use Purl\Url;

	class DplusoPagesCustomer extends DplusoPages implements Module {

		protected $fields = array();
		protected $templates = array(
			'dplus-menu' => array(
				'name'   => 'dplus-menu',
				'fields' => array('dplus_function', 'summary'),
				'paginated' => false
			),
			'dplus-function' => array(
				'name'   => 'dplus-menu',
				'fields' => array('dplus_function', 'pw_template', 'summary'),
				'paginated' => true
			),
			'ci-customer' => array(
				'name'   => 'ci-customer',
				'fields' => array(),
			),
			'ci-phonebook' => array(
				'name'   => 'ci-phonebook',
				'fields' => array(),
			),
		);

		protected $pages = array(
			'customer-menu' => array(
				'template'       => 'dplus-menu',
				'name'           => 'mci',
				'title'          => 'Customers',
				'summary'        => 'Customer Menu',
				'parent'         => '/',
				'dplus_function' => ''
			),
			'ci' => array(
				'template'       => 'dplus-function',
				'name'           => 'ci',
				'title'          => 'Customer Information',
				'summary'        => 'View Customer Information',
				'parent'         => '/mci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-customer'
			),
			'ci-index' => array(
				'template'       => 'dplus-function',
				'name'           => 'phonebook',
				'title'          => 'Customer Phonebook',
				'summary'        => 'View Customer Phonebook',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-phonebook'
			),
			'ci-shiptos' => array(
				'template'       => 'dplus-function',
				'name'           => 'shiptos',
				'title'          => 'Customer Ship-tos',
				'summary'        => 'View Customer Ship-tos',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-shiptos'
			),
			'ci-contacts' => array(
				'template'       => 'dplus-function',
				'name'           => 'contacts',
				'title'          => 'Customer Contacts',
				'summary'        => 'View Customer Contacts',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-contacts'
			),
			'ci-pricing' => array(
				'template'       => 'dplus-function',
				'name'           => 'pricing',
				'title'          => 'Customer Pricing',
				'summary'        => 'View Customer Pricing',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-pricing'
			),
			'ci-sales-orders' => array(
				'template'       => 'dplus-function',
				'name'           => 'sales-orders',
				'title'          => 'Customer Sales Orders',
				'summary'        => 'View Customer Sales Orders',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-sales-orders'
			),
			'ci-sales-history' => array(
				'template'       => 'dplus-function',
				'name'           => 'sales-history',
				'title'          => 'Customer Sales History',
				'summary'        => 'View Customer Sales History',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-sales-history'
			),
			'ci-customer-po' => array(
				'template'       => 'dplus-function',
				'name'           => 'customer-po',
				'title'          => 'Customer PO',
				'summary'        => 'View Customer PO',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-customer-po'
			),
			'ci-quotes' => array(
				'template'       => 'dplus-function',
				'name'           => 'quotes',
				'title'          => 'Customer Quotes',
				'summary'        => 'View Customer Quotes',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-quotes'
			),
			'ci-open-invoices' => array(
				'template'       => 'dplus-function',
				'name'           => 'open-invoices',
				'title'          => 'Customer Open Invoices',
				'summary'        => 'View Customer Open Invoices',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-open-invoices'
			),
			'ci-payments' => array(
				'template'       => 'dplus-function',
				'name'           => 'payments',
				'title'          => 'Customer Payments',
				'summary'        => 'View Customer Payments',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-payments'
			),
			'ci-credit' => array(
				'template'       => 'dplus-function',
				'name'           => 'credit',
				'title'          => 'Customer Credit',
				'summary'        => 'View Customer Credit',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-credit'
			),
			'ci-standing-orders' => array(
				'template'       => 'dplus-function',
				'name'           => 'standing-orders',
				'title'          => 'Customer Standing Orders',
				'summary'        => 'View Customer Standing Orders',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-standing-orders'
			),
			'ci-stock' => array(
				'template'       => 'dplus-function',
				'name'           => 'stock',
				'title'          => 'Customer Stock',
				'summary'        => 'View Customer Stock',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-stock'
			),
			'ci-notes' => array(
				'template'       => 'dplus-function',
				'name'           => 'notes',
				'title'          => 'Customer Notes',
				'summary'        => 'View Customer Notes',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-notes'
			),
			'ci-documents' => array(
				'template'       => 'dplus-function',
				'name'           => 'documents',
				'title'          => 'Customer Documents',
				'summary'        => 'View Customer Documents',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-documents'
			),
		);

		public function init_customer_hooks() {
			/**
			 * Adds hook for getting Sales Order List URL
			 */
			$this->addHook('Page::cust_salesordersURL', function($event) {
				$custID = $event->arguments(0);
				$url = new Url($this->wire('pages')->get('pw_template=sales-orders-customer')->url);
				$url->query->set('custID', $custID);
				$event->return = $url->getUrl();
			});

			/**
			 * Adds hook for getting Sales History List URL
			 */
			$this->addHook('Page::cust_saleshistoryURL', function($event) {
				$custID = $event->arguments(0);
				$url = new Url($this->wire('pages')->get('pw_template=sales-history-orders-customer')->url);
				$url->query->set('custID', $custID);
				$event->return = $url->getUrl();
			});
		}

		public static function getModuleInfo() {
			return array(
				'title' => 'Dplus Online Customer Pages',
				'version' => 101,
				'summary' => 'Installs and creates Dplus Online Customer Pages',
				'singular' => true,
				'autoload' => true,
			);
		}
	}
