<?php namespace ProcessWire;
	require_once(__DIR__ . '/DplusoPages.module');

	use Purl\Url;

	class MciPages extends DplusoPages implements Module {

		protected $fields = array(
			'jsoncode' => array(
				'name'  => 'jsoncode',
				'type'  => 'text',
				'label' => 'JSON Datafile Code'
			),
			'is_formattable' => array(
				'name'        => 'is_formattable',
				'type'        => 'checkbox',  // TRUE OR FALSE
				'label'       => 'Is screen formattable?',
				'description' => 'Allow Screen Formatter to be used',
				'notes'       => ""
			),
		);
		
		protected $templates = array(
			'dplus-menu' => array(
				'name'   => 'dplus-menu',
				'fields' => array('dplus_function', 'summary'),
				'paginated' => false
			),
			'dplus-function' => array(
				'name'   => 'dplus-menu',
				'fields' => array('dplus_function', 'pw_template', 'summary'),
				'paginated' => true
			),
			'ci-function' => array(
				'name'   => 'dplus-menu',
				'fields' => array('title', 'dplus_function', 'pw_template', 'jsoncode', 'is_formattable', 'summary'),
				'paginated' => true
			),
			'ci-customer' => array(
				'name'   => 'ci-customer',
				'fields' => array(),
			),
			'ci-pricing' => array(
				'name'   => 'ci-pricing',
				'fields' => array(),
			),
			'ci-shiptos' => array(
				'name'   => 'ci-shiptos',
				'fields' => array(),
			),
			'ci-contacts' => array(
				'name'   => 'ci-contacts',
				'fields' => array(),
			),
			'ci-sales-orders' => array(
				'name'   => 'ci-sales-orders',
				'fields' => array(),
			),
			'ci-sales-history' => array(
				'name'   => 'ci-sales-history',
				'fields' => array(),
			),
			'ci-purchase-orders' => array(
				'name'   => 'ci-purchase-orders',
				'fields' => array(),
			),
			'ci-quotes' => array(
				'name'   => 'ci-quotes',
				'fields' => array(),
			),
			'ci-open-invoices' => array(
				'name'   => 'ci-open-invoices',
				'fields' => array(),
			),
			'ci-payments' => array(
				'name'   => 'ci-payments',
				'fields' => array(),
			),
			'ci-credit' => array(
				'name'   => 'ci-credit',
				'fields' => array(),
			),
			'ci-standing-orders' => array(
				'name'   => 'ci-standing-orders',
				'fields' => array(),
			),
			'ci-stock' => array(
				'name'   => 'ci-stock',
				'fields' => array(),
			),
			'ci-notes' => array(
				'name'   => 'ci-notes',
				'fields' => array(),
			),
			'ci-documents' => array(
				'name'   => 'ci-documents',
				'fields' => array(),
			),
			'ci-phonebook' => array(
				'name'   => 'ci-phonebook',
				'fields' => array(),
			)
		);

		protected $pages = array(
			'customer-menu' => array(
				'template'       => 'dplus-menu',
				'name'           => 'mci',
				'title'          => 'Customers',
				'summary'        => 'Customer Menu',
				'parent'         => '/',
				'dplus_function' => ''
			),
			'ci' => array(
				'template'       => 'dplus-function',
				'name'           => 'ci',
				'title'          => 'Customer Information',
				'summary'        => 'View Customer Information',
				'parent'         => '/mci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-customer'
			),
			'ci-index' => array(
				'template'       => 'dplus-function',
				'name'           => 'phonebook',
				'title'          => 'Phonebook',
				'summary'        => 'View Customer Phonebook',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-phonebook'
			),
			'ci-shiptos' => array(
				'template'       => 'dplus-function',
				'name'           => 'shiptos',
				'title'          => 'Ship-tos',
				'summary'        => 'View Customer Ship-tos',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-shiptos'
			),
			'ci-contacts' => array(
				'template'       => 'ci-function',
				'name'           => 'contacts',
				'title'          => 'Contacts',
				'summary'        => 'View Customer Contacts',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-contacts',
				'jsoncode'       => 'ci-contacts'
			),
			'ci-pricing' => array(
				'template'       => 'dplus-function',
				'name'           => 'pricing',
				'title'          => 'Pricing',
				'summary'        => 'View Customer Pricing',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-pricing'
			),
			'ci-sales-orders' => array(
				'template'       => 'dplus-function',
				'name'           => 'sales-orders',
				'title'          => 'Sales Orders',
				'summary'        => 'View Customer Sales Orders',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-sales-orders'
			),
			'ci-sales-history' => array(
				'template'       => 'dplus-function',
				'name'           => 'sales-history',
				'title'          => 'Sales History',
				'summary'        => 'View Customer Sales History',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-sales-history'
			),
			'ci-customer-po' => array(
				'template'       => 'dplus-function',
				'name'           => 'customer-po',
				'title'          => 'Purchase Orders',
				'summary'        => 'View Customer PO',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-customer-po'
			),
			'ci-quotes' => array(
				'template'       => 'dplus-function',
				'name'           => 'quotes',
				'title'          => 'Quotes',
				'summary'        => 'View Customer Quotes',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-quotes'
			),
			'ci-open-invoices' => array(
				'template'       => 'dplus-function',
				'name'           => 'open-invoices',
				'title'          => 'Open Invoices',
				'summary'        => 'View Customer Open Invoices',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-open-invoices'
			),
			'ci-payments' => array(
				'template'       => 'dplus-function',
				'name'           => 'payments',
				'title'          => 'Payments',
				'summary'        => 'View Customer Payments',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-payments'
			),
			'ci-credit' => array(
				'template'       => 'dplus-function',
				'name'           => 'credit',
				'title'          => 'Credit',
				'summary'        => 'View Customer Credit',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-credit'
			),
			'ci-standing-orders' => array(
				'template'       => 'dplus-function',
				'name'           => 'standing-orders',
				'title'          => 'Standing Orders',
				'summary'        => 'View Customer Standing Orders',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-standing-orders'
			),
			'ci-stock' => array(
				'template'       => 'dplus-function',
				'name'           => 'stock',
				'title'          => 'Stock',
				'summary'        => 'View Customer Stock',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-stock'
			),
			'ci-notes' => array(
				'template'       => 'dplus-function',
				'name'           => 'notes',
				'title'          => 'Notes',
				'summary'        => 'View Customer Notes',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-notes'
			),
			'ci-documents' => array(
				'template'       => 'dplus-function',
				'name'           => 'documents',
				'title'          => 'Documents',
				'summary'        => 'View Customer Documents',
				'parent'         => '/mci/ci/',
				'dplus_function' => '',
				'pw_template'    => 'ci-documents'
			),
		);

		public function init_cipage() {
			$this->addHook('Page::get_redirURL', function($event) {
				$p = $event->object;
				$event->return = $p->parent('template=dplus-menu')->child('template=redir')->url;
			});

			$this->addHook('Page::get_customerURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-customer');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customerpricingURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-pricing');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customershiptosURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-shiptos');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customercontactsURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-contacts');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customersalesordersURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-sales-orders');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customersaleshistoryURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-sales-history');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customerpurchaseordersURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-purchase-orders');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customerquotesURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-quotes');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customeropeninvoicesURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-open-invoices');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customerpaymentsURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-payments');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customercreditURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-credit');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customerstandingordersURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-standing-orders');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customerstockURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-stock');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customernotesURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-notes');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customerdocumentsURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-documents');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_customerphonebookURL', function($event) {
				$p = $event->object;
				$custID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ci-phonebook');
				$url->query->set('custID', $custID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});
		}

		public static function getModuleInfo() {
			return array(
				'title' => 'Dplus Online Customer Pages',
				'version' => 101,
				'summary' => 'Installs and creates Dplus Online Customer Pages',
				'singular' => true,
				'autoload' => true,
			);
		}
	}
