<?php namespace ProcessWire;
	require_once(__DIR__ . '/DplusoPages.module');

	use Purl\Url;

	class MiiPages extends DplusoPages implements Module {
		const REQUIREMENTS_OPTIONS = array(
			"REQ" => "requirements",
			"AVL" => 'available'
		);

		const TEMPLATES_JSONFILES = array(
			'ii-stock'        => 'ii-stock_whse',
			'ii-requirements' => 'ii-requirements',
			'ii-pricing'      => 'ii-pricing'
		);

		protected $fields = array(
			'jsoncode' => array(
				'name'  => 'jsoncode',
				'type'  => 'text',
				'label' => 'JSON Datafile Code'
			),
			'is_formattable' => array(
				'name'        => 'is_formattable',
				'type'        => 'checkbox',  // TRUE OR FALSE
				'label'       => 'Is screen formattable?',
				'description' => 'Allow Screen Formatter to be used',
				'notes'       => ""
			),
		);

		protected $templates = array(
			'dplus-menu' => array(
				'name'   => 'dplus-menu',
				'fields' => array('dplus_function', 'summary'),
				'paginated' => false
			),
			'dplus-function' => array(
				'name'   => 'dplus-menu',
				'fields' => array('dplus_function', 'pw_template', 'summary'),
				'paginated' => true
			),
			'ii-function' => array(
				'name'   => 'dplus-menu',
				'fields' => array('title', 'dplus_function', 'pw_template', 'jsoncode', 'is_formattable', 'summary'),
				'paginated' => true
			),
			'ii-item' => array(
				'name'   => 'ii-item',
				'fields' => array(),
			),
			'ii-requirements' => array(
				'name'   => 'ii-requirements',
				'fields' => array(),
			),
			'ii-pricing' => array(
				'name'   => 'ii-pricing',
				'fields' => array(),
			),
		);

		protected $pages = array(
			'ii-menu' => array(
				'template'       => 'dplus-menu',
				'name'           => 'mii',
				'title'          => 'Item Information',
				'summary'        => 'Item Information Menu',
				'parent'         => '/',
				'dplus_function' => ''
			),
			'ii' => array(
				'template'       => 'dplus-function',
				'name'           => 'ii',
				'title'          => 'Item Information',
				'summary'        => 'View Item Information',
				'parent'         => '/mii/',
				'dplus_function' => '',
				'pw_template'    => 'ii-item'
			),
			'ii-stock' => array(
				'template'       => 'ii-function',
				'name'           => 'stock',
				'title'          => 'Stock',
				'summary'        => 'View Item Stock',
				'parent'         => '/mii/ii/',
				'dplus_function' => '',
				'pw_template'    => 'ii-stock',
				'jsoncode'       => 'ii-stock_whse',
				'has_print'      => true
			),
			'ii-requirements' => array(
				'template'       => 'ii-function',
				'name'           => 'requirements',
				'title'          => 'Requirements',
				'summary'        => 'View Item Requirements',
				'parent'         => '/mii/ii/',
				'dplus_function' => '',
				'pw_template'    => 'ii-requirements',
				'jsoncode'       => 'ii-requirements',
				'has_print'      => true
			),
			'ii-pricing' => array(
				'template'       => 'ii-function',
				'name'           => 'pricing',
				'title'          => 'Pricing',
				'summary'        => 'View Item Pricing',
				'parent'         => '/mii/ii/',
				'dplus_function' => '',
				'pw_template'    => 'ii-pricing',
				'has_print'      => true,
				'jsoncode'       => 'ii-pricing'
			)
		);

		public function init_iipage() {
			$this->addHook('Page::get_itemURL', function($event) {
				$p = $event->object;
				$itemID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ii-item');
				$url->query->set('itemID', $itemID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_itemstockURL', function($event) {
				$p = $event->object;
				$itemID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ii-stock');
				$url->query->set('itemID', $itemID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_itemrequirementsURL', function($event) {
				$p = $event->object;
				$itemID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ii-requirements');
				$url->query->set('itemID', $itemID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});

			$this->addHook('Page::get_itempricingURL', function($event) {
				$p = $event->object;
				$itemID = $event->arguments(0);
				$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
				$url->query->set('action','ii-pricing');
				$url->query->set('itemID', $itemID);
				$url->query->set('page', $p->fullURL->getUrl());
				$event->return = $url->getUrl();
			});
		}

		public static function getModuleInfo() {
			return array(
				'title' => 'Dplus Online Item Information Pages',
				'version' => 101,
				'summary' => 'Installs and creates Dplus Online Item Information  Pages',
				'singular' => true,
				'autoload' => true,
			);
		}

		public function get_requirementsoptions() {
			return self::REQUIREMENTS_OPTIONS;
		}

		public function get_jsondatafilename($template) {
			return self::TEMPLATES_JSONFILES[$template];
		}
	}
