<?php namespace ProcessWire;

use CustomerQuery, Customer;
use ConfigCiQuery, ConfigCi;

use Propel\Runtime\ActiveQuery\Criteria;

class FilterCustomers extends WireData implements Module {
	public function __construct() {
		$this->query = CustomerQuery::create();
	}

	/**
	 * Returns Query
	 * @return CustomerQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * NOTE: Filters by Sales Rep if provided user is a Sales rep
	 *
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return self
	 */
	public function init_query(User $user) {
		$this->query = CustomerQuery::create();

		if ($user->is_salesrep()) {
			$this->query->filterByCustid($user->get_customers(), Criteria::IN);
		}
		$this->active();
		return $this;
	}

/* =============================================================
	Base Filter Functions
============================================================= */
	/**
	 * Filter for Active Customers Only
	 * @return self
	 */
	public function active() {
		$config = ConfigCiQuery::create()->findOne();

		if ($config->show_inactive != ConfigCi::BOOL_TRUE) {
			$this->query->filterByActive(Customer::STATUS_ACTIVE);
		}
		return $this;
	}

	/**
	 * Filter Query by Cust ID
	 * @param  string|array $custID Cust ID
	 * @return void
	 */
	public function custid($custID) {
		return $this->query->filterByCustid($custID);
	}

	/**
	 * Searches the Customer Table to find vendors that match the query provided
	 *
	 * @param  string $q Search Query
	 * @return void
	 */
	public function search($q) {
		$columns = [
			Customer::get_aliasproperty('custid'),
			Customer::get_aliasproperty('name'),
			Customer::get_aliasproperty('address1'),
			Customer::get_aliasproperty('address2'),
			Customer::get_aliasproperty('city'),
			Customer::get_aliasproperty('state'),
			Customer::get_aliasproperty('zip'),
		];
		$this->query->search_filter($columns, strtoupper($q));
	}

/* =============================================================
	Misc Query Functions
============================================================= */
	/**
	 * Adds the Sort By to the query
	 * @param  Page   $page
	 * @return void
	 */
	public function apply_sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;

			$tablecolumn = Customer::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		}
	}

	/**
	 * Return Position of Customer ID in Results
	 * @param  Vendor $custID  Customer ID
	 * @return int
	 */
	public function position($custID) {
		if (!$this->exists($custID)) {
			return 0;
		}
		$customers = $this->query->find();
		$customer = $this->get_customer($custID);
		return $customers->search($customer);
	}

	/**
	 * Return if Customer Exists
	 * @param  string $custID Customer ID
	 * @return bool
	 */
	public function exists($custID) {
		return boolval(CustomerQuery::create()->filterByCustid($custID)->count());
	}

	/**
	 * Return if Vendor Exists
	 * @param  string $custID Customer ID
	 * @return bool
	 */
	public function get_customer($custID) {
		return CustomerQuery::create()->findOneByCustid($custID);
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Filter Customer Module',
			'version' => 101,
			'summary' => 'Handles Customer Filtering',
			'singular' => true,
			'autoload' => true,
		);
	}
}
