<?php namespace ProcessWire;

use ItemMasterItemQuery, ItemMasterItem;

use Propel\Runtime\ActiveQuery\Criteria;

class FilterItemMaster extends WireData implements Module {
	/**
	 * Returns Query
	 * @return ItemMasterItemQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * NOTE: Filters by Sales Rep if provided user is a Sales rep
	 *
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return void
	 */
	public function init_query(User $user) {
		$this->query = ItemMasterItemQuery::create();
	}

	/**
	 * Searches the ItemMasterItem Table to find vendors that match the query provided
	 *
	 * @param  string $q Search Query
	 * @return void
	 */
	public function filter_search($q) {
		$col_itemid = ItemMasterItem::get_aliasproperty('itemid');
		$col_desc1  = ItemMasterItem::get_aliasproperty('description');
		$col_desc2  = ItemMasterItem::get_aliasproperty('description2');
		$columns = array($col_itemid, $col_desc1, $col_desc2);
		$this->query->search_filter($columns, strtoupper($q));
	}

	/**
	 * Adds the Sort By to the query
	 *
	 * @param  Page   $page
	 * @return void
	 */
	public function apply_sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;

			$tablecolumn = ItemMasterItem::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		}
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso Filter ItemMaster Module',
			'version' => 101,
			'summary' => 'Handles ItemMaster Item Filtering',
			'singular' => true,
			'autoload' => true,
		);
	}
}
