<?php namespace ProcessWire;

use DplusUserQuery, DplusUser;

use Propel\Runtime\ActiveQuery\Criteria;

class FilterDplusUsers extends WireData implements Module {
	/**
	 * Returns Query
	 * @return DplusUserQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * NOTE: Filters by Sales Rep if provided user is a Sales rep
	 *
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return void
	 */
	public function init_query(User $user) {
		$this->query = DplusUserQuery::create();
	}

	/**
	 * Searches the DplusUser Table to find vendors that match the query provided
	 * @param  string $q Search Query
	 * @return void
	 */
	public function filter_search($q) {
		$columns = [
			DplusUser::get_aliasproperty('loginid'),
			DplusUser::get_aliasproperty('name'),
			DplusUser::get_aliasproperty('whseid'),
			DplusUser::get_aliasproperty('group'),
			DplusUser::get_aliasproperty('role'),
			DplusUser::get_aliasproperty('email'),
		];
		$this->query->search_filter($columns, strtoupper($q));
	}

	/**
	 * Adds the Sort By to the query
	 * @param  Page   $page
	 * @return void
	 */
	public function apply_sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;

			$tablecolumn = DplusUser::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		}
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Filter DplusUser Module',
			'version' => 101,
			'summary' => 'Handles DplusUser Filtering',
			'singular' => true,
			'autoload' => true,
		);
	}
}
