<?php namespace ProcessWire;

use VendorQuery, Vendor;

use Propel\Runtime\ActiveQuery\Criteria;

class FilterVendors extends WireData implements Module {
	public function __construct() {
		$this->query = VendorQuery::create();
	}

	/**
	 * Returns Query
	 * @return VendorQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * NOTE: Filters by Sales Rep if provided user is a Sales rep
	 *
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return void
	 */
	public function init_query(User $user) {
		$this->query = VendorQuery::create();
	}

	/**
	 * Filter Query with Input Data
	 * @param  WireInput $input Input Data
	 * @return void
	 */
	public function filter_input(WireInput $input) {

	}

/* =============================================================
	Base Filter Functions
============================================================= */
	/**
	 * Searches the Vendor Table to find vendors that match the query provided
	 * @param  string $q Search Query
	 * @return void
	 */
	public function search($q) {
		$columns = [
			Vendor::get_aliasproperty('vendorid'),
			Vendor::get_aliasproperty('name'),
			Vendor::get_aliasproperty('address'),
			Vendor::get_aliasproperty('address2'),
			Vendor::get_aliasproperty('city'),
			Vendor::get_aliasproperty('state'),
			Vendor::get_aliasproperty('zip'),
		];
		$this->query->search_filter($columns, strtoupper($q));
	}

	/**
	 * Filter Query by VendorID
	 * @param  array|string $vendorID  Vendor ID(s)
	 * @return void
	 */
	public function vendorid($vendorID) {
		$this->query->filterByVendorid($vendorID);
	}


/* =============================================================
	Misc Query Functions
============================================================= */
	/**
	 * Adds the Sort By to the query
	 * @param  Page   $page
	 * @return void
	 */
	public function apply_sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;

			$tablecolumn = Vendor::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		}
	}

	/**
	 * Return Position of Vendor in Results
	 * @param  Vendor $vendor Vendor
	 * @return int
	 */
	public function position($vendorID) {
		if (!$this->exists($vendorID)) {
			return 0;
		}
		$vendor = $this->get_vendor($vendorID);
		$vendors = $this->query->find();

		return $vendors->search($vendor);
	}

	/**
	 * Return Vendor
	 * @param  string $vendorID Vendor ID
	 * @return Vendor
	 */
	public function get_vendor($vendorID) {
		return VendorQuery::create()->findOneByVendorid($vendorID);
	}

	/**
	 * Return if Vendor exists
	 * @param  string $vendorID Vendor ID
	 * @return bool
	 */
	public function exists($vendorID) {
		return boolval(VendorQuery::create()->filterByVendorid($vendorID)->count());
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso Filter Vendors Module',
			'version' => 101,
			'summary' => 'Handles Vendor Filtering',
			'singular' => true,
			'autoload' => true,
		);
	}
}
