<?php namespace ProcessWire;

include_once(__DIR__.'/vendor/autoload.php');

class Filters extends WireData implements Module {

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');
		$modules->refresh();

		foreach ($info['installs'] as $module_name) {
			$modules->install($module_name);
		}
	}


/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Filters Module',
			'version' => 101,
			'summary' => 'Handles Loading of Filters Modules',
			'singular' => true,
			'autoload' => true,
			'installs' => array(
				'FilterSalesOrders',
				'FilterSalesHistory',
				'FilterQuotes',
				'FilterPurchaseOrder',
				'FilterApInvoices',
				'FilterBookings',
				'FilterVendors',
				'FilterItemXrefUpc',
				'FilterItemMaster',
				'FilterItemXrefVxm',
				'FilterQnotes',
				'FilterCountryCodes',
			)
		);
	}
}
