<?php namespace ProcessWire;

use Purl\Url;

use Dplus\CodeValidators\Mpo as MpoValidator;

use ConfigApQuery;
use PurchaseOrderNoteQuery, PurchaseOrderNote;


include_once(__DIR__.'/../QnotesResponse.php');

/**
 * QnotesPo
 *
 * Wrapper Class that houses the modules for PO NOTES CRUD methods
 */
class QnotesPo extends WireData implements Module {

/* =============================================================
	CRUD Processing Functions
============================================================= */
	/**
	 * Takes Input, Processes it, updates Purchase Order Notes in the Database
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function process_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$validate_ponbr = new MpoValidator();
		$ponbr = $values->text('ponbr');

		if ($validate_ponbr->po($ponbr)) {
			switch ($values->text('type')) {
				case 'PORD':
					$this->pord->process_input($input);
					break;
				case 'INTL':
					$this->intl->process_input($input);
					break;
				case 'IREV':
					$this->irev->process_input($input);
					break;
				default:
					$this->wire('session')->response_qnote = QnotesResponse::response_error($ponbr, 'Invalid Note Type');
					break;
			}
		} else {
			$this->wire('session')->response_qnote = QnotesResponse::response_error($ponbr, "Invalid PO # $ponbr");
		}
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Qnotes Purchase Order',
			'version' => 101,
			'summary' => 'Qnotes Purchase Order methods',
			'singular' => true,
			'autoload' => true,
			'requires' => array('Qnotes'),
			'installs' => array(
				'QnotesPoPord',
				'QnotesPoIntl',
			)
		);
	}

	public function init() {
		$this->pord = $this->wire('modules')->get('QnotesPoPord');
		$this->intl = $this->wire('modules')->get('QnotesPoIntl');
		$this->vend = $this->wire('modules')->get('QnotesVendorVend');
		$this->irev = $this->wire('modules')->get('QnotesItemRevision');

		$this->addHook('Page(pw_template=purchase-order-notes)::view_notesURL', function($event) {
			$p = $event->object;
			$ponbr = $event->arguments(0);
			$linenbr = $event->arguments(1);
			$url = new Url($this->wire('pages')->get('pw_template=purchase-order-notes')->url);
			$url->query->set('ponbr', $ponbr);
			$hash = $linenbr > 0 ? "#line-$linenbr" : '';
			$event->return = $url->getUrl()."$hash";
		});
	}

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');
		$modules->refresh();

		foreach ($info['installs'] as $module_name) {
			$modules->install($module_name);
		}
	}
}
