<?php namespace ProcessWire;

include_once(__DIR__ . "/FilterSalesTraits.php");

use SalesOrderQuery, SalesOrder;
use Propel\Runtime\ActiveQuery\Criteria;

class FilterSalesOrders extends WireData implements Module {
	use FilterSalesTraits;

	/**
	 * Query
	 * @var SalesOrderQuery
	 */
	protected $query;

	/**
	 * Returns Query
	 * @return SalesOrderQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * NOTE: Filters by Sales Rep if provided user is a Sales rep
	 *
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return void
	 */
	public function init_query(User $user) {
		$this->query = SalesOrderQuery::create();

		if ($user->is_salesrep()) {
			$this->query->filterbySalesPerson($user->roleid);
		}
	}

/* =============================================================
	Input Functions
============================================================= */
	/**
	 * Applies Filters to the Query
	 * NOTE:: Filters include Customer, ItemXrefCustomer #, ItemXrefCustomer Date, Review Date, Expire Date, ItemXrefCustomer Total, ItemXrefCustomer Status
	 *
	 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
	 * @return void
	 */
	public function filter_input(WireInput $input) {
		$this->custid_input($input);
		$this->shiptoid_input($input);

		if ($input->get->filter) {
			$this->ordernumber_input($input);
			$this->custpo_input($input);
			$this->orderdate_input($input);
			$this->requestdate_input($input);
			$this->ordertotal_input($input);
			$this->orderstatus_input($input);
		} else {
			$input->get->status = array();
		}
	}

	/**
	 * Filter the Query on the Order Status column
	 * @param  WireInput $input
	 * @return self
	 */
	public function orderstatus_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$sanitizer = new Sanitizer();

		if ($values->status) {
			$statuses = array();

			foreach ($values->status as $status) {
				$sanitized = $sanitizer->text($status);

				if (array_key_exists($sanitized, SalesOrder::STATUS_DESCRIPTIONS)) {
					$statuses[] = $sanitized;
				}
			}
			$this->orderstatus($statuses);
		} else {
			$input->get->status = array();
		}
		return $this;
	}

	/**
	 * Filter The Query on the Order Status Column
	 * @param  mixed $status Order Status
	 * @return self
	 */
	public function orderstatus($status) {
		if ($status) {
			$this->query->filterByStatus($status);
		}
		return $this;
	}

	/**
	 * Adds the Sort By to the query
	 *
	 * @param  Page   $page
	 * @return void
	 */
	public function apply_sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;
			$tablecolumn = SalesOrder::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		} else {
			$this->query->orderByDate_ordered('DESC');
		}
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso filter Sales Orders Module',
			'version' => 101,
			'summary' => 'Handles Sales Orders Filtering',
			'singular' => true,
			'autoload' => true,
		);
	}
}
