<?php namespace ProcessWire;

include_once(__DIR__ . "/FilterSalesTraits.php");

use SalesHistoryQuery, SalesHistory;
use Propel\Runtime\ActiveQuery\Criteria;

class FilterSalesHistory extends WireData implements Module {
	use FilterSalesTraits;

	/**
	 * Query
	 * @var SalesHistoryQuery
	 */
	protected $query;

	/**
	 * Returns Query
	 * @return SalesHistoryQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * NOTE: Filters by Sales Rep if provided user is a Sales rep
	 *
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return void
	 */
	public function init_query(User $user) {
		$this->query = SalesHistoryQuery::create();

		if ($user->is_salesrep()) {
			$this->query->filterbySalesPerson($user->roleid);
		}
	}

	/**
	 * Applies Filters to the Query
	 * NOTE:: Filters include Customer, Shipto, Order #, Customer PO, Order Date, Invoice Date, Order Total
	 *
	 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
	 * @return void
	 */
	public function filter_input(WireInput $input) {
		$this->custid_input($input);
		$this->shiptoid_input($input);

		if ($input->get->filter) {
			$this->ordernumber_input($input);
			$this->custpo_input($input);
			$this->orderdate_input($input);
			$this->invoicedate_input($input);
			$this->ordertotal_input($input);
		}
	}

	/**
	 * Filter the Query on the Inovice Date Column
	 *
	 * @param  WireInput $date Invoice Date
	 * @return self
	 */
	public function invoicedate_input(WireInput $input) {
		if ($input->get->text('invoicedate_from') || $input->get->text('invoicedate_through')) {
			$invoicedate_from = date("Ymd", strtotime($input->get->text('invoicedate_from')));

			if (empty($input->get->text('invoicedate_through'))) {
				$invoicedate_through = date('Ymd');
			} else {
				$invoicedate_through = date("Ymd", strtotime($input->get->text('invoicedate_through')));
			}

			if ($invoicedate_from) {
				$this->invoicedate($invoicedate_from, Criteria::GREATER_EQUAL);
			}

			if ($invoicedate_through) {
				$this->invoicedate($invoicedate_through, Criteria::LESS_EQUAL);
			}
		}
	}

	/**
	 * Filter the Query on the Inovice Date Column
	 *
	 * @param  string $date Invoice Date
	 * @return self
	 */
	public function invoicedate($date, $comparison = null) {
		if ($date) {
			$this->query->filterByInvoicedate($date, $comparison);
		}
		return $this;
	}

	/**
	 * Adds the Sort By to the query
	 *
	 * @param  Page   $page
	 * @return void
	 */
	public function apply_sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;
			$tablecolumn = SalesHistory::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		} else {
			$this->query->orderByDate_ordered('DESC');
		}
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso filter Sales History Module',
			'version' => 101,
			'summary' => 'Handles Sales History Filtering',
			'singular' => true,
			'autoload' => true,
		);
	}
}
