<?php namespace ProcessWire;
	use SalesOrderQuery, SalesOrder;

	class FilterSalesOrders extends WireData implements Module {
		protected $query;


		public function init() {

		}

		public function get_query() {
			return $this->query;
		}

		public function init_query(User $user) {
			$this->query = SalesOrderQuery::create();

			if ($user->is_salesrep()) {
				$this->query->filterbySalesPerson($user->roleid);
			}
		}

		public function filter_ordernumber(WireInput $input) {
			if ($input->get->text('ordernumber_from') && $input->get->text('ordernumber_through')) {
				$this->query->filterByOrdernumber(array($input->get->text('ordernumber_from'), $input->get->text('ordernumber_through')));
			} else if ($input->get->text('ordernumber_from')) {
				$this->query->filterByOrdernumber($input->get->text('ordernumber_from'));
			} else if ($input->get->text('ordernumber_through')) {
				$this->query->filterByOrdernumber($input->get->text('ordernumber_through'));
			}
		}

		public function filter_custpo(WireInput $input) {
			if ($input->get->text('custpo')) {
				$custpo = $input->get->text('custpo');
				$this->query->filterByCustpo("%$custpo%", Criteria::LIKE);
			}
		}

		public function filter_orderdate(WireInput $input) {
			if ($input->get->text('orderdate_from') || $input->get->text('orderdate_through')) {
				$orderdate_from = date("Ymd", strtotime($input->get->text('orderdate_from')));

				if (empty($input->get->text('orderdate_through'))) {
					$orderdate_through = date('Ymd');
				} else {
					$orderdate_through = date("Ymd", strtotime($input->get->text('orderdate_through')));
				}
				if ($orderdate_from && $orderdate_through) {
					$this->query->filterByOrderdate(array($orderdate_from, $orderdate_through));
				} else if ($orderdate_from) {
					$this->query->filterByOrderdate($orderdate_from);
				} else if ($orderdate_through) {
					$this->query->filterByOrderdate($orderdate_through);
				}
			}
		}

		public function filter_ordertotal(WireInput $input) {
			if ($input->get->text('order_total_from') && $input->get->text('order_total_through')) {
				$this->query->filterByOrdertotal(array($input->get->text('order_total_from'), $input->get->text('order_total_through')));
			} else if ($input->get->text('order_total_from')) {
				$this->query->filterByTotal_total($input->get->text('order_total_from'), Criteria::GREATER_EQUAL);
			} else if ($input->get->text('order_total_through')) {
				$this->query->filterByTotal_total($input->get->text('order_total_through'), Criteria::LESS_EQUAL);
			}
		}

		public function filter_orderstatus(WireInput $input) {
			if ($input->get->status) {
				$statuses = array();

				foreach ($input->get->status as $status) {
					$sanitized = $sanitizer->text($status);

					if (array_key_exists($sanitized, SalesOrder::$status_descriptions)) {
						$statuses[] = $sanitized;
					}
				}
				$this->query->filterByOrderstatus($statuses);
			} else {
				$input->get->status = array();
			}
		}

		public function filter_custid($input) {
			if ($input->get->custID) {
				if (is_array($input->get->custID)) {
					$filter = $input->get->array('custID');
				} else {
					$filter = $input->get->text('custID');
				}
				$this->query->filterByCustid($filter);
			}
		}

		public function filter_shiptoid($input) {
			if ($input->get->shiptoID && $input->get->custID) {
				if (is_array($input->get->shiptoID)) {
					$filter = $input->get->array('shiptoID');
				} else {
					$filter = $input->get->text('shiptoID');
				}
				$this->query->filterByShiptoid($filter);
			}
		}



		public function filter_query(WireInput $input) {
			$this->filter_custid($input);
			$this->filter_shiptoid($input);

			if ($input->get->filter) {
				$this->filter_ordernumber($input);
				$this->filter_custpo($input);
				$this->filter_orderdate($input);
				$this->filter_ordertotal($input);
				$this->filter_status($input);
			} else {
				$input->get->status = array();
			}
		}

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
		/**
		 * ProcessWire Module Info
		 *
		 * @return voID
		 */
		public static function getModuleInfo() {
			return array(
				'title' => 'Dpluso filter Sales Orders Module',
				'version' => 101,
				'summary' => 'Handles Sales Orders Filtering',
				'singular' => true,
				'autoload' => true,
			);
		}
	}
