<?php namespace ProcessWire;

use Purl\Url;
use QuoteQuery, Quote;
use QuothedQuery, Quothed;
use StatesQuery, States;
use ShipviaQuery, Shipvia;
use CustomerShiptoQuery, CustomerShipto;
use WarehouseQuery, Warehouse;

class QuoteEdit extends WireData implements Module {

	protected $qnbr;

	public function init() {
		/**
		 * Returns Sales Order Page URL
		 */
		$this->addHook('Page::unlock_quoteURL', function($event) {
			$qnbr = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('template=dplus-menu,name=mqo')->child('template=redir')->url);
			$url->query->set('action', 'unlock-quote');
			$url->query->set('qnbr', $qnbr);
			$event->return = $url->getUrl();
		});

		/**
		 * Adds self::is_user_editingorder() as User hook
		 * @uses self::is_user_editingorder()
		 */
		$this->addHook('Page::remove_itemURL', function($event) {
			$p = $event->object;
			$qnbr = $event->arguments(0);
			$linenbr = $event->arguments(1);
			$url = new Url($this->wire('pages')->get('template=dplus-menu,name=mqo')->child('template=redir')->url);
			$url->query->set('action', 'remove-line');
			$url->query->set('qnbr', $qnbr);
			$url->query->set('linenbr', $linenbr);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page(pw_template=quote-edit)::get_itm_lookupURL', function($event) {
			$url = new Url($this->wire('pages')->get('pw_template=itm-json')->httpUrl);
			$url->query->set('json', 'true');
			$event->return = $url->getUrl();
		});

		$this->addHook('Page(pw_template=quote-edit)::get_ii_lookupURL', function($event) {
			$url = new Url($this->wire('pages')->get('pw_template=ii-item-lookup')->httpUrl);
			$event->return = $url->getUrl();
		});
	}

	/**
	 * Returns if Quote Number has been defined
	 * @return bool
	 */
	public function has_qnbr() {
		return boolval($this->qnbr);
	}

	/**
	 * Returns Static Quote
	 *
	 * @return Quote
	 */
	public function get_quote_static() {
		return QuoteQuery::create()->filterByQuoteid($this->qnbr)->findOne();
	}

	/**
	 * Returns Editable Quote
	 * @return Quothed
	 */
	public function get_quote_edit() {
		return QuothedQuery::create()->findOneBySessionidQuote(session_id(), $this->qnbr);
	}

	/**
	 * Sets Quote Number
	 *
	 * @return string
	 */
	public function set_qnbr($qnbr) {
		$this->qnbr = $qnbr;
	}

	/**
	 * Return US States
	 * @return States|ObjectCollection
	 */
	public function get_states() {
		return StatesQuery::create()->select(['name', 'abbreviation'])->find();
	}

	/**
	 * Return Shipvias
	 * @return Shipvia[]|ObjectCollection
	 */
	public function get_shipvias() {
		return ShipviaQuery::create()->find();
	}

	/**
	 * Return Warehouses
	 * @return Warehouse[]|ObjectCollection
	 */
	public function get_warehouses() {
		return WarehouseQuery::create()->find();
	}

	/**
	 * Gets the Shipto address in an array format to be easily converted to JSON
	 * NOTE: used for JS
	 * @return array
	 */
	public function get_shiptos_json_array() {
		$custID = $this->get_custid();
		$columns = array('id', 'name', 'address', 'address2', 'city', 'state', 'zip');

		$query = CustomerShiptoQuery::create();

		foreach ($columns as $column) {
			$query->addAsColumn($column, CustomerShipto::get_aliasproperty($column));
		}
		$query->select($columns);
		$query->filterByCustid($custID);
		$shiptos = $query->find();
		return $shiptos->toArray('id');
	}

	/**
	 * Return Customer ID from Quote
	 * @return string Customer ID
	 */
	public function get_custid() {
		return  QuoteQuery::create()->select(Quote::get_aliasproperty('custid'))->findOneByQuotenumber($this->qnbr);
	}

	/**
	 * Sends HTTP GET request to send Dplus Item Search Request
	 * @param  string $q Query or Item ID
	 * @return void
	 */
	public function request_itemsearch($q) {
		$http = new WireHttp();
		$url = new Url('127.0.0.1');
		$url->path = $this->wire('pages')->get('template=redir,redir_file=ii')->url;
		$url->query->set('action', 'item-search');
		$url->query->set('q', $q);
		$url->query->set('custID', $this->get_custid());
		$url->query->set('sessionID', session_id());
		$http->get($url->getUrl());
	}


/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso Quote Edit Module',
			'version' => 101,
			'summary' => 'Handles Dpluso Quote Edit',
			'singular' => true,
			'autoload' => true,
		);
	}
}
