<?php namespace ProcessWire;

class WhseLabelPrinter extends WireData implements Module {

	public function init() {
		$this->sessionID = session_id();
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public function update() {
		$modules = $this->wire('modules');
		$modules->refresh();
		$moduleinfo = self::getModuleInfo();

		foreach ($moduleinfo['installs'] as $sub) {
			$modules->install($sub);
		}
	}

	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso Warehouse Label Printing',
			'version' => 101,
			'summary' => 'Handles Default Warehouse Label Printing',
			'singular' => true,
			'autoload' => false,
			'installs' => array(
				'WhseLabelPrinterProvalley',
			)
		);
	}
}
