<?php namespace ProcessWire;

include_once(__DIR__.'../CodeTablesResponse.php');

use Purl\Url;
use Propel\Runtime\ActiveQuery\Criteria;

use TariffCodeQuery, TariffCode;
use TariffCodeCountryQuery, TariffCodeCountry;
use ConfigInQuery, ConfigIn;
use ConfigSalesOrderQuery, ConfigSalesOrder;

/**
 * Module that handles the editing of the CCM codetable
 */
class CodeTablesTarm extends WireData implements Module {
	const MODEL              = 'TariffCode';
	const MODEL_KEY          = 'id';
	const DESCRIPTION        = 'Tariff Class';
	const DESCRIPTION_RECORD = 'Tariff Class';
	const MODEL_TABLE = 'inv_tari_code';

	public function __construct() {
		$this->description = self::DESCRIPTION;
	}

	/**
	 * Return the Code records from Database
	 * @param  string $table Table Code
	 * @return ObjectCollection
	 */
	public function get_codes() {
		$q = $this->get_query();
		return $q->find();
	}

	/**
	 * Return the Code records from Database filtered by ProductLne ID
	 * @param  string $productlne ProductLneID
	 * @return ObjectCollection
	 */
	public function get_code($code) {
		$q = $this->get_query();
		return $q->findOneById($code);
	}

	/**
	 * Returns if Codes Exists
	 * @param  string $productlne ProductLneID
	 * @return bool
	 */
	public function code_exists($code) {
		$q = $this->get_query();
		return boolval($q->filterById($code)->count());
	}

	/**
	 * Returns the associated ModelQuery class for table code
	 * @param  string $table Table Code
	 * @return mixed
	 */
	public function get_query() {
		return TariffCodeQuery::create();
	}

	/**
	 * Takes Input, validates it's for one of the code tables
	 * Processes it, and if updated sends request to dplus
	 *
	 * NOTE: If an existing code is more than TariffCode::MAX_LENGTH_CODE, we will allow editing
	 * but we won't allow creation of a code with more than allowed characters we will trim it.
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function process_input(WireInput $input) {
		$countries_updated = false;
		$rm = strtolower($input->requestMethod());
		$table = $input->$rm->text('table');
		$code  = $input->$rm->text('code');

		$q = $this->get_query();
		$q->filterByCode($code);

		if ($q->count()) {
			$record = $q->findOne();
		} else {
			$code  = $input->$rm->text('code', array('maxLength' => TariffCode::MAX_LENGTH_CODE));
			$record = new TariffCode();
			$record->setCode($code);
		}

		if ($input->$rm->text('action') == 'remove-code') {
			$record->delete();
		} else {
			$number = $input->$rm->text('number');
			$description = $input->$rm->text('description');
			$duty_rate = $input->$rm->text('duty_rate');
			$countries = $input->$rm->array('country');

			$record->setNumber($number);
			$record->setDescription($description);
			$record->setDuty_rate($duty_rate);
			$record->setDate(date('Ymd'));
			$record->setTime(date('His'));
			$record->setDummy('P');

			$countries_updated = $this->update_tariff_countries($code, $countries);
		}

		$response = $this->save_and_process_response($table, $code, $record);

		if ($response->has_error() && $countries_updated) {
			$response->set_success(true);
		}

		if ($response->has_success()) {
			$this->update_dplus_cobol($table, $code, $countries_updated);
		}

		$this->wire('session')->response_codetable = $response;
	}

	/**
	 * Returns CodeTablesResponse based on the outcome of the database save
	 *
	 * @param  string $table  Table Code
	 * @param  string $code   Code being added
	 * @param  bool   $is_new Was the Record in the database before Save?
	 * @param  bool   $saved  Was the Record Saved?
	 * @return CodeTablesResponse
	 */

	protected function save_and_process_response($table, $code, TariffCode $record) {
		$is_new = $record->isDeleted() ? false : $record->isNew();
		$saved  = $record->isDeleted() ? $record->isDeleted() : $record->save();

		$response = new CodeTablesResponse();
		$response->set_key($code);
		$message = self::DESCRIPTION_RECORD . " ($code) was ";

		if ($saved) {
			$response->set_success(true);
		} else {
			$response->set_error(true);
			$message .= "not ";
		}

		if ($is_new) {
			$message .= 'added';
			$response->set_action(CodeTablesResponse::CRUD_CREATE);
		} elseif ($record->isDeleted()) {
			$message .= 'deleted';
			$response->set_action(CodeTablesResponse::CRUD_DELETE);
		} else {
			$message .= 'updated';
			$response->set_action(CodeTablesResponse::CRUD_UPDATE);
		}

		$response->set_message($message);
		return $response;
	}

	/**
	 * [update_tariff_countries description]
	 * @param  [type] $code            [description]
	 * @param  array  $input_countries [description]
	 * @return [type]                  [description]
	 */
	public function update_tariff_countries($code, array $input_countries) {
		$updated = false;

		$q_delete = $this->get_tariffcodecountry_query($code);
		$q_delete->filterByCountry($input_countries, Criteria::NOT_IN);

		if ($q_delete->count()) {
			$updated = $q_delete->delete();
		}

		$q_exists = $this->get_tariffcodecountry_query($code);
		$q_exists->select(TariffCodeCountry::get_aliasproperty('country'));
		$q_exists->filterByCountry($input_countries);
		$existing_countries = $q_exists->find()->toArray();

		$create_countries = array_diff($input_countries, $existing_countries);

		if (sizeof($create_countries)) {
			foreach ($input_countries as $country) {
				$record = new TariffCodeCountry();
				$record->setCode($code);
				$record->setCountry($country);
				$record->setDate(date('Ymd'));
				$record->setTime(date('His'));
				$record->setDummy('P');
				$response = $record->save();
			}
			$q = $this->get_tariffcodecountry_query($code);
			$updated = $q->count() == sizeof($input_countries);
		}
		return $updated;
	}

	public function get_tariffcodecountry_query($code) {
		$q = TariffCodeCountryQuery::create();
		$q->filterByCode($code);
		return $q;
	}

	public function update_dplus_cobol($table, $code, $countries_updated = false) {
		$config = $this->wire('config');
		$dplusdb = $this->wire('modules')->get('DplusConnectDatabase')->db_name;
		$table = strtoupper($table);
		$data = array("DBNAME=$dplusdb", 'UPDATECODETABLE', "TABLE=$table", "CODE=$code");
		if ($countries_updated) {
			$data[] = 'CTRY=UPDATED';
		}
		$this->wire('modules')->get('CodeTables')->write_dplusfile($data, session_id());
		$this->wire('modules')->get('CodeTables')->http_get_dplus();
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus TARM Code Table CRUD Manager',
			'version' => 101,
			'summary' => 'Module for CRUD Methods for the TARM code table',
			'singular' => true,
			'autoload' => true,
		);
	}
}
