<?php namespace ProcessWire;

include_once(__DIR__.'../CodeTablesResponse.php');

use Purl\Url;

use Propel\Runtime\ActiveRecord\ActiveRecordInterface;

/**
 * Module that loads the Module needed for the AR code tables
 */
class CodeTablesIn extends WireData implements Module {

	const CODE_TABLES = array(
		'iwhm' => array(
			'code'   => 'iwhm',
			'module' => 'CodeTablesIwhm'
		),
		'iplm' => array(
			'code'   => 'iplm',
			'module' => 'CodeTablesIplm'
		),
		'stcm' => array(
			'code'   => 'stcm',
			'module' => 'CodeTablesStcm'
		),
		'spit' => array(
			'code'   => 'spit',
			'module' => 'CodeTablesSpit'
		),
		'csccm' => array(
			'code'   => 'csccm',
			'module' => 'CodeTablesCsccm'
		),
		'iasm' => array(
			'code'   => 'iasm',
			'module' => 'CodeTablesIasm'
		),
		'igcm' => array(
			'code'   => 'igcm',
			'module' => 'CodeTablesIgcm'
		),
		'umm' => array(
			'code'   => 'umm',
			'module' => 'CodeTablesUmm'
		),
		'msdsm' => array(
			'code'   => 'msdsm',
			'module' => 'CodeTablesMsdsm'
		),
		'igpm' => array(
			'code'   => 'igpm',
			'module' => 'CodeTablesIgpm'
		),
		'igm' => array(
			'code'   => 'igm',
			'module' => 'CodeTablesIgm'
		),
		'tarm' => array(
			'code'   => 'tarm',
			'module' => 'CodeTablesTarm'
		)
	);

	public function get_codetables() {
		return self::CODE_TABLES;
	}

	public function validate_codetable($table) {
		return array_key_exists($table, self::CODE_TABLES);
	}

	public function get_codetable_module($table) {
		return $this->wire('modules')->get(self::CODE_TABLES[$table]['module']);
	}

	/**
	 * ProcessWire Installer Function
	 * NOTE: Runs when installed through ProcessWire
	 * @return void
	 */
	public function ___install() {

	}

	/**
	 * ProcessWire removal Function
	 * NOTE: Runs when removed through ProcessWire
	 * @return void
	 */
	public function ___uninstall() {

	}

	public function update() {
		parent::update();

		$info = self::getModuleInfo();
		$modules = $this->wire('modules');

		foreach ($info['installs'] as $module_name) {
			$modules->install($module_name);
		}
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Codes Tables Inventory Management',
			'version' => 101,
			'summary' => 'Module for Inventory Codes Tables',
			'singular' => true,
			'autoload' => true,
			'installs' => array(
				'CodeTablesIwhm',
				'CodeTablesIplm',
				'CodeTablesStcm',
				'CodeTablesSpit',
				'CodeTablesCsccm',
				'CodeTablesIasm',
				'CodeTablesIgcm',
				'CodeTablesUmm',
				'CodeTablesMsdsm',
				'CodeTablesIgpm',
				'CodeTablesIgm',
				'CodeTablesTarm'
			)
		);
	}
}
