<?php namespace ProcessWire;

include_once(__DIR__.'/../CodeTablesResponse.php');

use Purl\Url;

use MsaSysopCodeQuery, MsaSysopCode;
use SysopOptionalCodeQuery, SysopOptionalCode;

/**
 * Module that handles the editing of the IOPTM codetable
 */
class CodeTablesIoptm extends WireData implements Module {
	const MODEL              = 'MsaSysopCode';
	const MODEL_KEY          = 'id';
	const DESCRIPTION        = 'Inventory Optional Codes';
	const DESCRIPTION_RECORD = 'Inventory Optional Codes';
	const MODEL_TABLE = 'sys_opt_options';

	public function __construct() {
		$this->description = self::DESCRIPTION;
	}

	/**
	 * Return the Code records from Database
	 * @param  string $table Table Code
	 * @return ObjectCollection
	 */
	public function get_codes() {
		$q = $this->get_query();
		return $q->find();
	}

	/**
	 * Return the Code records from Database filtered by ProductLne ID
	 * @param  string $productlne ProductLneID
	 * @return ObjectCollection
	 */
	public function get_code($opt_code) {
		$q = $this->get_query();
		return $q->findOneById($opt_code);
	}

	/**
	 * Returns if Codes Exists
	 * @param  string $productlne ProductLneID
	 * @return bool
	 */
	public function code_exists($opt_code) {
		$q = $this->get_query();
		return boolval($q->filterById($opt_code)->count());
	}

	/**
	 * Returns the associated ModelQuery class for table code
	 * @param  string $table Table Code
	 * @return mixed
	 */
	public function get_query() {
		$q = MsaSysopCodeQuery::create();
		return $q->filterBySystem(MsaSysopCode::SYSTEM_IN);
	}


	/**
	 * Return System Options
	 * @param  string $sysopcode
	 * @return MsaSysopCode[]
	 */
	public function get_sysops($opt_code) {
        $q = SysopOptionalCodeQuery::create();
		return $q->filterBySystem(MsaSysopCode::SYSTEM_IN)->filterByOpt_code($opt_code);
	}

	/**
	 * Return MsaSysopCodeQuery filtered for IN
	 * @return MsaSysopCodeQuery
	 */
	public function get_query_sysop() {
		$q = MsaSysopCodeQuery::create();
		return $q->filterBySystem(MsaSysopCode::SYSTEM_IN);
	}


	/**
	 * Takes Input, validates it's for one of the code tables
	 * Processes it, and if updated sends request to dplus
	 *
	 * NOTE: If an existing code is more than MsaSysopCode::MAX_LENGTH_CODE, we will allow editing
	 * but we won't allow creation of a code with more than allowed characters we will trim it.
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function process_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$table = $input->$rm->text('table');
		$code  = $input->$rm->text('code');

		$q = $this->get_query();
		$q->filterByCode($code);

		if ($q->count()) {
			$record = $q->findOne();
		} else {
			$code  = $input->$rm->text('code', array('maxLength' => MsaSysopCode::MAX_LENGTH_CODE));
			$record = new MsaSysopCode();
			$record->setCode($code);
		}

		if ($input->$rm->text('action') == 'remove-code') {
			$record->delete();
		} else {
			$description = $input->$rm->text('description');
			$record->setDescription($description);
			$record->setDate(date('Ymd'));
			$record->setTime(date('His'));
			$record->setDummy('P');
		}

		$this->wire('session')->response_codetable = $this->save_and_process_response($table, $code, $record);
	}

	/**
	 * Returns CodeTablesResponse based on the outcome of the database save
	 *
	 * @param  string $table  Table Code
	 * @param  string $code   Code being added
	 * @param  bool   $is_new Was the Record in the database before Save?
	 * @param  bool   $saved  Was the Record Saved?
	 * @return CodeTablesResponse
	 */
	protected function save_and_process_response($table, $code, MsaSysopCode $record) {
		$is_new = $record->isDeleted() ? false : $record->isNew();
		$saved  = $record->isDeleted() ? $record->isDeleted() : $record->save();

		$response = new CodeTablesResponse();
		$response->set_key($code);
		$message = self::DESCRIPTION_RECORD . " ($code) was ";

		if ($saved) {
			$response->set_success(true);
		} else {
			$response->set_error(true);
			$message .= "not ";
		}

		if ($is_new) {
			$message .= 'added';
			$response->set_action(CodeTablesResponse::CRUD_CREATE);
		} elseif ($record->isDeleted()) {
			$message .= 'deleted';
			$response->set_action(CodeTablesResponse::CRUD_DELETE);
		} else {
			$message .= 'updated';
			$response->set_action(CodeTablesResponse::CRUD_UPDATE);
		}

		$response->set_message($message);

		if ($response->has_success()) {
			$this->wire('modules')->get('CodeTables')->update_dplus_cobol($table, $code);
		}
		return $response;
	}

	/**
	 * Return the Max Length of characters for the code
	 * NOTE: Used for the JS
	 * @return int
	 */
	public function get_max_length_code() {
		return MsaSysopCode::MAX_LENGTH_CODE;
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus IOPTM Code Table CRUD Manager',
			'version' => 101,
			'summary' => 'Module for CRUD Methods for the IOPTM code table',
			'singular' => true,
			'autoload' => true,
		);
	}
}
