<?php namespace ProcessWire;

use Purl\Url;


class PrintLabel extends WireData implements Module {

	public static function getModuleInfo() {
		return array(
			'title' => 'Print Label Modules Manager',
			'version' => 101,
			'summary' => 'Manages Print Labels modules',
			'singular' => true,
			'autoload' => true,
			'installs' => array(
				'PrintLabelItem'
			)
		);
	}

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');
		$modules->refresh();

		foreach ($info['installs'] as $module_name) {
			$modules->install($module_name);
		}
	}
}
