<?php namespace ProcessWire;

use Propel\Runtime\ActiveQuery\Criteria;
use ItemXrefCustomerQuery, ItemXrefCustomer;

/**
 * FilterItemXrefCustomer
 * Filters Input to Retreive ItemXrefCustomer objects
 *
 * @property ItemXrefCustomerQuery $query
 */
class FilterXrefItemCxm extends WireData implements Module {
	public function __construct() {
		$this->query = ItemXrefCustomerQuery::create();
	}

	/**
	 * Returns Query
	 * @return ItemXrefCustomerQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * NOTE: Filters by Sales Rep if provided user is a Sales rep
	 *
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return void
	 */
	public function init_query(User $user) {
		$this->query = ItemXrefCustomerQuery::create();
	}

	/**
	 * Applies Filters to the Query
	 * NOTE:: Filters include Customer, ItemXrefCustomer #, ItemXrefCustomer Date, Review Date, Expire Date, ItemXrefCustomer Total, ItemXrefCustomer Status
	 *
	 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
	 * @return void
	 */
	public function filter_query(WireInput $input) {
		$this->filter_itemid($input);
		$this->filter_customerid($input);
	}

	/**
	 * Filters Query by Item ID
	 *
	 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
	 * @return void
	 */
	public function filter_itemid($input) {
		if ($input->get->itemID) {
			$this->query->filterByItemid($input->get->text('itemID'));
		} elseif ($input->get->ouritemID) {
			$this->query->filterByItemid($input->get->text('ouritemID'));
		}
	}

	/**
	 * Filters Query by Customer ID
	 *
	 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
	 * @return void
	 */
	public function filter_customerid($input) {
		if ($input->get->custID) {
			$this->query->filterByCustid($input->get->text('custID'));
		}
	}

	/**
	 * Adds the Sort By to the query
	 *
	 * @param  Page   $page
	 * @return void
	 */
	public function apply_sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;
			$tablecolumn = ItemXrefCustomer::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		} else {
			$this->query->orderByCustitemid('ASC');
		}
	}

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
		/**
		 * ProcessWire Module Info
		 *
		 * @return void
		 */
		public static function getModuleInfo() {
			return array(
				'title' => 'Dpluso filter X-ref Item CXM Module',
				'version' => 101,
				'summary' => 'Handles X-ref Item CXM Filtering',
				'singular' => true,
				'autoload' => true,
			);
		}
}
