<?php namespace ProcessWire;

use Propel\Runtime\ActiveQuery\Criteria;
use ItemXrefUpcQuery, ItemXrefUpc;

/**
 * FilterItemXrefUpc
 * Filters Input to Retreive ItemXrefUpc objects
 *
 * @property ItemXrefUpcQuery $query
 */
class FilterXrefItemUpc extends WireData implements Module {
	public function __construct() {
		$this->query = ItemXrefUpcQuery::create();
	}


	/**
	 * Returns Query
	 * @return ItemXrefUpcQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * NOTE: Filters by Sales Rep if provided user is a Sales rep
	 *
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return void
	 */
	public function init_query(User $user) {
		$this->query = ItemXrefUpcQuery::create();
	}

	/**
	 * Applies Filters to the Query
	 * NOTE:: Filters include Customer, ItemXrefUpc #, ItemXrefUpc Date, Review Date, Expire Date, ItemXrefUpc Total, ItemXrefUpc Status
	 *
	 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
	 * @return void
	 */
	public function filter_query(WireInput $input) {
		$this->filter_itemid($input);
	}

	/**
	 * Filters Query by Item ID
	 *
	 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
	 * @return void
	 */
	public function filter_itemid($input) {
		if ($input->get->itemID) {
			$this->query->filterByItemid($input->get->text('itemID'));
		}
	}


	/**
	 * Adds the Sort By to the query
	 *
	 * @param  Page   $page
	 * @return void
	 */
	public function apply_sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;
			$tablecolumn = ItemXrefUpc::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		} else {
			$this->query->orderByUpc('ASC');
		}
	}

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
		/**
		 * ProcessWire Module Info
		 *
		 * @return void
		 */
		public static function getModuleInfo() {
			return array(
				'title' => 'Dpluso filter X-ref Item UPC Module',
				'version' => 101,
				'summary' => 'Handles X-ref Item UPC Filtering',
				'singular' => true,
				'autoload' => true,
			);
		}
}
