<?php namespace ProcessWire;

use Propel\Runtime\ActiveQuery\Criteria;
use ItemXrefVendorQuery, ItemXrefVendor;

/**
 * FilterItemXrefVendor
 * Filters Input to Retreive ItemXrefVendor objects
 *
 * @property ItemXrefVendorQuery $query
 */
class FilterXrefItemVxm extends WireData implements Module {
	public function __construct() {
		$this->query = ItemXrefVendorQuery::create();
	}


	/**
	 * Returns Query
	 * @return ItemXrefVendorQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * NOTE: Filters by Sales Rep if provided user is a Sales rep
	 *
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return void
	 */
	public function init_query(User $user) {
		$this->query = ItemXrefVendorQuery::create();
	}

	/**
	 * Applies Filters to the Query
	 * NOTE:: Filters include Customer, ItemXrefVendor #, ItemXrefVendor Date, Review Date, Expire Date, ItemXrefVendor Total, ItemXrefVendor Status
	 *
	 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
	 * @return void
	 */
	public function filter_query(WireInput $input) {
		$this->filter_itemid($input);
		$this->filter_vendorid($input);
	}

	/**
	 * Filters Query by Item ID
	 *
	 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
	 * @return void
	 */
	public function filter_itemid($input) {
		if ($input->get->itemID) {
			$this->query->filterByOuritemid($input->get->text('itemID'));
		} elseif ($input->get->ouritemID) {
			$this->query->filterByOuritemid($input->get->text('ouritemID'));
		}
	}

	/**
	 * Filters Query by Vendor ID
	 *
	 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
	 * @return void
	 */
	public function filter_vendorid($input) {
		if ($input->get->vendorID) {
			$this->query->filterByVendorid($input->get->text('vendorID'));
		}
	}

	/**
	 * Filter Query by Vendor ID
	 * @param  array|string $vendorID  Vendor ID(s)
	 * @return void
	 */
	public function vendorid($vendorID) {
		$this->query->filterByVendorid($vendorID);
	}

	/**
	 * Searches the ItemXrefVendor Table to find vendors that match the query provided
	 *
	 * @param  string $q Search Query
	 * @return void
	 */
	public function filter_search($q) {
		$columns = array(
			ItemXrefVendor::get_aliasproperty('ouritemid'),
			ItemXrefVendor::get_aliasproperty('vendoritemid'),
			ItemXrefVendor::get_aliasproperty('description')
		);
		$this->query->search_filter($columns, strtoupper($q));
	}

	/**
	 * Adds the Sort By to the query
	 *
	 * @param  Page   $page
	 * @return void
	 */
	public function apply_sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;
			$tablecolumn = ItemXrefVendor::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		} else {
			$this->query->orderByVendoritemid('ASC');
		}
	}

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
		/**
		 * ProcessWire Module Info
		 *
		 * @return void
		 */
		public static function getModuleInfo() {
			return array(
				'title' => 'Dpluso filter X-ref Item VXM Module',
				'version' => 101,
				'summary' => 'Handles X-ref Item VXM Filtering',
				'singular' => true,
				'autoload' => true,
			);
		}
}
