<?php namespace ProcessWire;

use Propel\Runtime\ActiveQuery\Criteria;
use ItemXrefCustomerQuery, ItemXrefCustomer;

/**
 * FilterItemXrefCustomer
 *
 * Filters Input to Retreive ItemXrefCustomer objects
 * @property ItemXrefCustomerQuery $query
 */
class FilterXrefItemCxm extends WireData implements Module {
	public function __construct() {
		$this->query = ItemXrefCustomerQuery::create();
	}

	/**
	 * Returns Query
	 * @return ItemXrefCustomerQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * NOTE: Filters by Sales Rep if provided user is a Sales rep
	 *
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return void
	 */
	public function init_query(User $user) {
		$this->query = ItemXrefCustomerQuery::create();
	}

/* =============================================================
	Input Functions
============================================================= */
	/**
	 * Applies Filters to the Query
	 * NOTE:: Filters include Customer, ItemXrefCustomer #, ItemXrefCustomer Date, Review Date, Expire Date, ItemXrefCustomer Total, ItemXrefCustomer Status
	 *
	 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
	 * @return void
	 */
	public function filter_input(WireInput $input) {
		$this->itemid_input($input);
		$this->custid_input($input);
	}

	/**
	 * Filter Query by ItemID using Input Data
	 * @param  WireInput $input Input Data
	 * @return self
	 */
	public function itemid_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;

		$itemID = $values->ouritemID ? $values->text('ouritemID') : $values->text('itemID');
		return $this->itemid($itemID);
	}

	/**
	 * Filters Query by Customer ID
	 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
	 * @return void
	 */
	public function custid_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		if ($values->custID) {
			$this->custid($values->text('custID'));
		}
		return $this;
	}


/* =============================================================
	Base Filter Functions
============================================================= */
	/**
	 * Filters Query by Item ID
	 * @param  string|array $itemID Item ID(s)
	 * @return self
	 */
	public function itemid($itemID) {
		if ($itemID) {
			$this->query->filterByItemid($itemID);
		}
		return $this;
	}

	/**
	 * Filters Query by Customer ID
	 * @param  string|array  Customer ID(s)
	 * @return self
	 */
	public function custid($custID) {
		if ($custID) {
			$this->query->filterByCustid($custID);
		}
		return $this;
	}

	/**
	 * Searches the ItemXrefCustomer Table to find vendors that match the query provided
	 * @param  string $q Search Query
	 * @return void
	 */
	public function search($q) {
		$columns = array(
			ItemXrefCustomer::get_aliasproperty('itemid'),
			ItemXrefCustomer::get_aliasproperty('custitemid'),
			ItemXrefCustomer::get_aliasproperty('description')
		);
		$this->query->search_filter($columns, strtoupper($q));
	}

/* =============================================================
	Misc Query Functions
============================================================= */
	/**
	 * Adds the Sort By to the query
	 * @param  Page   $page
	 * @return void
	 */
	public function apply_sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;
			$tablecolumn = ItemXrefCustomer::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		} else {
			$this->query->orderByCustitemid('ASC');
		}
	}

	/**
	 * Return Position of CXM item in Results
	 * @param  ItemXrefCustomer $item CXM Item
	 * @return int
	 */
	public function position(ItemXrefCustomer $item) {
		$items = $this->query->find();
		return $items->search($item);
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso filter X-ref Item CXM Module',
			'version' => 101,
			'summary' => 'Handles X-ref Item CXM Filtering',
			'singular' => true,
			'autoload' => true,
		);
	}
}
