<?php namespace ProcessWire;

use Propel\Runtime\ActiveQuery\Criteria;
use ItemXrefUpcQuery, ItemXrefUpc;

/**
 * FilterItemXrefUpc
 * Filters Input to Retreive ItemXrefUpc objects
 *
 * @property ItemXrefUpcQuery $query
 */
class FilterXrefItemUpc extends WireData implements Module {
	public function __construct() {
		$this->query = ItemXrefUpcQuery::create();
	}

	/**
	 * Returns Query
	 * @return ItemXrefUpcQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * NOTE: Filters by Sales Rep if provided user is a Sales rep
	 *
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return void
	 */
	public function init_query(User $user) {
		$this->query = ItemXrefUpcQuery::create();
	}

	/**
	 * Applies Filters to the Query
	 * NOTE:: Filters include Customer, ItemXrefUpc #, ItemXrefUpc Date, Review Date, Expire Date, ItemXrefUpc Total, ItemXrefUpc Status
	 *
	 * @param  WireInput $input Object that Contains the $_GET array for values to filter on
	 * @return void
	 */
	public function filter_input(WireInput $input) {
		$this->itemid_input($input);
		return $this;
	}

	/**
	 * Filter Query by ItemID using Input Data
	 * @param  WireInput $input Input Data
	 * @return self
	 */
	public function itemid_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;

		$itemID = $values->text('itemID');
		return $this->itemid($itemID);
	}

/* =============================================================
	Base Filter Functions
============================================================= */
	/**
	 * Filters Query by Item ID
	 * @param  string|array $itemID Item ID(s)
	 * @return self
	 */
	public function itemid($itemID) {
		if ($itemID) {
			$this->query->filterByItemid($itemID);
		}
		return $this;
	}

	/**
	 * Searches the ItemXrefUpc Table to find vendors that match the query provided
	 * @param  string $q Search Query
	 * @return self
	 */
	public function search($q) {
		$columns = [
			ItemXrefUpc::get_aliasproperty('upc'),
			ItemXrefUpc::get_aliasproperty('itemid'),
		];
		$this->query->search_filter($columns, strtoupper($q));
		return $this;
	}

	/**
	 * Return Position of SalesPerson in results
	 * @param  ItemXrefUpc $item SalesPerson
	 * @return int
	 */
	public function position(ItemXrefUpc $xref) {
		$results = $this->query->find();
		return $results->search($xref);
	}

/* =============================================================
	Misc Query Functions
============================================================= */
	/**
	 * Adds the Sort By to the query
	 * @param  Page   $page
	 * @return void
	 */
	public function apply_sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;
			$tablecolumn = ItemXrefUpc::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		} else {
			$this->query->orderByUpc('ASC');
		}
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso filter X-ref Item UPC Module',
			'version' => 101,
			'summary' => 'Handles X-ref Item UPC Filtering',
			'singular' => true,
			'autoload' => true,
		);
	}
}
