<?php namespace ProcessWire;


class FilterXref extends WireData implements Module {
	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
		public function update() {
			$info = self::getModuleInfo();
			$modules = $this->wire('modules');
			$modules->refresh();

			foreach ($info['installs'] as $module_name) {
				$modules->install($module_name);
			}
		}
		
		/**
		 * ProcessWire Module Info
		 *
		 * @return void
		 */
		public static function getModuleInfo() {
			return array(
				'title' => 'Dpluso filter X-ref Module',
				'version' => 101,
				'summary' => 'Handles X-ref Filtering',
				'singular' => true,
				'autoload' => true,
				'installs' => array(
					'FilterItemCxm',
					'FilterItemVxm',
					'FilterItemUpc',
				)
			);
		}
}
