<?php namespace ProcessWire;

include_once(__DIR__.'/../CodeTablesResponse.php');

use Purl\Url;

use Propel\Runtime\ActiveRecord\ActiveRecordInterface;

/**
 * Module that loads the Module needed for the AR code tables
 */
class CodeTablesMsa extends WireData implements Module {

	const CODE_TABLES = array(
		'sysop' => array(
			'code'        		 => 'sysop',
			'module'   			 => 'MsaSysop'
		),
		'lgrp' => array(
			'code'        		 => 'lgrp',
			'module'   			 => 'MsaLgrp'
		),
	);

	public function get_codetables() {
		return self::CODE_TABLES;
	}

	public function validate_codetable($table) {
		return array_key_exists($table, self::CODE_TABLES);
	}

	public function get_codetable_module($table) {
		return $this->wire('modules')->get(self::CODE_TABLES[$table]['module']);
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Codes Tables MSA Management',
			'version' => 101,
			'summary' => 'Module for Codes Tables MSA Management',
			'singular' => true,
			'autoload' => true,
			'installs' => array(

			)
		);
	}

	/**
	 * ProcessWire Installer Function
	 * NOTE: Runs when installed through ProcessWire
	 * @return void
	 */
	public function ___install() {

	}

	/**
	 * ProcessWire removal Function
	 * NOTE: Runs when removed through ProcessWire
	 * @return void
	 */
	public function ___uninstall() {

	}

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');

		foreach ($info['installs'] as $module_name) {
			$modules->install($module_name);
		}
	}
}
