<?php namespace ProcessWire;

use Purl\Url;

include_once(__DIR__.'/XrefResponse.php');

class Xrefs extends WireData implements Module {

	/**
	 * ProcessWire Installer Function
	 * NOTE: Runs when installed through ProcessWire
	 * @return void
	 */
	public function ___install() {

	}

	/**
	 * ProcessWire removal Function
	 * NOTE: Runs when removed through ProcessWire
	 * @return void
	 */
	public function ___uninstall() {

	}

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');

		foreach ($info['installs'] as $module_name) {
			$modules->install($module_name);
		}
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Xrefs Management',
			'version' => 101,
			'summary' => 'Module for Xrefs Management',
			'singular' => true,
			'autoload' => true,
			'installs' => array(
				'XrefVxm',
				'XrefUpc'
			)
		);
	}
}
