<?php namespace ProcessWire;

use Purl\Url;

include_once(__DIR__.'/XrefResponse.php');

class Xrefs extends WireData implements Module {

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');
		$modules->refresh();

		foreach ($info['installs'] as $module_name) {
			$modules->install($module_name);
		}
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Xrefs Management',
			'version' => 101,
			'summary' => 'Module for Xrefs Management',
			'singular' => true,
			'autoload' => true,
			'installs' => array(
				'XrefVxm',
				'XrefUpc',
				'XrefCxm',
				'XrefMxrfe',
			)
		);
	}
}
