<?php namespace ProcessWire;

/**
 * Load
 *
 * Parent Module to Install Sub Lookup Modules
 */
class Load extends WireData implements Module {

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');

		foreach ($info['installs'] as $module_name) {
			if (!$modules->isInstalled($module_name)) {
				$result = $modules->install($module_name);
			}
		}
	}

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Load Module',
			'version' => 101,
			'summary' => 'Handles Load Modules Installation & Updates',
			'singular' => true,
			'autoload' => true,
			'installs' => array(
				'LoadItem',
			)
		);
	}
}
