<?php namespace ProcessWire;


class ItemIiLookup extends ItemLookup implements Module {

	/**
	 * Looks Up Item
	 * @param  string $q Item ID | UPC | Short Item ID
	 * @return void
	 */
	public function lookup($q) {
		$this->lookup_itm($q);

		if (!$this->exists) {
			$this->lookup_itm_short($q);
		}

		if (!$this->exists) {
			$this->lookup_upcx($q);
		}
	}

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Item II Lookup Module',
			'version' => 101,
			'summary' => 'Handles Item Lookup for II',
			'singular' => true,
			'autoload' => true,
			'installs' => array(),
			'requires' => array('ItemLookup')
		);
	}
}
