<?php namespace ProcessWire;

class FilterMso extends WireData implements Module {

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');
		$modules->refresh();

		foreach ($info['installs'] as $module_name) {
			$modules->install($module_name);
		}
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Filters MSO Module',
			'version' => 101,
			'summary' => 'Handles Loading of MSO Filters Modules',
			'singular' => true,
			'autoload' => true,
			'installs' => array(
				'FilterMsoFreightCodes',
			)
		);
	}
}
