<?php namespace ProcessWire;

use Dplus\CodeValidators\Mso as MsoValidator;

use SalesHistoryNotesQuery, SalesHistoryNotes;
use SalesHistoryQuery, SalesHistory;
use ConfigArQuery, ConfigAr;
use ConfigSalesOrderQuery, ConfigSalesOrder;

include_once(__DIR__.'/QnotesResponse.php');

/**
 * QnotesSalesHistory
 *
 * Class for Writing and Reading Qnotes for Sales History Order
 */
class QnotesSalesHistory extends WireData implements Module {
	const MODEL              = 'SalesHistoryNotes';
	const MODEL_KEY          = 'OehhNbr, OedtLine';
	const DESCRIPTION        = 'Sales History Note';
	const DESCRIPTION_RECORD = 'Sales History Note';
	const DESCRIPTION_RESPONSE = 'Sales History ';
	const MODEL_TABLE = 'notes_sh_head_det';

	public function allow_add(User $user, $ordn) {
		return false;
	}

	/**
	 * Return the Max Number of columns for Note Type
	 * @return int
	 */
	public function get_column_count() {
		$configAR = ConfigArQuery::create()->findOne();
		return $configAR->columns_notes_invoice;
	}

/* =============================================================
	CRUD Read, Validate Functions
============================================================= */
	/**
	 * Returns Sales History Notes Query
	 * @return SalesHistoryNotesQuery
	 */
	public function get_query() {
		return SalesHistoryNotesQuery::create();
	}

	/**
	 * Returns if Notes Exist
	 * @param  string $ordn    Order Number
	 * @param  int    $linenbr Line Number
	 * @return bool
	 */
	public function notes_exist($ordn, $linenbr) {
		$q = $this->get_query();
		$q->filterByOrdernumber($ordn);
		$q->filterByLine($linenbr);
		return boolval($q->count());
	}

	/**
	 * Returns Line 1 of Every Note
	 * @param  string $ordn    Order Number
	 * @param  int    $linenbr Line Number
	 * @return SalesHistoryNotes[]|ObjectCollection
	 */
	public function get_notes_summarized($ordn, $linenbr) {
		$q = $this->get_query();
		$q->filterByOrdernumber($ordn);
		$q->filterByLine($linenbr);
		$q->filterBySequence(1);
		return $q->find();
	}

	/**
	 * Return Notes for Form
	 * @param  string $ordn    Order Number
	 * @param  int    $linenbr Line Number
	 * @param  string $form    Form to Match to e.g YYYN
	 * @return array
	 */
	public function get_notes_form_array($ordn, $linenbr, $form) {
		$q = $this->get_query();
		$q->select(SalesHistoryNotes::get_aliasproperty('note'));
		$q->filterByOrdernumber($ordn);
		$q->filterByLine($linenbr);
		$q->filterByForm($form);
		return $q->find()->toArray();
	}

/* =============================================================
	CRUD Delete
============================================================= */
	/**
	 * Delete Notes for Form
	 * @param  string $ordn    Order Number
	 * @param  int    $linenbr Line Number
	 * @param  string $form    Form to Match to e.g YYYN
	 * @return array
	 */
	public function delete_notes($ordn, $linenbr, $form) {
		$q = $this->get_query();
		$q->filterByOrdernumber($ordn);
		$q->filterByLine($linenbr);
		$q->filterByForm($form);

		if ($q->count()) {
			return $q->delete();
		}
		return true;
	}

/* =============================================================
	CRUD Processing Functions
============================================================= */
	/**
	 * Takes Input, Processes it, updates Sales Order Notes in the Database
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function process_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());

		$lookup_orders = new MsoValidator();
		$ordn = $input->$rm->text('ordn');

		if ($lookup_orders->order($ordn)) {
			$this->wire('modules')->get('QnotesSalesOrder')->process_input($input);
		} else {
			switch ($input->$rm->text('action')) {
				case 'update-notes':
					$this->update_notes_input($input);
					break;
				case 'delete-notes':
					$this->delete_notes_input($input);
					break;
			}
		}
	}

	/**
	 * Takes Input, Processes it, deletes Sales History Notes
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function delete_notes_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$ordn  = $input->$rm->text('ordn');
		$linenbr = $input->$rm->text('linenbr');
		$form    = $input->$rm->text('form');
		$q = $this->get_query();
		$q->filterByOrdernumber($ordn);
		$q->filterByLine($linenbr);
		$q->filterByForm($form);

		if ($q->count()) {
			$note = $q->findOne();
		} else {
			$note = new SalesHistoryNotes();
			$note->setOrdernumber($ordn);
			$note->setLine($linenbr);
			$note->setForm($form);
		}
		$success = $this->delete_notes($ordn, $linenbr, $form);
		$this->wire('session')->response_qnote = $this->process_response_delete($note, $ordn, $success);
	}

	/**
	 * Takes Input, Processes it, updates Sales History Notes
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function update_notes_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$ordn  = $input->$rm->text('ordn');

		$linenbr = $input->$rm->text('linenbr');
		$form    = $input->$rm->text('form');
		$note_lines = explode(PHP_EOL, $input->$rm->textarea('note'));
		$lines_saved = array();

		if (empty($form)) {
			$form = '';
			$form .= $input->$rm->text('check_pick') == SalesHistoryNotes::FORM_TRUE ? 'Y' : 'N';
			$form .= $input->$rm->text('check_pack') == SalesHistoryNotes::FORM_TRUE ? 'Y' : 'N';
			$form .= $input->$rm->text('check_invoice') == SalesHistoryNotes::FORM_TRUE ? 'Y' : 'N';
			$form .= $input->$rm->text('check_acknowledgement') == SalesHistoryNotes::FORM_TRUE ? 'Y' : 'N';
		}

		$year = SalesHistoryQuery::create()->select(SalesHistory::get_aliasproperty('year'))->findOneByOrdernumber($ordn);

		$this->delete_notes($ordn, $linenbr, $form);

		foreach ($note_lines as $key => $line) {
			$sequence = $key + 1;
			$record = new SalesHistoryNotes();
			$record->setType(SalesHistoryNotes::TYPE); // PK
			$record->setDescription(SalesHistoryNotes::DESCRIPTION);
			$record->setOrdernumber($ordn);
			$record->setLine($linenbr);
			$record->generateKey2(); // PK
			$record->setSequence($sequence); // PK
			$record->setForm($form);
			$record->setNote($line);
			$record->setYear($year);

			$record->setPickticket($input->$rm->text('check_pick') == SalesHistoryNotes::FORM_TRUE ? 'Y' : 'N');
			$record->setPackticket($input->$rm->text('check_pack') == SalesHistoryNotes::FORM_TRUE ? 'Y' : 'N');
			$record->setInvoice($input->$rm->text('check_invoice') == SalesHistoryNotes::FORM_TRUE ? 'Y' : 'N');
			$record->setAcknowledgement($input->$rm->text('check_acknowledgement') == SalesHistoryNotes::FORM_TRUE ? 'Y' : 'N');

			$record->setDate(date('Ymd'));
			$record->setTime(date('His'));
			$record->setDummy('P');
			$lines_saved[$sequence] = $record->save();
		}
		$this->wire('session')->response_qnote = $this->process_responses($record, $ordn, $lines_saved);
	}

/* =============================================================
	CRUD Response Functions
============================================================= */
	/**
	 * Return Code Table Response based on the number of lines that were written to the database
	 * @param  string $ordn         Sales History Number
	 * @param  array  $lines_saved  array of line numbers and if they got saved e.g. (1 => true, 2 => false)
	 * @return CodeTableResponse
	 */
	protected function process_responses(SalesHistoryNotes $note, $ordn, array $lines_saved) {
		$message = self::DESCRIPTION_RESPONSE . " ($ordn) Notes";

		$response = new QnotesResponse();
		$response->set_key("$ordn-{$note->line}-{$note->form}");

		if (in_array(false, $lines_saved)) {
			$lines_error =
			array_filter($lines_saved, function($value, $key) {
				return  $value == false;
			}, ARRAY_FILTER_USE_BOTH);
			$message .= implode(", ", array_keys($lines_error));
			$message .= " were not able to be saved";

			if (sizeof($lines_error)) {
				$response->set_error(true);
			}
		} else {
			$response->set_success(true);
			$message .= " were able to be saved";
		}

		$response->set_action(QnotesResponse::CRUD_UPDATE);
		$response->set_message($message);

		// IF there are lines saved
		if (sizeof($lines_saved)) {
			$this->wire('modules')->get('Qnotes')->update_dplus_cobol($note->type, $note->key2, $note->form);
		}
		return $response;
	}

	/**
	 * Return QnoteResponse based if Notes were able to be Deleted
	 * @param  SalesHistoryNotes $note         Attributes are needed to generate key
	 * @param  string            $ordn         Sales History Number
	 * @param  array             $success      Were Notes able to be deleted?
	 * @return QnoteResponse
	 */
	public function process_response_delete(SalesHistoryNotes $note, $ordn, bool $success) {
		$message = self::DESCRIPTION_RESPONSE . " ($ordn) Notes ";

		$response = new QnotesResponse();
		$response->set_key("$ordn-{$note->line}-{$note->form}");

		if ($success) {
			$response->set_success(true);
			$message .= " were able to be deleted";
		} else {
			$response->set_success(true);
			$message .= " were not able to be deleted";
		}

		$response->set_action(QnotesResponse::CRUD_DELETE);
		$response->set_message($message);

		// IF there are lines saved
		if ($success) {
			$this->wire('modules')->get('Qnotes')->update_dplus_cobol($note->type, $note->key2, $note->form);
		}
		return $response;
	}

/* =============================================================
	Supplemental Functions
============================================================= */
	/**
	 * Return Default forms
	 * @return array
	 */
	public function get_default_forms() {
		$config_so = ConfigSalesOrderQuery::create()->findOne();
		$defaults = array(
			'pick' => $config_so->note_default_pick,
			'pack' => $config_so->note_default_pack,
			'invoice' => $config_so->note_default_invoice,
			'acknowledgement' => $config_so->note_default_acknowledgement,
		);
		return $defaults;
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Qnotes Sales History',
			'version' => 101,
			'summary' => 'Dplus Qnotes Sales History methods',
			'singular' => true,
			'autoload' => true,
			'requires' => array('Qnotes')
		);
	}
}
