<?php namespace ProcessWire;

class Qponotes extends WireData implements Module {
	/**
	 * Return Data needed for Dplus to UPDATE the Q PO NOTES
	 * @param  string $notetype Note Type @see WarehouseNote::TYPES
	 * @param  string $key2     Key 2
	 * @param  string $form     Form e.g YNNN
	 * @return array
	 */
	public function write_dplus_data($notetype, $key2, $form) {
		$dplusdb = $this->wire('modules')->get('DplusDatabase')->db_name;
		return array("DBNAME=$dplusdb", 'UPDATEPONOTE', "TYPE=$notetype", "KEY2=$key2", "FORM=$form");
	}

	/**
	 * Sends Update Request for Qnote Type
	 * @param  string $notetype Note Type
	 * @param  string $key2     Key 2
	 * @param  string $form     Form e.g YNNN
	 * @return void
	 */
	public function update_dplus_cobol($notetype, $key2, $form) {
		$config = $this->wire('config');
		$dplusdb = $this->wire('modules')->get('DplusDatabase')->db_name;
		$data = $this->write_dplus_data($notetype, $key2, $form);
		$requestor = $this->wire('modules')->get('DplusRequest');
		$requestor->write_dplusfile($data, session_id());
		$requestor->cgi_request($config->cgis['database'], session_id());
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Qnotes PO',
			'version' => 101,
			'summary' => 'Dplus Qnotes PO',
			'singular' => true,
			'autoload' => true,
			'installs' => array(
			)
		);
	}
}
