<?php namespace ProcessWire;

	require_once(__DIR__ . '/DplusoConfig.module');

	class WarehouseConfig extends WireData implements Module {
	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
		/**
		 * ProcessWire Module Info
		 *
		 * @return void
		 */
		public static function getModuleInfo() {
			return array(
				'title' => 'Dpluso Config Module',
				'version' => 101,
				'summary' => 'Handles Dplus Warehouse Configurations',
				'singular' => true,
				'autoload' => true,
				'requires' => array('DplusPwPages'),
				'installs' => array('WarehouseInventoryConfig', 'WarehousePickingConfig'),
			);
		}
	}
