<?php namespace ProcessWire;

	class WarehousePickingConfig extends Process implements ConfigurableModule {
	/* =============================================================
			ProcessWire Module Functions
	=============================================================== */

		const CONFIG_FIELDS = array(
			'picking_method' => array(
				'type'        => 'select',
				'label'       => 'Customer Picking Method',
				'description' => 'Picking Method',
				'notes'       => "Unguided: User will not be guided through the order
				Guided: User will be guided through the order",
				'options' => array('guided' => 'Guided', 'unguided' => 'Unguided')
			)
		);

		const DEFAULT_CONFIG = array(
			'picking_method' => 'unguided'
		);

		/**
		 * ProcessWire Module Info
		 *
		 * @return void
		 */
		public static function getModuleInfo() {
			return array(
				'title' => 'Dpluso Warehouse Picking Config Module',
				'version' => 101,
				'summary' => 'Handles Dplus Warehouse Picking Configurations',
				'singular' => true,
				'autoload' => true,
				'requires' => array('DplusPwPages'),
				//'installs' => array('DplusoSalesOrder'),
			);
		}

		static public function getModuleConfigInputfields(array $data) {
			$modules = wire('modules');
			$fields = new InputfieldWrapper();
			$data = array_merge(self::DEFAULT_CONFIG, $data);

			$traits = self::CONFIG_FIELDS['picking_method'];
			$f = $modules->get("InputfieldSelect");
			$f->attr('name', 'picking_method');
			$f->label = __($traits['label']);
			$f->description = __($traits['description']);
			$f->notes = _($traits['notes']);
			$f->addOptions($traits['options']);
			$f->value = $data['picking_method'];
			$fields->add($f);

			return $fields;
		}
	}
