<?php namespace ProcessWire;

include_once(__DIR__.'../CodeTablesResponse.php');

use Purl\Url;

use Propel\Runtime\ActiveRecord\ActiveRecordInterface;

/**
 * Module that loads the Module needed for the AR code tables
 */
class CodeTablesAr extends WireData implements Module {

	const CODE_TABLES = array(
		'ccm' => array(
			'code'        		 => 'ccm',
			'module'   			 => 'CodeTablesCcm',
			'description' 	     => 'Customer Commission Code',
			'description-record' => 'Customer Commission Code',
			'model'       		 => 'CustomerCommissionCode',
			'model-key'   		 => 'code'
		),
		'crtm' => array(
			'code'        		 => 'crtm',
			'module'   			 => 'CodeTablesCrtm',
			'description'  		 => 'Customer Route Code',
			'description-record' => 'Customer Route Code',
			'model'       		 => 'CustomerRouteCode',
			'model-key'   		 => 'code'
		),
		'spgpm' => array(
			'code'        		 => 'spgpm',
			'module'   			 => 'CodeTablesSpgpm',
			'description' 		 => 'Salesperson Group Code',
			'description-record' => 'Salesperson Group Code',
			'model'       		 => 'SalespersonGroupCode',
			'model-key'   		 => 'code'
		),
		'worm' => array(
			'code'        		 => 'worm',
			'module'   			 => 'CodeTablesWorm',
			'description' 		 => 'Customer Write Off Code',
			'description-record' => 'Customer Write Off Code',
			'model'       		 => 'CustomerWriteOffCode',
			'model-key'   		 => 'code'
		),
		'cpm' => array(
			'code'        		 => 'cpm',
			'module'   			 => 'CodeTablesCpm',
			'description' 		 => 'Customer Price Code',
			'description-record' => 'Customer Price Code',
			'model'       		 => 'CustomerPriceCode',
			'model-key'   		 => 'code'
		),
		'ctm' => array(
			'code'        		 => 'ctm',
			'module'   			 => 'CodeTablesCtm',
			'description' 		 => 'Customer Type Code',
			'description-record' => 'Customer Type Code',
			'model'       		 => 'CustomerTypeCode',
			'model-key'   		 => 'code'
		),
	);

	public function get_codetables() {
		return self::CODE_TABLES;
	}

	public function validate_codetable($table) {
		return array_key_exists($table, self::CODE_TABLES);
	}

	public function get_codetable_module($table) {
		return $this->wire('modules')->get(self::CODE_TABLES[$table]['module']);
	}



	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Codes Tables AR Management',
			'version' => 101,
			'summary' => 'Module for Codes Tables AR Managment',
			'singular' => true,
			'autoload' => true,
		);
	}
}
