<?php namespace ProcessWire;

include_once(__DIR__.'/../CodeTablesResponse.php');

use Purl\Url;

use CustomerTypeCodeQuery, CustomerTypeCode;
use ConfigArQuery, ConfigAr;

/**
 * Module that handles the editing of the CCM codetable
 */
class CodeTablesCtm extends WireData implements Module {
	const MODEL              = 'CustomerTypeCode';
	const MODEL_KEY          = 'code';
	const DESCRIPTION        = 'Customer Type Code';
	const DESCRIPTION_RECORD = 'Customer Type Code';
	const TABLE              = 'ctm';

	public function __construct() {
		$this->description = self::DESCRIPTION;
	}

	/**
	 * Return the Code records from Database
	 * @return CustomerTypeCode[]|ObjectCollection
	 */
	public function get_codes() {
		$q = $this->get_query();
		return $q->find();
	}

	/**
	 * Return the Code
	 * @param  string $code Customer Type Code
	 * @return CustomerTypeCode
	 */
	public function get_code($code) {
		$q = $this->get_query();
		return $q->findOneByCode($code);
	}

	/**
	 * Return if the Code Exists
	 * @param  string $code Customer Type Code
	 * @return bool
	 */
	public function code_exists($code) {
		$q = $this->get_query();
		return boolval($q->filterByCode($code)->count());
	}

	/**
	 * Returns a new CustomerTypeCode
	 * @return CustomerTypeCode
	 */
	public function get_new_code() {
		return new CustomerTypeCode();
	}

	/**
	 * Returns the associated ModelQuery class for table code
	 * @param  string $table Table Code
	 * @return mixed
	 */
	public function get_query() {
		return CustomerTypeCodeQuery::create();
	}

	/**
	 * Takes Input, validates it's for one of the code tables
	 * Processes it, and if updated sends request to dplus
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function process_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$table = $input->$rm->text('table');
		$code  = $input->$rm->text('code');

		if ($input->$rm->text('action') == 'update-notes' || $input->$rm->text('action') == 'delete-notes') {
			$this->wire('modules')->get('CodeTablesCtmNotes')->process_input($input);
		} else {
			$this->process_input_ctm($input);
		}
	}

	/**
	 * Takes Input Processes it, updates the ctm table,
	 * and if updated sends request to dplus
	 *
	 * NOTE: If an existing code is more than TariffCode::MAX_LENGTH_CODE, we will allow editing
	 * but we won't allow creation of a code with more than allowed characters we will trim it.
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function process_input_ctm(WireInput $input) {
		$configAR = ConfigArQuery::create()->findOne();
		$rm = strtolower($input->requestMethod());
		$table = self::TABLE;
		$code = $input->$rm->text('code');

		$q = $this->get_query();
		$q->filterByCode($code);

		if ($q->count()) {
			$record = $q->findOne();
		} else {
			$code  = $input->$rm->text('code', array('maxLength' => CustomerTypeCode::MAX_LENGTH_CODE));
			$record = new CustomerTypeCode();
			$record->setCode($code);
		}

		if ($input->$rm->action) {
			$recordlocker = $this->wire('modules')->get('RecordLockerUser');

			/**
			 * Create lock for CTM code if not already locked.
			 */
			if (!$recordlocker->function_locked('ctm', $code)) {
				$recordlocker->create_lock('ctm', $code);
			}

			if ($record->isNew() || $recordlocker->function_locked_by_user('ctm', $code)) {
				if ($input->$rm->text('action') == 'remove-code') {
					$record->delete();
				} elseif ($input->$rm->text('action') == 'update-ctm') {
					$description = $input->$rm->text('description');
					$email = $input->$rm->text('order_approval_email');
					$record->setDescription($description);
					$record->setOrder_approval_email($email);
					$record->setMail_list($input->$rm->text('mail_list'));
					$record->setDate(date('Ymd'));
					$record->setTime(date('His'));
					$record->setDummy('P');

					if ($configAR->gl_report_type() == 'customer') {
						$record->setAccount_sales($input->$rm->text('gl_sales'));
						$record->setAccount_credits($input->$rm->text('gl_credits'));
						$record->setAccount_cogs($input->$rm->text('gl_cogs'));
						$record->setAccount_freight($input->$rm->text('gl_freight'));
						$record->setAccount_misc($input->$rm->text('gl_misc'));
						$record->setAccount_cash($input->$rm->text('gl_cash'));
						$record->setAccount_ar($input->$rm->text('gl_ar'));
						$record->setAccount_finance($input->$rm->text('gl_finance'));
						$record->setAccount_discounts($input->$rm->text('gl_discounts'));
					}
				}
				$response = $this->save_and_process_response($table, $code, $record);
			} else {
				$response = new CodeTablesResponse();
				$response->set_key($code);
				$response->set_error(true);
				$response->set_action(CodeTablesResponse::CRUD_UPDATE);
				$message = self::DESCRIPTION_RECORD . " ($code) was not updated because it is locked by " . $recordlocker->get_locked_user('ctm', $code);
				$response->set_message($message);
			}
		} else {
			$response = new CodeTablesResponse();
			$response->set_key($code);
			$response->set_error(true);
			$response->set_action(CodeTablesResponse::CRUD_UPDATE);
			$message = self::DESCRIPTION_RECORD . " ($code) was not updated ";
			$response->set_message($message);
		}
		$this->wire('session')->response_codetable = $response;
	}

	/**
	 * Returns CodeTablesResponse based on the outcome of the database save
	 *
	 * @param  string $table  Table Code
	 * @param  string $code   Code being added
	 * @param  bool   $is_new Was the Record in the database before Save?
	 * @param  bool   $saved  Was the Record Saved?
	 * @return CodeTablesResponse
	 */
	protected function save_and_process_response($table, $code, CustomerTypeCode $record) {
		$is_new = $record->isDeleted() ? false : $record->isNew();
		$saved  = $record->isDeleted() ? $record->isDeleted() : $record->save();

		$response = new CodeTablesResponse();
		$response->set_key($code);
		$message = self::DESCRIPTION_RECORD . " ($code) was ";

		if ($saved) {
			$response->set_success(true);
		} else {
			$response->set_error(true);
			$message .= "not ";
		}

		if ($is_new) {
			$message .= 'added';
			$response->set_action(CodeTablesResponse::CRUD_CREATE);
		} elseif ($record->isDeleted()) {
			$message .= 'deleted';
			$response->set_action(CodeTablesResponse::CRUD_DELETE);
		} else {
			$message .= 'updated';
			$response->set_action(CodeTablesResponse::CRUD_UPDATE);
		}

		$response->set_message($message);

		if ($response->has_success()) {
			$this->wire('modules')->get('CodeTables')->update_dplus_cobol($table, $code);
		}

		return $response;
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus CTM Code Table CRUD Manager',
			'version' => 101,
			'summary' => 'Module for CRUD Methods for the CTM code table',
			'singular' => true,
			'autoload' => true,
		);
	}
}
