<?php namespace ProcessWire;

include_once(__DIR__.'/../CodeTablesResponse.php');

use Purl\Url;

use CustomerQuery, Customer;

/**
 * Module that handles the editing of the CCM codetable
 */
class CodeTablesCmm extends WireData implements Module {
	const MODEL              = 'Customer';
	const MODEL_KEY          = 'code';
	const DESCRIPTION        = 'Customer Maintenance';
	const DESCRIPTION_RECORD = 'Customer Maintenance';
	const TABLE              = 'cmm';

	public function __construct() {
		$this->description = self::DESCRIPTION;
	}

	/**
	 * Return the Code records from Database
	 * @return Customer[]|ObjectCollection
	 */
	public function get_codes() {
		$q = $this->get_query();
		return $q->find();
	}

	/**
	 * Return the Code
	 * @param  string $code Customer Code
	 * @return Customer
	 */
	public function get_code($code) {
		$q = $this->get_query();
		return $q->findOneByCustid($code);
	}

	/**
	 * Return if the Code Exists
	 * @param  string $code Customer Code
	 * @return bool
	 */
	public function code_exists($code) {
		$q = $this->get_query();
		return boolval($q->filterByCustid($code)->count());
	}

	/**
	 * Returns a new Customer
	 * @return Customer
	 */
	public function get_new_code() {
		return new Customer();
	}

	/**
	 * Returns the associated ModelQuery class for table code
	 * @param  string $table Table Code
	 * @return mixed
	 */
	public function get_query() {
		return CustomerQuery::create();
	}

	/**
	 * Takes Input, validates it's for one of the code tables
	 * Processes it, and if updated sends request to dplus
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function process_input(WireInput $input) {
        $rm = strtolower($input->requestMethod());
		$table = $input->$rm->text('table');
		$code  = $input->$rm->text('code');

		$q = $this->get_query();
		$q->filterByCustid($code);

		if ($q->count()) {
			$record = $q->findOne();
		} else {
			$code  = $input->$rm->text('code', array('maxLength' => Customer::MAX_LENGTH_CODE));
			$record = new Customer();
			$record->setCustid($code);
		}

		if ($input->$rm->action) {
			$recordlocker = $this->wire('modules')->get('RecordLockerUser');

			/**
			 * Create lock for IGM code if not already locked.
			 */
			if (!$recordlocker->function_locked('cmm', $code)) {
				$recordlocker->create_lock('cmm', $code);
			}

			if ($record->isNew() || $recordlocker->function_locked_by_user('cmm', $code)) {
				if ($input->$rm->text('action') == 'remove-code') {
					$record->delete();
				} elseif ($input->$rm->text('action') == 'update-cmm') {
					$name = $input->$rm->text('name');
					$record->setName($name);
					$record->setDate(date('Ymd'));
					$record->setTime(date('His'));
					$record->setDummy('P');
				}
				$response = $this->save_and_process_response($table, $code, $record);
			} else {
				$response = new CodeTablesResponse();
				$response->set_key($code);
				$response->set_error(true);
				$response->set_action(CodeTablesResponse::CRUD_UPDATE);
				$message = self::DESCRIPTION_RECORD . " ($code) was not updated because it is locked by " . $recordlocker->get_locked_user('cmm', $code);
				$response->set_message($message);
			}
		} else {
			$response = new CodeTablesResponse();
			$response->set_key($code);
			$response->set_error(true);
			$response->set_action(CodeTablesResponse::CRUD_UPDATE);
			$message = self::DESCRIPTION_RECORD . " ($code) was not updated";
			$response->set_message($message);
		}

		$this->wire('session')->response_codetable = $response;
	}

	/**
	 * Returns CodeTablesResponse based on the outcome of the database save
	 *
	 * @param  string $table  Table Code
	 * @param  string $code   Code being added
	 * @param  bool   $is_new Was the Record in the database before Save?
	 * @param  bool   $saved  Was the Record Saved?
	 * @return CodeTablesResponse
	 */
	protected function save_and_process_response($table, $code, Customer $record) {
		$is_new = $record->isDeleted() ? false : $record->isNew();
		$saved  = $record->isDeleted() ? $record->isDeleted() : $record->save();

		$response = new CodeTablesResponse();
		$response->set_key($code);
		$message = self::DESCRIPTION_RECORD . " ($code) was ";

		if ($saved) {
			$response->set_success(true);
		} else {
			$response->set_error(true);
			$message .= "not ";
		}

		if ($is_new) {
			$message .= 'added';
			$response->set_action(CodeTablesResponse::CRUD_CREATE);
		} elseif ($record->isDeleted()) {
			$message .= 'deleted';
			$response->set_action(CodeTablesResponse::CRUD_DELETE);
		} else {
			$message .= 'updated';
			$response->set_action(CodeTablesResponse::CRUD_UPDATE);
		}

		$response->set_message($message);

		if ($response->has_success()) {
			$this->wire('modules')->get('CodeTables')->update_dplus_cobol($table, $code);
		}

		return $response;
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus CMM Code Table CRUD Manager',
			'version' => 101,
			'summary' => 'Module for CRUD Methods for the CMM code table',
			'singular' => true,
			'autoload' => true,
		);
	}
}
