<?php namespace ProcessWire;

use Purl\Url;

include_once(__DIR__."/MsaResponse.php");

class Msa extends WireData implements Module {

	const CODE_TABLES = array(
		'sysop' => array(
			'code'        		 => 'sysop',
			'module'   			 => 'MsaSysop'
		),
		'lgrp' => array(
			'code'        		 => 'lgrp',
			'module'   			 => 'MsaLgrp'
		),
	);

	public function get_codetables() {
		return self::CODE_TABLES;
	}

	public function validate_codetable($table) {
		return array_key_exists($table, self::CODE_TABLES);
	}

	public function get_codetable_module($table) {
		return $this->wire('modules')->get(self::CODE_TABLES[$table]['module']);
	}

	/**
	 * ProcessWire Installer Function
	 * NOTE: Runs when installed through ProcessWire
	 * @return void
	 */
	public function ___install() {

	}

	/**
	 * ProcessWire removal Function
	 * NOTE: Runs when removed through ProcessWire
	 * @return void
	 */
	public function ___uninstall() {

	}

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');

		foreach ($info['installs'] as $module_name) {
			$modules->install($module_name);
		}
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus MSA Management',
			'version' => 101,
			'summary' => 'Module for MSA Management',
			'singular' => true,
			'autoload' => true,
			'installs' => array(
				'MsaSysop',
				'MsaLgrp',
			)
		);
	}

	/**
	 * Sends Dplus Cobol that Code Table has been Update
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return void
	 */
	public function update_dplus_cobol($table, $code) {
		$config = $this->wire('config');
		$dplusdb = $this->wire('modules')->get('DplusConnectDatabase')->db_name;
		$table = strtoupper($table);
		$data = array("DBNAME=$dplusdb", 'UPDATECODETABLE', "TABLE=$table", "CODE=$code");
		$requestor = $this->wire('modules')->get('DplusRequest');
		$requestor->write_dplusfile($data, session_id());
		$requestor->cgi_request($this->wire('config')->cgis['database'], session_id());
	}
}
