<?php
	require_once('./DplusConnectDatabase.module');

class DplusOnlineDatabase extends DplusConnectDatabase implements ConfigurableModule {
	protected $connection_name = 'dplusodb';

	/**
	 * Returns Config to connect to Database
	 * @return Config
	 */
	public function get_dbconfig() {
		$config = $this->wire('config');
		$dbconfig = parent::get_dbconfig();

		if (!empty($this->db_name)){
			$this->db_name = $this->db_name;
		} else {
			$this->db_name = !empty($config->dplusdbname) ? $config->dplusdbname : "dpluso$config->COMPANYNBR";
		}
		return $dbconfig;
	}

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */

	public static function getModuleInfo() {
		$infoArray = array(
			'title' => __('Dplus Online Database Connection'),
			'version' => 115,
			'summary' => __("Creates Connection to Dplus Online Database"),
			'autoload' => true,
			'singular' => true,
			'author' => 'pauldro',
			'icon' => 'database'
		);
		return $infoArray;
	}
}
