<?php
	require_once('./DplusConnectDatabase.module');
	
	class DplusOnlineDatabase extends DplusConnectDatabase implements ConfigurableModule {
		protected $connection_name = 'dplusodb';

		public static function getModuleInfo() {
			$infoArray = array(
				'title' => __('Dplus Online Database Connection'),
				'version' => 115,
				'summary' => __("Creates Connection to Dplus Online Database"),
				'autoload' => true,
				'singular' => true,
				'author' => 'pauldro',
				'icon' => 'database'
			);
			return $infoArray;
		}

		static public function getDefaultConfig() {
			return array(
				'db_name' => 'dpluso',
				'db_host' => '192.168.1.2',
				'db_user' => 'cptecomm',
				'db_pass' => 'rghopeless',
				'db_port' => '3306',
			);
		}


		/**
		 * Returns Config to connect to Dplus Data Database
		 * @return Config
		 */
		public function get_dbconfig() {
			$config = $this->wire('config');
			$dbname = '';

			if (!empty($this->db_name)){
				$this->db_name = $this->db_name;
			} else {
				$this->db_name = !empty($config->dplusdbname) ? $config->dplusdbname : "dpluso$config->COMPANYNBR";
			}

			$dbconfig = new Config();
			$dbconfig->dbHost = !empty($this->db_host) ? $this->db_host : $config->dbHost;;
			$dbconfig->dbName = $this->db_name;
			$dbconfig->dbUser = !empty($this->db_user) ? $this->db_user : $config->dbUser;
			$dbconfig->dbPass = !empty($this->db_pass) ? $this->db_pass : $config->dbPass;
			$dbconfig->dbPort = !empty($this->db_port) ? $this->db_port : $config->dbport;

			return $dbconfig;
		}
	}
