<?php namespace ProcessWire;

include_once(__DIR__.'/ItmResponse.php');

use Purl\Url;

use ItemPricingQuery, ItemPricing;

/**
 * Module that handles the editing of the UPC item Xref
 */
class ItmPricing extends WireData implements Module {
	const MODEL              = 'ItemPricing';
	const MODEL_KEY          = 'code';
	const DESCRIPTION        = 'Item Master Item Pricing';
	const DESCRIPTION_RECORD = 'Item Master Item Pricing';

	public function __construct() {
		$this->description = self::DESCRIPTION;
	}

	/**
	 * Return if Item Exists
	 * @param  string $itemID Item ID
	 * @return bool
	 */
	public function pricing_exists($itemID) {
		$q = $this->get_query();
		$q->filterByItemid($itemID);
		return boolval($q->count());
	}


	/**
	 * Return ItemPricing
	 * @param  string $itemID Item ID
	 * @return ItemPricing
	 */
	public function get_pricing($itemID) {
		$q = $this->get_query();
		$q->filterByItemid($itemID);
		return $q->findOne();
	}

	/**
	 * Returns ItemPricingQuery
	 * @return ItemPricingQuery
	 */
	public function get_query() {
		return ItemPricingQuery::create();
	}

	/**
	 * Returns ItemPricing after retreiving or creating it
	 * @param  WireInput $input Input Data
	 * @return ItemPricing
	 */
	public function get_create_itempricing(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$itemID = $input->$rm->text('itemID');

		if ($this->wire('modules')->get('Itm')->item_exists($itemID)) {
			$record = $this->get_pricing($itemID);
		} else {
			$record = new ItemPricing();
			$record->setItemid($itemID);
		}
		return $record;
	}

	/**
	 * Takes Input, validates Item Updates the pricing record for it, sends update to DPlus
	 * NOTE: Updates ITM record with changes to the uom_sale, allowdiscount, assortmentcode, assortmentqty fields
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function process_input(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$itemID = $input->$rm->text('itemID');

		$record = $this->get_create_itempricing($input);

		if ($input->$rm->text('action') == 'update-itm-pricing') {
			$record->setBaseprice($input->$rm->text('baseprice'));

			for ($i = 1; $i < ItemPricing::QTY_BREAKS; $i++) {
				$col_qty = ucfirst(ItemPricing::get_pricebreak_qty_column($i));
				$col_price = ucfirst(ItemPricing::get_pricebreak_price_column($i));
				$function_unitqty = "set$col_qty";
				$function_unitprice = "set$col_price";
				$record->$function_unitqty($input->$rm->text("pricebreak_qty$i"));
				$record->$function_unitprice($input->$rm->text("pricebreak_price$i"));
			}
			$saved_itm = $this->update_itm($input);
			$response = $this->save_and_process_response($record);
			$response->set_saved_itm($saved_itm);
			$this->wire('session')->response_itm = $response;
		}
	}
	/**
	 * Updates ITM Item Record and updates DPLUS
	 * Records values for uom_sale, allowdiscount, assortmentcode, assortmentqty
	 * @param  WireInput $input
	 * @return bool was it able to be saved?
	 */
	public function update_itm(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$itemID = $input->$rm->text('itemID');

		$module_itm = $this->wire('modules')->get('Itm');
		$item = $module_itm->get_item($itemID);
		$item->setUom_sale($input->$rm->text('uom_sale'));
		$item->setAllowdiscount($input->$rm->text('allowdiscount'));
		$item->setAssortmentcode($input->$rm->text('assortmentcode'));
		$item->setAssortmentqty($input->$rm->text('assortmentqty'));
		$saved = $item->save();

		if ($saved) {
			$module_itm->update_dplus_cobol($itemID);
		}
		return $saved;
	}

	/**
	 * Returns XrefResponse based on the outcome of the database save
	 * @param  ItemPricing $record Record to record response of database save
	 * @return ItmResponse
	 */
	protected function save_and_process_response(ItemPricing $record) {
		$is_new = $record->isDeleted() ? false : $record->isNew();
		$saved  = $record->isDeleted() ? $record->isDeleted() : $record->save();

		$response = new ItmResponse();
		$response->set_itemID($record->itemid);
		$message = self::DESCRIPTION_RECORD . " ($record->itemid) was ";

		if ($saved) {
			$response->set_success(true);
		} else {
			$response->set_error(true);
			$message .= "not ";
		}

		if ($is_new) {
			$message .= 'added';
			$response->set_action(ItmResponse::CRUD_CREATE);
		} elseif ($record->isDeleted()) {
			$message .= 'deleted';
			$response->set_action(ItmResponse::CRUD_DELETE);
		} else {
			$message .= 'updated';
			$response->set_action(ItmResponse::CRUD_UPDATE);
		}

		$response->set_message($message);
		$response->set_saved_itm_pricing($response->has_success());

		if ($response->has_success()) {
			$this->update_dplus_cobol($record->itemid);
		}
		return $response;
	}

	/**
	 * Writes File for Dplus to update the ITM file for this ITEM
	 * @param  string $itemID Item ID
	 * @return void
	 */
	public function update_dplus_cobol($itemID) {
		$config = $this->wire('config');
		$dplusdb = $this->wire('modules')->get('DplusConnectDatabase')->db_name;
		$data = array("DBNAME=$dplusdb", 'UPDATEITMPRICE', "ITEMID=$itemID");

		$requestor = $this->wire('modules')->get('DplusRequest');
		$requestor->write_dplusfile($data, session_id());
		$requestor->cgi_request($config->cgis['database'], session_id());
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus ITM Pricing CRUD Manager',
			'version' => 101,
			'summary' => 'Module for CRUD Methods for ITM Pricing',
			'singular' => true,
			'autoload' => true,
		);
	}
}
