<?php namespace ProcessWire;
// Purl
use Purl\Url;
// Dplus Model
use ItemMasterItem;
use ItemXrefCustomer;
// Dplus Databases
use Dplus\Databases\Connectors\Dplus as DbDplus;
// Dplus Filters
use Dplus\Filters\Mso\Cxm   as CxmFilter;
use Dplus\Filters\Map\Mxrfe as MxrfeFilter;
use Dplus\Filters\Map\Vxm   as VxmFilter;
use Dplus\Filters\Min\Upcx  as UpcxFilter;
// Dplus Configs
use Dplus\Configs;

/**
 * Module that handles the editing of the ITM item X-refs
 */
class ItmXrefs extends WireData implements Module {
	const MODEL              = 'ItemMasterItem';
	const MODEL_KEY          = 'code';
	const DESCRIPTION        = 'ITM Item';
	const DESCRIPTION_RECORD = 'ITM Item';

	public function __construct() {
		$this->description = self::DESCRIPTION;
		$this->xrefs = new WireData();
		$this->xrefs->upcx = false;
		$this->xrefs->cxm = false;
	}

	public function init2() {
		$this->xrefs->cxm = $modules->get('XrefCxm');
	}

/* =============================================================
	CRUD Proccessing Functions
============================================================= */

	/**
	 * Process CRUD Request call necessary methos
	 * @param  WireInput $input Input Data
	 * @return bool
	 */
	public function processInput(WireInput $input) {
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$itemID = $values->string('itemID');
		$itm = $this->wire('modules')->get('Itm');

		if ($itm->exists($itemID) === false) {
			$itm->setResponse(ItmResponse::response_error($itemID, "Item $itemID does not exist"));
			return false;
		}

		switch ($values->text('action')) {
			case 'update-itm-xrefs':
				return $this->processInputXref($input);
				break;
			default:
				$itm->setResponse(ItmResponse::response_error($itemID, "No Action was specified"));
				return false;
				break;
		}

	}

	private function processInputXref(WireInput $input) {
		$itm = $this('modules')->get('Itm');
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$item = $itm->item($values->string('itemID'));

		if ($item->isNew() === false) {
			$itm->lockrecord($item->itemid);
		}

		if ($itm->recordlocker->userHasLocked($item->itemid) === false) {
			$message = self::DESCRIPTION_RECORD . " ($record->itemid)  was not saved, it is locked by " . $itm->recordlocker->getLockingUser($itemID);
			$response = ItmResponse::response_error($record->itemid, $message);
			return false;
		}

		return $this->inputUpdate($input, $item);
	}

	/**
	 * Update Itm Supercede, then CXM if needed
	 * @param  WireInput      $input Input Data
	 * @param  ItemMasterItem $item  Item Master Item
	 * @return bool
	 */
	private function inputUpdate(WireInput $input, ItemMasterItem $item) {
		$response = $this->inputUpdateSupercede($input, $item);
		$this->wire('session')->setFor('response', 'itm', $response);
		$this->updateCxm($input);
		return $response->has_success();
	}

	/**
	 * Update Itm Supercede
	 * @param  WireInput      $input Input Data
	 * @param  ItemMasterItem $item  Item Master Item
	 * @return ItmResponse
	 */
	private function inputUpdateSupercede(WireInput $input, ItemMasterItem $item) {
		$itm = $this('modules')->get('Itm');
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;

		$configIn  = Configs\In::config();
		$supercede = $configIn->useUppercaseItemid() ? strtoupper($values->text('supercede')) : $values->text('supercede');
		$item->setSupercededby($supercede);
		$item->setDate(date('Ymd'));
		$item->setTime(date('His'));

		if ($itm->exists($values->text('supercede')) || $this->supercede == '') {
			if ($values->text('supercede') == $item->itemid) {
				return ItmResponse::response_error($item->itemid, "Cannot supercede an item back to the same Item ID");
			}
			return $itm->save_and_respond($item);
		}
		return ItmResponse::response_error($item->itemid, "Supercede Item $item->supercede does not exist");
	}

/* =============================================================
	Request Functions
============================================================= */
	/**
	 * Update CXM for short itemid if needed
	 * @param  WireInput $input Input Data
	 * @return bool
	 */
	private function updateCxm(WireInput $input) {
		$cxm = $this->wire('modules')->get('XrefCxm');
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$itemID = $values->string('itemID');
		$shortitemID = $values->text('shortitemID');

		// Delete record if blank
		if (empty($shortitemID)) {
			return $this->deleteShortItmItemid($itemID);
		}

		// CHECK / VALIDATE IF SHORT ITEMID EXISTS
		if ($cxm->xref_shortitem_exists_by_custitemid($values->text('shortitemID'))) {
			$overwrite = $values->bool('overwriteshort');
			$this->overwriteOriginalShortitemid($itemID, $shortitemID, $overwrite);
		}

		$xref = $cxm->new_xref();

		if ($cxm->xref_shortitem_exists($itemID) === false) {
			$xref->setItemid($itemID);
			$xref->setCustid(Configs\Sys::config()->custid);
		}

		if ($cxm->xref_shortitem_exists($itemID)) {
			$xref = $cxm->xref_shortitem($itemID);
		}

		if ($xref->isNew() === false && $shortitemID != $xref->custitemid) {
			$original = $xref;
			$originalValues = $original->toArray();
			$original->delete();
			$xref = new ItemXrefCustomer();
			$xref->fromArray($originalValues);
		}
		$xref->setCustitemid($shortitemID);

		$xref->setDate(date('Ymd'));
		$xref->setTime(date('His'));
		$xref->setDummy('P');
		$saved = $xref->save();

		if (boolval($saved) === false) {
			return false;
		}
		$this->requestUpdateItmShort($itemID, $shortitemID);
	}

	/**
	 * Delete CXM record for Short Item ID
	 * @param  string $itemID Item ID
	 * @return bool
	 */
	private function deleteShortItmItemid($itemID) {
		$cxm = $this->wire('modules')->get('XrefCxm');
		if ($cxm->xref_shortitem_exists($itemID) === false) {
			return true;
		}
		$xref = $cxm->xref_shortitem($itemID);
		$xref->delete();
		$this->requestUpdateItmShort($itemID);
		return true;
	}

	/**
	 * Delete Short Item ID
	 * @param  string $itemID       Item ID
	 * @param  string $shortitemID  Short Item ID
	 * @param  bool   $overwrite    Overwrite ?
	 * @return bool
	 */
	private function overwriteOriginalShortitemid($itemID, $shortitemID, $overwrite = false) {
		if ($overwrite === false) {
			return false;
		}
		$cxm = $this->wire('modules')->get('XrefCxm');
		$original = $cxm->xref_shortitem_by_custitemid($shortitemID);
		$deleted = boolval($original->delete());
		$this->requestUpdateItmShort($original->itemid);
		sleep(3);
		return true;
	}

/* =============================================================
	Dplus Cobol Request Functions
============================================================= */
	private function requestDplus(array $data) {
		$config = $this->wire('config');
		$dplusdb = DbDplus::instance()->dbconfig->dbName;
		$data = array_merge(["DBNAME=$dplusdb"], $data);
		$requestor = $this->wire('modules')->get('DplusRequest');
		$requestor->write_dplusfile($data, session_id());
		$requestor->cgi_request($config->cgis['database'], session_id());
	}

	/**
	 * Writes File for Dplus to update the ITM file for this ITEM
	 * @param  string $itemID Item ID
	 * @return void
	 */
	private function requestUpdateItmShort($itemID, $shortitemID = '') {
		$custID = Configs\Sys::config()->custid;
		$data = ['UPDATESHORTITM', "CUSTID=$custID", "CUSTITEM=$shortitemID", "OURITEM=$itemID"];
		$this->requestDplus($data);
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus ITM XRefs CRUD Manager',
			'version' => 101,
			'summary' => 'Module for CRUD Methods for ITM Xrefs',
			'singular' => true,
			'autoload' => true,
		);
	}
}
