<?php namespace ProcessWire;
// Purl
use Purl\Url;
// Dplus Filters
use Dplus\Filters\Mso\Cxm   as CxmFilter;
use Dplus\Filters\Map\Mxrfe as MxrfeFilter;
use Dplus\Filters\Map\Vxm   as VxmFilter;
use Dplus\Filters\Min\Upcx  as UpcxFilter;

/**
 * Module that handles the editing of the ITM item X-refs
 */
class ItmXrefs extends WireData implements Module {
	const MODEL              = 'ItemMasterItem';
	const MODEL_KEY          = 'code';
	const DESCRIPTION        = 'ITM Item';
	const DESCRIPTION_RECORD = 'ITM Item';

	public function __construct() {
		$this->description = self::DESCRIPTION;
		$this->xrefs = new WireData();
		$this->xrefs->upcx = false;
		$this->xrefs->cxm = false;
	}

	public function init2() {
		$this->xrefs->cxm = $modules->get('XrefCxm');
	}

/* =============================================================
	CRUD Proccessing Functions
============================================================= */
	/**
	 * Takes Input, validates it's for one of the code tables
	 * Processes it, and if updated sends request to dplus
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function process_input(WireInput $input) {
		$itm = $this->wire('modules')->get('Itm');
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$itemID = $values->text('itemID');

		if ($values->action) {
			if ($itm->item_exists($itemID)) {
				if ($values->text('action') == 'update-itm-xrefs') {
					$response = $this->process_input_xref($input);
				}
			} else {
				$response = ItmResponse::response_error($itemID, "Item $itemID does not exist");
			}
		} else {
			$response = ItmResponse::response_error($itemID, "No Action was specified");
		}
		$this->wire('session')->setFor('response', 'itm', $response);
	}

	/**
	 * Takes Input, validates it's for an Item
	 * Updates Item
	 * Processes it, and if updated sends request to dplus
	 *
	 * @param  WireInput $input Input
	 * @return void
	 */
	public function process_input_xref(WireInput $input) {
		$itm = $this('modules')->get('Itm');
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$itemID = strtoupper($values->text('itemID'));
		$record = $itm->get_item($itemID);

		if ($record->isNew() === false) {
			$itm->lockrecord($itemID);
		}

		if ($record->isNew() || $itm->recordlocker->function_locked_by_user($itemID)) {
			if ($values->text('action') == 'update-itm-xrefs') {
				$record->setSupercededby(strtoupper($values->text('supercededby')));

				if (strlen($values->text('supercededby'))) {
					if ($itm->item_exists($values->text('supercededby'))) {
						$response_itm = $itm->save_and_respond($record);
					} else {
						$response_itm = ItmResponse::response_error($record->itemid, "Supercede Item $record->supercededby does not exist");
					}
				}

				$this->send_cxm_update($input);
			} else {
				$message = self::DESCRIPTION_RECORD . " ($record->itemid) was not saved, no action was specified";
				$response_itm = ItmResponse::response_error($record->itemid, $message);
			}
		} else {
			$message = self::DESCRIPTION_RECORD . " ($record->itemid)  was not saved, it is locked by " . $itm->recordlocker->get_locked_user($itemID);
			$response_itm = ItmResponse::response_error($record->itemid, $message);
		}
		return $response_itm;
	}

/* =============================================================
	Request Functions
============================================================= */
	/**
	 * Send Request to Update the Short Item ID using the XrefCxm module
	 * @param  WireInput $input
	 * @return void
	 */
	protected function send_cxm_update(WireInput $input)  {
		$cxm = $this('modules')->get('XrefCxm');
		$rm = strtolower($input->requestMethod());
		$values = $input->$rm;
		$itemID = strtoupper($values->text('itemID'));

		if (!$cxm->xref_shortitem_exists($itemID) || $cxm->xref_shortitem($itemID)->custitemid != $values->text('cxm_custitemid')) {
			$data = array('action' => 'update-cxm-shortitem', 'itemID' => $itemID, 'custitemid' => $values->text('cxm_custitemid'));
			$input_cxm = new WireInput();
			$input_cxm->$rm->setArray($data);
			$cxm->process_input($input_cxm);
		}
	}

/* =============================================================
	URL Functions
============================================================= */
	/**
	 * Return URL to view / edit Item Xrefs
	 * @param  string $itemID
	 * @return string
	 */
	public function get_itm_xrefsURL($itemID) {
		$url = new Url($this->wire('pages')->get("pw_template=itm-xrefs")->url);
		$url->query->set('itemID', $itemID);
		return $url->getUrl();
	}

	/**
	 * Return URL to view / edit Item Xrefs
	 * @param  string $itemID
	 * @return string
	 */
	public function get_itm_xrefs_upcxURL($itemID) {
		$url = new Url($this->wire('pages')->get("pw_template=itm-xrefs-upcx")->url);
		$url->query->set('itemID', $itemID);
		return $url->getUrl();
	}

	/**
	 * Return URL to view / edit UPC for Item
	 * @param  string $itemID Item ID
	 * @param  string $upc    UPC Code
	 * @return string
	 */
	public function get_upcURL($itemID, $upc = '') {
		$url = new Url($this->wire('pages')->get("pw_template=itm-xrefs-upcx")->url);
		$url->query->set('itemID', $itemID);

		if ($upc) {
			$url->query->set('upc', $upc);
		}
		return $url->getUrl();
	}

	public function get_upc_listURL($itemID, $focus = '') {
		$url = new Url($this->wire('pages')->get("pw_template=itm-xrefs-upcx")->url);
		$url->query->set('itemID', $itemID);
		if ($focus == '') {
			return $url->getUrl();
		}
		return $this->get_upc_list_focusURL($itemID, $focus);
	}

	public function get_upc_list_focusURL($itemID, $focus = '') {
		$page = $this->wire('pages')->get("pw_template=itm-xrefs-upcx");
		$upcx = $this->wire('modules')->get('XrefUpc');
		if ($focus == '' || $upcx->xref_exists($focus) === false) {
			return $this->get_upc_listURL($itemID);
		}

		$url = new Url($this->get_upc_listURL($itemID));
		$xref = $upcx->xref($focus);
		$filter = new UpcxFilter();
		$filter->itemid($itemID);
		$offset = $filter->position($xref);
		$pagenbr = ceil($offset / $this->wire('session')->display);
		$url = $this->wire('modules')->get('Dpurl')->paginate($url, $page->name, $pagenbr);
		$url->query->set('focus', $focus);
		return $url->getUrl();
	}

	/**
	 * Return URL to delete UPC for Item
	 * @param  string $itemID Item ID
	 * @param  string $upc    UPC Code
	 * @return string
	 */
	public function get_upc_deleteURL($itemID, $upc) {
		$url = new Url($this->wire('pages')->get("pw_template=itm-xrefs-upcx")->url);
		$url->query->set('action', 'delete-upcx');
		$url->query->set('itemID', $itemID);
		$url->query->set('upc', $upc);
		return $url->getUrl();
	}

	/**
	 * Return URL to view Kit
	 * @param  string  $itemID      Item ID / Kit ID
	 * @return string
	 */
	public function get_kitURL($itemID, $focus = '') {
		$url = new Url($this->wire('pages')->get('pw_template=itm-kit')->url);
		$url->query->set('itemID', $itemID);
		if ($focus) {
			$url->query->set('focus', $focus);
		}
		return $url->getUrl();
	}

	/**
	 * Return URL to view Kit Component
	 * @param  string  $itemID      Item ID / Kit ID
	 * @param  string  $component   Component Item ID
	 * @return string
	 */
	public function get_kit_componentURL($itemID, $component = '') {
		$url = new Url($this->wire('pages')->get('pw_template=itm-kit')->url);
		$url->query->set('itemID', $itemID);
		$url->query->set('component', $component);
		return $url->getUrl();
	}

	/**
	 * Return URL to view Kit Component
	 * @param  string  $itemID      Item ID / Kit ID
	 * @param  string  $component   Component Item ID
	 * @return string
	 */
	public function get_kit_component_deleteURL($itemID, $component) {
		$url = new Url($this->wire('pages')->get('pw_template=itm-kit')->url);
		$url->query->set('action', 'delete-component');
		$url->query->set('itemID', $itemID);
		$url->query->set('kitID', $itemID);
		$url->query->set('component', $component);
		return $url->getUrl();
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus ITM XRefs CRUD Manager',
			'version' => 101,
			'summary' => 'Module for CRUD Methods for ITM Xrefs',
			'singular' => true,
			'autoload' => true,
		);
	}

	/**
	 * Sets up Hook Functions for pages that have itm-xrefs as a parent
	 * @return void
	 */
	public function init() {
		$itm = $this->wire('modules')->get('Itm');
		$templates = implode('|', $itm::TEMPLATES_ITM);

		$this->addHook("Page(pw_template=$templates)::itm_xrefsURL", function($event) {
			$itemID = $event->arguments(0);
			$event->return = $this->get_itm_xrefsURL($itemID);
		});

		$this->add_pagehooks_upcx();
		$this->add_pagehooks_kim();
	}

	public function add_pagehooks_upcx() {
		$itm = $this->wire('modules')->get('Itm');
		$templates = implode('|', $itm::TEMPLATES_ITM);

		$this->addHook("Page(pw_template=$templates)::itm_xrefs_upcxURL", function($event) {
			$itemID = $event->arguments(0);
			$event->return = $this->get_itm_xrefs_upcxURL($itemID);
		});

		$this->addHook("Page(pw_template=$templates)::upc_create_itemidURL", function($event) {
			$itemID = $event->arguments(0);
			$event->return = $this->get_upcURL($itemID, 'new');
		});

		$this->addHook("Page(pw_template=$templates)::upc_deleteURL", function($event) {
			$p = $event->object;
			$upc    = $event->arguments(0);
			$event->return = $this->get_upc_deleteURL($p->itemID, $upc);
		});

		$this->addHook("Page(pw_template=$templates)::upcURL", function($event) {
			$p = $event->object;
			$upc    = $event->arguments(0);
			$event->return = $this->get_upcURL($p->itemID, $upc);
		});

		$this->addHook("Page(pw_template=$templates)::upc_listURL", function($event) {
			$p = $event->object;
			$focus = $event->arguments(0);
			$event->return = $this->get_upc_listURL($p->itemID, $focus);
		});

		$this->addHookProperty('Page(pw_template=itm-xrefs-upcx)::upc', function($event) {
			$p = $event->object;
			$event->return = $p->fullURL->query->get('upc');
		});

		$this->addHookProperty('Page(pw_template=itm-xrefs-upcx)::itemID', function($event) {
			$p = $event->object;
			$event->return = $p->fullURL->query->get('itemID');
		});
	}

	public function add_pagehooks_kim() {
		$itm = $this->wire('modules')->get('Itm');
		$templates = implode('|', $itm::TEMPLATES_ITM);

		$this->addHook("Page(pw_template=$templates)::kitURL", function($event) {
			$itemID = $event->arguments(0);
			$focus  = $event->arguments(1);
			$event->return = $this->get_kitURL($itemID);
		});

		$this->addHook("Page(pw_template=$templates)::kit_exitURL", function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$event->return = $p->itm_xrefsURL($itemID);
		});

		$this->addHook("Page(pw_template=$templates)::kit_componentURL", function($event) {
			$itemID = $event->arguments(0);
			$component = $event->arguments(1);
			$event->return = $this->get_kit_componentURL($itemID, $component);
		});

		$this->addHook("Page(pw_template=$templates)::kit_component_deleteURL", function($event) {
			$itemID = $event->arguments(0);
			$component = $event->arguments(1);
			$event->return = $this->get_kit_component_deleteURL($itemID, $component);
		});
	}
}
