<?php namespace ProcessWire;

/**
 * Mso
 *
 * Parent Module to Install Sub Mso Modules
 */
class Mso extends WireData implements Module {

	public function update() {
		$info = self::getModuleInfo();
		$modules = $this->wire('modules');
		$modules->refresh();

		foreach ($info['installs'] as $module_name) {
			if (!$modules->isInstalled($module_name)) {
				$result = $modules->install($module_name);
			}
		}
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'MSO',
			'version' => 101,
			'summary' => 'Handles Mso Modules Installation & Updates',
			'singular' => true,
			'autoload' => true,
			'installs' => array(
				'SalesOrderEdit',
				'SoControlsSocp',
			)
		);
	}
}
