<?php namespace ProcessWire;

use Purl\Url;

/**
 * class Dpages
 *
 * Installs fields, templates, pages, hooks necessary for Top Menus
 * NOTE: Also installs the basic fields, templates, to build the rest of the Application
 */
class DpagesMar extends Dpages implements Module {
	const FIELDS = array();

	const TEMPLATES = array(
		'ar-code-table' => array(
			'name'   => 'ar-code-table',
			'fields' => array()
		),
		'ar-code-table-ctm' => array(
			'name'   => 'ar-code-table-ctm',
			'fields' => array()
		),
	);

	const PAGES = array(
		'mar' => array(
			'template'       => 'dplus-menu',
			'name'           => 'mar',
			'title'          => 'Accounts Receivable Menu',
			'summary'        => '',
			'parent'         => '/',
			'dplus_function' => 'mar'
		),
		'armain' => array(
			'template'       => 'dplus-menu',
			'pw_template'    => 'ar-code-table-menu',
			'name'           => 'armain',
			'title'          => 'Maintenance',
			'summary'        => 'Accounts Receivable Maintenance',
			'parent'         => '/mar/',
			'dplus_function' => 'armain'
		),
		'ar-ccm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'ccm',
			'title'          => 'Customer Commission Code',
			'summary'        => 'View AR Customer Commission Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'ccm'
		),
		'ar-crtm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'crtm',
			'title'          => 'Customer Route Code',
			'summary'        => 'View AR Customer Route Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'crtm'
		),
		'ar-spgpm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'spgpm',
			'title'          => 'Salesperson Group Code',
			'summary'        => 'View Salesperson Group Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'spgpm'
		),
		'ar-worm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'worm',
			'title'          => 'Customer Write Off Code',
			'summary'        => 'Customer Write Off Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'worm'
		),
		'ar-cpm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'cpm',
			'title'          => 'Customer Price Code',
			'summary'        => 'Customer Price Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'cpm'
		),
		'ar-ctm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'ctm',
			'title'          => 'Customer Type Code',
			'summary'        => 'View Customer Type Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'ctm'
		),
	);

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public function init() {
		/**
		 * Returns Sales Order Page URL
		 */
		$this->addHook('Page(pw_template=ar-code-table-menu|ar-code-table)::get_codetable_viewURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_viewURL($table, $code);
		});

		$this->addHook('Page(pw_template=ar-code-table)::get_codetable_code_deleteURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_code_deleteURL($table, $code);
		});

		$this->addHook('Page(pw_template=ar-code-table)::get_codetable_code_editURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_code_editURL($table, $code);
		});

		$this->addHook('Page(pw_template=ar-code-table)::get_codetable_listURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_listURL($table, $code);
		});

		$this->addHookProperty('Page(pw_template=ar-code-table)::codetable', function($event) {
			$page = $event->object;
			$event->return = $page->name;
		});
	}

	public function get_codetable_viewURL($table, $code = false) {
		$url = new Url($this->wire('pages')->get("pw_template=ar-code-table, name=$table")->url);
		$url->query->set('code', $code);
		return $url->getUrl();
	}

	public function get_codetable_listURL($table, $code = false) {
		$url = new Url($this->wire('pages')->get("pw_template=ar-code-table, name=$table")->url);
		$url->query->set('focus', $code);
		return $url->getUrl();
	}

	public function get_codetable_code_deleteURL($table, $code) {
		$url = new Url($this->wire('pages')->get("pw_template=ar-code-table, name=$table")->url);
		$url->query->set('action', 'remove-code');
		$url->query->set('table', $table);
		$url->query->set('code', $code);
		return $url->getUrl();
	}

	public function get_codetable_code_editURL($table, $code) {
		$url = new Url($this->wire('pages')->get("pw_template=ar-code-table, name=$table")->url);
		$url->query->set('code', $code);
		return $url->getUrl();
	}


	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus AR Pages Modules',
			'version' => 101,
			'summary' => 'Installs and creates AR Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
			'installs' => array(),
		);
	}
}
