<?php namespace ProcessWire;

use Purl\Url;

/**
 * class DpagesMap
 *
 * Installs fields, templates, pages, hooks necessary for the MAP pages
 * NOTE: Also installs the basic fields, templates, to build the rest of the Application
 */
class DpagesMap extends Dpages implements Module {
	const FIELDS = array();

	const TEMPLATES = array(
		'vxm' => array(
			'name'   => 'vxm',
			'fields' => array(),
			'paginated' => true
		),
		'vxm-validate' => array(
			'name'   => 'vxm',
			'fields' => array(),
			'paginated' => true
		),
		'ap-code-table' => array(
			'name'   => 'ap-code-table',
			'fields' => array()
		),
		'ap-code-table-aoptm' => array(
			'name'   => 'ap-code-table-aoptm',
			'fields' => array()
		),
	);

	const PAGES = array(
		'map' => array(
			'template'       => 'dplus-menu',
			'name'           => 'map',
			'title'          => 'Accounts Payable',
			'summary'        => 'Accounts Payable Menu',
			'parent'         => '/',
			'dplus_function' => 'map'
		),
		'apmain' => array(
			'template'       => 'dplus-menu',
			'name'           => 'apmain',
			'title'          => 'Maintenance',
			'summary'        => 'Accounts Payable Maintenance',
			'parent'         => '/map/',
			'dplus_function' => 'apmain'
		),
		'ap-vxm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'vxm',
			'name'           => 'vxm',
			'title'          => 'VXM',
			'summary'        => 'View Vendor Item Xref',
			'parent'         => '/map/apmain/',
			'dplus_function' => 'vxm'
		),
		'ap-vxm-validate' => array(
			'template'       => 'dplus-json',
			'pw_template'    => 'vxm-validate',
			'name'           => 'validate',
			'title'          => 'VXM Validate',
			'summary'        => 'Validate VXM',
			'parent'         => '/map/apmain/vxm/',
			'dplus_function' => ''
		),
		'ap-bum' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ap-code-table',
			'name'           => 'bum',
			'title'          => 'Vendor Buyer',
			'summary'        => 'View / Edit Vendor Buyer',
			'parent'         => '/map/apmain/',
			'dplus_function' => 'bum'
		),
		'ap-vtm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ap-code-table',
			'name'           => 'vtm',
			'title'          => 'Vendor Type Code',
			'summary'        => 'View / Edit Vendor Type Code',
			'parent'         => '/map/apmain/',
			'dplus_function' => 'vtm'
		),
		'ap-aoptm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ap-code-table',
			'name'           => 'aoptm',
			'title'          => 'Accounts Payable Optional Code',
			'summary'        => 'View / Edit Accounts Payable Optional Code',
			'parent'         => '/map/apmain/',
			'dplus_function' => 'aoptm'
		),
	);

/* =============================================================
	URL Functions
============================================================= */
	/**
	 * Return URL for VXM items filtered by Vendor ID
	 * @param  string $vendorID Vendor ID
	 * @return string
	 */
	public function get_vxm_vendorURL($vendorID) {
		$url = new Url($this->wire('pages')->get('pw_template=vxm')->url);
		$url->query->set('vendorID', $vendorID);
		return $url->getUrl();
	}

	/**
	 * Return URL for VXM Item
	 * @param  string $vendorID     Vendor ID
	 * @param  string $vendoritemID Vendor Item ID
	 * @return string
	 */
	public function get_vxm_itemURL($vendorID, $vendoritemID) {
		$url = new Url($this->wire('pages')->get('pw_template=vxm')->url);

		if ($vendorID) {
			$url->query->set('vendorID', $vendorID);
		}

		$url->query->set('vendoritemID', $vendoritemID);
		return $url->getUrl();
	}

	/**
	 * Return URL for VXM ItemID
	 * @param  string $itemID Item ID
	 * @return string
	 */
	public function get_vxm_itemidURL($itemID) {
		$url = new Url($this->wire('pages')->get('pw_template=vxm')->url);

		$url->query->set('itemID', $itemID);
		return $url->getUrl();
	}

	/**
	 * Return URL to Delete VXM Item
	 * @param  string  $itemID       Item ID
	 * @param  string  $vendorID     Vendor ID
	 * @param  string  $vendoritemID Vendor's Item ID
	 * @return string
	 */
	public function get_vxm_item_deleteURL($itemID, $vendorID, $vendoritemID) {
		$url = new Url($this->wire('pages')->get('pw_template=vxm')->url);
		$url->query->set('action', 'remove-vxm-item');
		$url->query->set('itemID', $itemID);

		if ($vendorID) {
			$url->query->set('vendorID', $vendorID);
		}

		$url->query->set('vendoritemID', $vendoritemID);
		return $url->getUrl();
	}

	/**
	 * Return View Code Table URL
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return string
	 */
	public function get_codetable_viewURL($table, $code = '') {
		$url = new Url($this->wire('pages')->get("pw_template=ap-code-table, name=$table")->url);

		if ($table == 'aoptm') {
			$url->query->set('sysop', $code);
		} else {
			$url->query->set('code', $code);
		}
		return $url->getUrl();
	}

	/**
	 * Return View Code Table List URL
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return string
	 */
	public function get_codetable_listURL($table, $code = '') {
		$url = new Url($this->wire('pages')->get("pw_template=ap-code-table, name=$table")->url);
		if ($table == 'aoptm') {
			$url->query->set('sysop', $code);
		} else {
			$url->query->set('focus', $code);
		}
		return $url->getUrl();
	}

	/**
	 * Return Code Table Code Delete URL
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return string
	 */
	public function get_codetable_code_deleteURL($table, $code) {
		$url = new Url($this->wire('pages')->get("pw_template=ap-code-table, name=$table")->url);
		$url->query->set('action', 'remove-code');
		$url->query->set('table', $table);
		$url->query->set('code', $code);
		return $url->getUrl();
	}

	/**
	 * Return Code Table Edit Code URL
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return string
	 */
	public function get_codetable_code_editURL($table, $code) {
		$url = new Url($this->wire('pages')->get("pw_template=ap-code-table, name=$table")->url);
		$url->query->set('code', $code);
		return $url->getUrl();
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus AP Pages Modules',
			'version' => 101,
			'summary' => 'Installs and creates AP Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
			'installs' => array(),
		);
	}

	public function init() {
		$this->addHook("Page(pw_template=vxm)::vxm_itemURL", function($event) {
			$p = $event->object;
			$vendorID = $event->arguments(0);
			$vendoritemID = $event->arguments(1);
			$event->return = $this->get_vxm_itemURL($vendorID, $vendoritemID);
		});

		$this->addHook("Page(pw_template=vxm)::vxm_itemidURL", function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$event->return = $this->get_vxm_itemidURL($itemID);
		});

		$this->addHook('Page(pw_template=vxm)::vxm_vendorURL', function($event) {
			$vendorID = $event->arguments(0);
			$event->return = $this->get_vxm_vendorURL($vendorID);
		});

		$this->addHookProperty('Page(pw_template=vxm)::vendorID', function($event) {
			$p = $event->object;
			$event->return = $p->fullURL->query->get('vendorID');
		});

		$this->addHookProperty('Page(pw_template=vxm)::vendoritemID', function($event) {
			$p = $event->object;
			$event->return = $p->fullURL->query->get('vendoritemID');
		});

		$this->addHookProperty('Page(pw_template=vxm)::itemID', function($event) {
			$p = $event->object;
			$event->return = $p->fullURL->query->get('itemID');
		});

		$this->addHookProperty('Page(pw_template=vxm)::vxm_item_deleteURL', function($event) {
			$p = $event->object;
			$vendorID = $event->arguments(0);
			$vendoritemID = $event->arguments(1);
			$itemID = $p->itemID;
			$event->return = $this->get_vxm_item_deleteURL($itemID, $vendorID, $vendoritemID);
		});

		// Code Tables
		$this->addHook('Page(pw_template=ap-code-table-menu|ap-code-table)::get_codetable_viewURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_viewURL($table, $code);
		});


		$this->addHook('Page(pw_template=ap-code-table)::get_codetable_code_deleteURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_code_deleteURL($table, $code);
		});

		$this->addHook('Page(pw_template=ap-code-table)::get_codetable_code_editURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_code_editURL($table, $code);
		});

		$this->addHook('Page(pw_template=ap-code-table)::get_codetable_listURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_listURL($table, $code);
		});

		$this->addHookProperty('Page(pw_template=ap-code-table)::codetable', function($event) {
			$page = $event->object;
			$event->return = $page->name;
		});
	}
}
