<?php namespace ProcessWire;

use Purl\Url;

/**
 * class DpagesApi
 *
 * Installs fields, templates, pages, hooks necessary for Api Pages
 * api Pages will provide api functionality to the site if not available through other means
 */
class DpagesApi extends Dpages implements Module {
	const FIELDS = array(
		'ajaxcode' => array(
			'name'  => 'ajaxcode',
			'type'  => 'text',
			'label' => 'AJAX Code'
		),
		'ajaxtype' => array(
			'name'  => 'ajaxtype',
			'type'  => 'select',
			'label' => 'AJAX Code',
			'options' => array(
				'lookup' => 'Lookup',
				'json'   => 'JSON',
			)
		),
	);

	const TEMPLATES = array(
		'api-menu' => array(
			'name'   => 'api-menu',
			'fields' => array('dplus_function', 'summary'),
			'paginated' => false
		),
		'api-json' => array(
			'name'   => 'api-json',
			'fields' => array('dplus_function', 'pw_template', 'summary'),
			'paginated' => true
		),
		'api-ajax' => array(
			'name'   => 'api-ajax',
			'fields' => array('ajaxtype', 'ajaxcode', 'pw_template', 'summary'),
			'paginated' => true
		),
		'api-ajax-lookup' => array(
			'name'   => 'api-ajax-lookup',
			'fields' => array(),
			'paginated' => true
		),
	);

	const PAGES = array(
		'api' => array(
			'template'       => 'api-menu',
			'name'           => 'api',
			'title'          => 'API Menu',
			'summary'        => 'API Menu',
			'parent'         => '/',
			'dplus_function' => ''
		),
		'menu-lookup' => array(
			'template'       => 'api-menu',
			'name'           => 'lookup',
			'title'          => 'API Lookup Menu',
			'summary'        => 'API Lookup Menu',
			'parent'         => '/api/',
			'dplus_function' => ''
		),
		'lookup-country-codes' => array(
			'template'       => 'api-ajax',
			'name'           => 'country-codes',
			'title'          => 'Lookup Country Codes',
			'summary'        => 'Lookup Country Codes',
			'parent'         => '/api/lookup/',
			'ajaxtype'       => '',
			'ajaxcode'       => '',
			'pw_template'    => 'lookup-country-codes'
		),
		'lookup-tariff-codes' => array(
			'template'       => 'api-ajax',
			'name'           => 'tariff-codes',
			'title'          => 'Lookup Tariff Codes',
			'summary'        => 'Lookup Tariff Codes',
			'parent'         => '/api/lookup/',
			'ajaxtype'       => 'lookup',
			'ajaxcode'       => 'tariff-codes',
			'pw_template'    => ''
		),
	);

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Online API Pages',
			'version' => 101,
			'summary' => 'Installs and creates Dplus Online API Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
		);
	}
}
