<?php namespace ProcessWire;

use Purl\Url;

/**
 * class DpagesMin
 *
 * Installs fields, templates, pages, hooks necessary for Min Pages
 * Adds Hooks for getting URLs to Min pages
 */
class DpagesMin extends Dpages implements Module {
	const FIELDS = array();

	const TEMPLATES = array(
		'itm' => array(
			'name'   => 'itm',
			'fields' => array()
		),
		'inproc' => array(
			'name'   => 'inproc',
			'fields' => array()
		),
	);

	const PAGES = array(
		'min' => array(
			'template'       => 'dplus-menu',
			'name'           => 'min',
			'title'          => 'Inventory',
			'summary'        => 'Inventory Menu',
			'parent'         => '/',
			'dplus_function' => 'min'
		),
		'inmain' => array(
			'template'       => 'dplus-menu',
			'name'           => 'inmain',
			'title'          => 'Maintenance',
			'summary'        => 'Inventory Maintenance',
			'parent'         => '/min/',
			'dplus_function' => 'inmain'
		),
		'itm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'itm',
			'name'           => 'itm',
			'title'          => 'ITM',
			'summary'        => 'View / Edit Item',
			'parent'         => '/min/inmain/',
			'dplus_function' => 'itm'
		),
		'inproc' => array(
			'template'       => 'dplus-menu',
			'pw_template'    => 'inproc',
			'name'           => 'inproc',
			'title'          => 'Processing',
			'summary'        => 'Processing',
			'parent'         => '/min/',
			'dplus_function' => '' // TODO
		),
	);

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus MIN Pages Modules',
			'version' => 101,
			'summary' => 'Installs and creates MIN Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
			'installs' => array(),
		);
	}
}
