<?php namespace ProcessWire;
use Purl\Url;

/**
 * class DpagesMii
 *
 * Installs fields, templates, pages, hooks necessary for Mii Pages
 * Adds Hooks for getting URLs to Mii pages
 */
class DpagesMii extends Dpages implements Module {
	const REQUIREMENTS_OPTIONS = array(
		"REQ" => "requirements",
		"AVL" => 'available'
	);

	const FIELDS = array(
		'jsoncode' => array(
			'name'  => 'jsoncode',
			'type'  => 'text',
			'label' => 'JSON Datafile Code'
		),
		'is_formattable' => array(
			'name'        => 'is_formattable',
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Is screen formattable?',
			'description' => 'Allow Screen Formatter to be used',
			'notes'       => ""
		),
	);

	const TEMPLATES = array(
		'ii-item' => array(
			'name'   => 'ii-item',
			'fields' => array(),
		),
		'ii-sales-history' => array(
			'name'   => 'ii-sales-history',
			'fields' => array(),
		),
		'iio' => array(
			'name'   => 'iio',
			'fields' => array(),
		)
	);

	const PAGES = array(
		'ii-menu' => array(
			'template'       => 'dplus-menu',
			'name'           => 'mii',
			'title'          => 'Item Information',
			'summary'        => 'Item Information Menu',
			'parent'         => '/',
			'dplus_function' => 'mii'
		),
		'ii-admin' => array(
			'template'       => 'dplus-menu',
			'name'           => 'admin',
			'title'          => 'II Administration',
			'summary'        => 'Item Information Administration',
			'parent'         => '/mii/',
			'dplus_function' => 'iiadmn'
		),
		'iio' => array(
			'template'       => 'dplus-function',
			'name'           => 'iio',
			'title'          => 'II Options',
			'summary'        => 'Item Information Options',
			'parent'         => '/mii/admin/',
			'dplus_function' => 'iio',
			'pw_template'    => 'iio'
		),
		'ii' => array(
			'template'       => 'dplus-function',
			'name'           => 'ii',
			'title'          => 'Item Information',
			'summary'        => 'View Item Information',
			'parent'         => '/mii/',
			'dplus_function' => 'ii',
			'pw_template'    => 'ii-item'
		),
	);

/* =============================================================
	Supplemental Functions
============================================================= */
	/**
	 * Return II Subfunction pages that user has permissions to
	 * @param  User   $user User
	 * @return Pages
	 */
	public function get_ii_user_allowed_functions(User $user) {
		$p = $this->wire('pages')->get('pw_template=ii-item');
		$dplus_functions = array_unique($p->children()->explode('dplus_function'));
		$filtered_functions = $user->filter_functions($dplus_functions);
		return $p->children('dplus_function='.implode('|', $filtered_functions));
	}

	public function get_requirementsoptions() {
		return self::REQUIREMENTS_OPTIONS;
	}

/* =============================================================
	URL Functions
============================================================= */
	/**
	 * Returns URL to II item page
	 * @param  string $itemID Item ID
	 * @return string
	 */
	public function get_ii_itemURL($itemID) {
		$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
		$url->query->set('itemID', $itemID);
		return $url->getUrl();
	}

	/**
	 * Returns URL to II item page
	 * @param  string $itemID Item ID
	 * @return string
	 */
	public function get_ii_loaditemURL($itemID) {
		$url = new Url($this->wire('pages')->get('template=redir, redir_file=ii')->url);
		$url->query->set('action','ii-item');
		$url->query->set('itemID', $itemID);
		return $url->getUrl();
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Online Item Information Pages',
			'version' => 101,
			'summary' => 'Installs and creates Dplus Online Item Information  Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
		);
	}
}
