<?php namespace ProcessWire;

use Purl\Url;

/**
 * class DpagesMvi
 *
 * Installs fields, templates, pages, hooks necessary for Mci Pages
 * Adds Hooks for getting URLs to Mci pages
 */
class DpagesMvi extends Dpages implements Module {
	const FIELDS = array(
		'jsoncode' => array(
			'name'  => 'jsoncode',
			'type'  => 'text',
			'label' => 'JSON Datafile Code'
		),
		'is_formattable' => array(
			'name'        => 'is_formattable',
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Is screen formattable?',
			'description' => 'Allow Screen Formatter to be used',
			'notes'       => ""
		),
	);

	const TEMPLATES = array(
		'dplus-menu' => array(
			'name'   => 'dplus-menu',
			'fields' => array('dplus_function', 'summary'),
			'paginated' => false
		),
		'dplus-function' => array(
			'name'   => 'dplus-function',
			'fields' => array('dplus_function', 'pw_template', 'summary'),
			'paginated' => true
		),
		'vi-function' => array(
			'name'   => 'vi-function',
			'fields' => array('title', 'dplus_function', 'pw_template', 'jsoncode', 'is_formattable', 'summary'),
			'paginated' => true
		),
		'vi-vendor' => array(
			'name'   => 'vi-vendor',
			'fields' => array(),
			'paginated' => true
		),
		'vi-contact' => array(
			'name'   => 'vi-contact',
			'fields' => array(),
			'paginated' => true
		),
		'vi-purchase-orders' => array(
			'name'   => 'vi-purchase-orders',
			'fields' => array(),
			'paginated' => true
		),
		'vi-open-invoices' => array(
			'name'   => 'vi-open-invoices',
			'fields' => array(),
			'paginated' => true
		),
		'vi-unreleased' => array(
			'name'   => 'vi-unreleased',
			'fields' => array(),
			'paginated' => true
		),
		'vi-uninvoiced' => array(
			'name'   => 'vi-uninvoiced',
			'fields' => array(),
			'paginated' => true
		),
		'vi-24monthsummary' => array(
			'name'   => 'vi-24monthsummary',
			'fields' => array(),
			'paginated' => true
		),
		'vi-costing' => array(
			'name'   => 'vi-costing',
			'fields' => array(),
			'paginated' => true
		),
		'vi-sub' => array(
			'name'   => 'vi-sub',
			'fields' => array(),
			'paginated' => true
		),
		'vi-payments' => array(
			'name'   => 'vi-payments',
			'fields' => array(),
			'paginated' => true
		),
		'vi-notes' => array(
			'name'   => 'vi-notes',
			'fields' => array(),
			'paginated' => true
		),
		'vi-documents' => array(
			'name'   => 'vi-documents',
			'fields' => array(),
			'paginated' => true
		),
	);

	const PAGES = array(
		'vendor-menu' => array(
			'template'       => 'dplus-menu',
			'name'           => 'mvi',
			'title'          => 'Vendors',
			'summary'        => 'Vendor Menu',
			'parent'         => '/',
			'dplus_function' => 'mvi'
		),
		'vi-admin' => array(
			'template'       => 'dplus-menu',
			'name'           => 'admin',
			'title'          => 'VI Administration',
			'summary'        => 'Vendor Information Administration',
			'parent'         => '/mvi/',
			'dplus_function' => 'viadmn'
		),
		'vi' => array(
			'template'       => 'dplus-function',
			'name'           => 'vi',
			'title'          => 'Vendor Information',
			'summary'        => 'View Vendor Information',
			'parent'         => '/mvi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-vendor'
		),
		'vi-shipfrom' => array(
			'template'       => 'dplus-function',
			'name'           => 'shipfrom',
			'title'          => 'Shipfroms',
			'summary'        => 'View Vendor Shipfrom Information',
			'parent'         => '/mvi/vi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-shipfrom'
		),
		'vi-contact' => array(
			'template'       => 'dplus-function',
			'name'           => 'contacts',
			'title'          => 'Contacts',
			'summary'        => 'View Vendor Contacts',
			'parent'         => '/mvi/vi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-contact'
		),
		'vi-purchase-orders' => array(
			'template'       => 'vi-function',
			'name'           => 'purchase-orders',
			'title'          => 'Purchase Orders',
			'summary'        => 'View Vendor Purchase Orders',
			'parent'         => '/mvi/vi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-purchase-orders',
			'jsoncode'       => 'vi-purchase-orders'
		),
		'vi-open-invoices' => array(
			'template'       => 'vi-function',
			'name'           => 'open-invoices',
			'title'          => 'Open Invoices',
			'summary'        => 'View Vendor Open Invoices',
			'parent'         => '/mvi/vi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-open-invoices',
			'jsoncode'       => 'vi-openinvoices'
		),
		'vi-purchase-history' => array(
			'template'       => 'vi-function',
			'name'           => 'purchase-history',
			'title'          => 'Purchase History',
			'summary'        => 'View Vendor Purchase History',
			'parent'         => '/mvi/vi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-purchase-history',
			'jsoncode'       => 'vi-purchase-history'
		),
		'vi-unreleased' => array(
			'template'       => 'vi-function',
			'name'           => 'unreleased',
			'title'          => 'Unreleased Purchase Orders',
			'summary'        => 'View Vendor Unreleased',
			'parent'         => '/mvi/vi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-unreleased',
			'jsoncode'       => 'vi-unreleased'
		),
		'vi-uninvoiced' => array(
			'template'       => 'vi-function',
			'name'           => 'uninvoiced',
			'title'          => 'Uninvoiced',
			'summary'        => 'View Vendor Uninvoiced',
			'parent'         => '/mvi/vi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-uninvoiced',
			'jsoncode'       => 'vi-uninvoiced'
		),
		'vi-24monthsummary' => array(
			'template'       => 'vi-function',
			'name'           => '24monthsummary',
			'title'          => '24-month Summary',
			'summary'        => 'View Vendor 24-month Summary',
			'parent'         => '/mvi/vi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-24monthsummary',
			'jsoncode'       => 'vi-24monthsummary'
		),
		'vi-costing' => array(
			'template'       => 'vi-function',
			'name'           => 'costing',
			'title'          => 'Costing',
			'summary'        => 'View Vendor Costing',
			'parent'         => '/mvi/vi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-costing',
			'jsoncode'       => 'vi-costing'
		),
		'vi-sub' => array(
			'template'       => 'vi-function',
			'name'           => 'sub',
			'title'          => 'Substitutions',
			'summary'        => 'View Vendor Substitutions',
			'parent'         => '/mvi/vi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-sub',
			'jsoncode'       => 'vi-sub'
		),
		'vi-payments' => array(
			'template'       => 'vi-function',
			'name'           => 'payments',
			'title'          => 'Payments',
			'summary'        => 'View Vendor Payments',
			'parent'         => '/mvi/vi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-payments',
			'jsoncode'       => 'vi-payments'
		),
		'vi-notes' => array(
			'template'       => 'vi-function',
			'name'           => 'notes',
			'title'          => 'Notes',
			'summary'        => 'View Vendor Notes',
			'parent'         => '/mvi/vi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-notes',
			'jsoncode'       => 'vi-notes'
		),
		'vi-documents' => array(
			'template'       => 'vi-function',
			'name'           => 'documents',
			'title'          => 'Documents',
			'summary'        => 'View Vendor Documents',
			'parent'         => '/mvi/vi/',
			'dplus_function' => '',
			'pw_template'    => 'vi-documents',
			'jsoncode'       => 'vi-documents'
		),
	);

	public function init_vipage() {
		$this->addHook('Page::get_vi_vendorURL', function($event) {
			$vendorID = $event->arguments(0);
			$event->return = $this->get_vi_vendorURL($vendorID);
		});

		$this->addHook('Page::get_vi_vendorshipfromURL', function($event) {
			$vendorID   = $event->arguments(0);
			$shipfromID = $event->arguments(1);
			$event->return = $this->get_vi_vendorshipfromURL($vendorID, $shipfromID);
		});

		$this->addHook('Page(pw_template=vi-vendor)::children_user_allowed', function($event) {
			$user = $this->wire('user');
			$event->return = $this->get_vi_user_allowed_functions($user);
		});

		$this->addHook('Page::url_vendorID', function($event) {
			$p = $event->object;
			$vendorID   = $event->arguments(0);
			$url = new Url($p->url);
			$url->query->set('vendorID', $vendorID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_redirURL', function($event) {
			$p = $event->object;
			$event->return = $this->wire('pages')->get('template=redir, redir_file=vi')->url;
		});

		$this->addHook('Page::get_backURL', function($event) {
			$p = $event->object;
			$vendorID   = $p->fullURL->query->get('vendorID');
			$url = new Url($this->wire('pages')->get('pw_template=vi-vendor')->url);
			$url->query->set('vendorID', $vendorID);

			if ($p->fullURL->query->has('shipfromID') && $p->pw_template != 'vi-shipfrom') {
				$url->path = $this->wire('pages')->get('pw_template=vi-shipfrom')->url;
				$shipfromID = $p->fullURL->query->get('shipfromID');
				$url->query->set('shipfromID', $shipfromID);
			}
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_vipurchaseordersURL', function($event) {
			$p = $event->object;
			$vendorID   = $event->arguments(0);
			$shipfromID = $event->arguments(1);
			$url = new Url($p->get_redirURL());
			$url->query->set('action','vi-purchase-orders');
			$url->query->set('vendorID', $vendorID);
			$url->query->set('shipfromID', $shipfromID);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_vipurchasehistoryURL', function($event) {
			$p = $event->object;
			$vendorID   = $event->arguments(0);
			$shipfromID = $event->arguments(1);
			$date       = $event->arguments(2);
			$url = new Url($p->get_redirURL());
			$url->query->set('action','vi-purchase-history');
			$url->query->set('vendorID', $vendorID);
			$url->query->set('shipfromID', $shipfromID);
			$url->query->set('date', $date);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_viopeninvoicesURL', function($event) {
			$p = $event->object;
			$vendorID   = $event->arguments(0);
			$url = new Url($p->get_redirURL());
			$url->query->set('action','vi-open-invoices');
			$url->query->set('vendorID', $vendorID);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_viunreleasedURL', function($event) {
			$p = $event->object;
			$vendorID   = $event->arguments(0);
			$shipfromID = $event->arguments(1);
			$url = new Url($p->get_redirURL());
			$url->query->set('action','vi-unreleased');
			$url->query->set('vendorID', $vendorID);
			$url->query->set('shipfromID', $shipfromID);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_viuninvoicedURL', function($event) {
			$p = $event->object;
			$vendorID   = $event->arguments(0);
			$url = new Url($p->get_redirURL());
			$url->query->set('action','vi-uninvoiced');
			$url->query->set('vendorID', $vendorID);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_vi24monthsummaryURL', function($event) {
			$p = $event->object;
			$vendorID   = $event->arguments(0);
			$url = new Url($p->get_redirURL());
			$url->query->set('action','vi-24monthsummary');
			$url->query->set('vendorID', $vendorID);
			$url->query->set('date', $date);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_vicostingURL', function($event) {
			$p = $event->object;
			$vendorID   = $event->arguments(0);
			$itemID = $event->arguments(1);
			$url = new Url($this->wire('pages')->get('template=redir, redir_file=vi')->url);
			$url->query->set('action','vi-costing');
			$url->query->set('vendorID', $vendorID);
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page(pw_template=vi-costing)::get_itemURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($p->fullURL->getUrl());
			$url->query->remove('q');
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_visubURL', function($event) {
			$p = $event->object;
			$vendorID   = $event->arguments(0);
			$itemID = $event->arguments(1);
			$url = new Url($this->wire('pages')->get('template=redir, redir_file=vi')->url);
			$url->query->set('action','vi-sub');
			$url->query->set('vendorID', $vendorID);
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page(pw_template=vi-sub)::get_itemURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($p->fullURL->getUrl());
			$url->query->remove('q');
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_vipaymentsURL', function($event) {
			$p = $event->object;
			$vendorID   = $event->arguments(0);
			$url = new Url($p->get_redirURL());
			$url->query->set('action','vi-payments');
			$url->query->set('vendorID', $vendorID);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_vinotesURL', function($event) {
			$p = $event->object;
			$vendorID   = $event->arguments(0);
			$shipfromID = $event->arguments(1);
			$url = new Url($p->get_redirURL());
			$url->query->set('action','vi-notes');
			$url->query->set('vendorID', $vendorID);
			$url->query->set('shipfromID', $shipfromID);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});
	}

	/**
	 * Returns URL to Vendor Page
	 * @param  string $vendorID Vendor ID
	 * @return string           URL
	 */
	public function get_vi_vendorURL($vendorID) {
		$url = new Url($this->wire('pages')->get('pw_template=vi-vendor')->url);
		$url->query->set('vendorID', $vendorID);
		return $url->getUrl();
	}

	/**
	 * Returns URL to Vendor Shipfrom Page
	 * @param  string $vendorID   Vendor ID
	 * @param  string $shipfromID Vendor Shipfrom ID
	 * @return string             URL
	 */
	public function get_vi_vendorshipfromURL($vendorID, $shipfromID) {
		$url = new Url($this->wire('pages')->get('pw_template=vi-shipfrom')->url);
		$url->query->set('vendorID', $vendorID);
		$url->query->set('shipfromID', $shipfromID);
		return $url->getUrl();
	}

	/**
	 * Returns the VI pages the User has access to
	 * @param  User   $user
	 * @return PageArray
	 */
	public function get_vi_user_allowed_functions(User $user) {
		$p = $this->wire('pages')->get('pw_template=vi-vendor');
		$dplus_functions = array_unique($p->children()->explode('dplus_function'));
		$filtered_functions = $user->filter_functions($dplus_functions);
		$this->session->funcs = $filtered_functions;
		return $p->children('dplus_function='.implode('|', $filtered_functions));
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Online Vendor Pages',
			'version' => 101,
			'summary' => 'Installs and creates Dplus Online Vendor Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
		);
	}
}
