<?php namespace ProcessWire;

use Purl\Url;

/**
 * class DpagesMin
 *
 * Installs fields, templates, pages, hooks necessary for Min Pages
 * Adds Hooks for getting URLs to Min pages
 */
class DpagesMin extends Dpages implements Module {
	const FIELDS = array();

	const TEMPLATES = array(
		'upcx' => array(
			'name'   => 'upcx',
			'fields' => array()
		),
		'itm' => array(
			'name'   => 'itm',
			'fields' => array()
		),
		'itm-json' => array(
			'name'   => 'itm-json',
			'fields' => array()
		),
		'itm-search' => array(
			'name'   => 'itm-search',
			'fields' => array()
		),
		'min-itmp' => array(
			'name'   => 'itm-itmp',
			'fields' => array()
		),
		'inproc' => array(
			'name'   => 'inproc',
			'fields' => array()
		),
		'itmimg' => [
			'name'   => 'itmimg',
			'fields' => []
		],
	);

	const PAGES = array(
		'min' => array(
			'template'       => 'dplus-menu',
			'name'           => 'min',
			'title'          => 'Inventory',
			'summary'        => 'Inventory Menu',
			'parent'         => '/',
			'dplus_function' => 'min'
		),
		'inmain' => array(
			'template'       => 'dplus-menu',
			'name'           => 'inmain',
			'title'          => 'Maintenance',
			'summary'        => 'Inventory Maintenance',
			'parent'         => '/min/',
			'dplus_function' => 'inmain'
		),
		'min-upcx' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'upcx',
			'name'           => 'upcx',
			'title'          => 'UPC X-ref',
			'summary'        => 'View / Edit UPCs',
			'parent'         => '/min/inmain/',
			'dplus_function' => 'upcx'
		),
		'min-itmp' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'itmp',
			'name'           => 'itmp',
			'title'          => 'Item Maintenance Permissions',
			'summary'        => 'View / Edit User Item Maintenance Permissions',
			'parent'         => '/min/inmain/',
			'dplus_function' => 'itmp'
		),
		'itm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'itm',
			'name'           => 'itm',
			'title'          => 'ITM',
			'summary'        => 'View / Edit Item',
			'parent'         => '/min/inmain/',
			'dplus_function' => 'itm'
		),
		'itm-json' => array(
			'template'       => 'dplus-json',
			'pw_template'    => 'itm-json',
			'name'           => 'itm',
			'title'          => 'ITM',
			'summary'        => 'View / Edit Item',
			'parent'         => '/min/inmain/itm/',
			'dplus_function' => ''
		),
		'itm-search' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'itm-search',
			'name'           => 'search',
			'title'          => 'Search',
			'summary'        => 'Search ITM Items',
			'parent'         => '/min/inmain/itm/',
			'dplus_function' => ''
		),
		'inproc' => array(
			'template'       => 'dplus-menu',
			'pw_template'    => 'inproc',
			'name'           => 'inproc',
			'title'          => 'Processing',
			'summary'        => 'Processing',
			'parent'         => '/min/',
			'dplus_function' => '' // TODO
		),
		'min-itmimg' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'min-itmimg',
			'name'           => 'itmimg',
			'title'          => 'Item Images',
			'summary'        => 'View / Upload Item Images',
			'parent'         => '/min/inmain/',
			'dplus_function' => ''
		),
	);

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus MIN Pages Modules',
			'version' => 101,
			'summary' => 'Installs and creates MIN Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
			'installs' => array(),
		);
	}
}
