<?php namespace ProcessWire;

use Purl\Url;

/**
 * class Dpages
 *
 * Installs fields, templates, pages, hooks necessary for Top Menus
 * NOTE: Also installs the basic fields, templates, to build the rest of the Application
 */
class DpagesMar extends Dpages implements Module {
	const FIELDS = array();

	const TEMPLATES = array(
		'ar-code-table' => array(
			'name'   => 'ar-code-table',
			'fields' => array()
		),
		'ar-code-table-ctm' => array(
			'name'   => 'ar-code-table-ctm',
			'fields' => array()
		),
		'ar-code-table-cmm' => array(
			'name'   => 'ar-code-table-cmm',
			'fields' => array()
		),
		'ar-code-table-trm' => array(
			'name'   => 'ar-code-table-trm',
			'fields' => array()
		),
		'ar-code-table-crcd' => array(
			'name'   => 'ar-code-table-crcd',
			'fields' => array()
		),
		'ar-code-table-crcd-validate' => array(
			'name'   => 'ar-code-table-crcd-validate',
			'fields' => array()
		),
	);

	const PAGES = array(
		'mar' => array(
			'template'       => 'dplus-menu',
			'name'           => 'mar',
			'title'          => 'Accounts Receivable',
			'summary'        => 'Accounts Receivable Menu',
			'parent'         => '/',
			'dplus_function' => 'mar'
		),
		'armain' => array(
			'template'       => 'dplus-menu',
			'pw_template'    => 'ar-code-table-menu',
			'name'           => 'armain',
			'title'          => 'Maintenance',
			'summary'        => 'Accounts Receivable Maintenance',
			'parent'         => '/mar/',
			'dplus_function' => 'armain'
		),
		'ar-ccm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'ccm',
			'title'          => 'Customer Commission Code',
			'summary'        => 'View / Edit Customer Commission Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'ccm'
		),
		'ar-crtm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'crtm',
			'title'          => 'Customer Route Code',
			'summary'        => 'View / Edit Customer Route Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'crtm'
		),
		'ar-spgpm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'spgpm',
			'title'          => 'Salesperson Group Code',
			'summary'        => 'View / Edit Salesperson Group Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'spgpm'
		),
		'ar-worm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'worm',
			'title'          => 'Customer Write-Off Code',
			'summary'        => 'View / Edit Customer Write-Off Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'worm'
		),
		'ar-cpm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'cpm',
			'title'          => 'Customer Price Code',
			'summary'        => 'View / Edit Customer Price Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'cpm'
		),
		'ar-ctm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'ctm',
			'title'          => 'Customer Type Code',
			'summary'        => 'View / Edit Customer Type Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'ctm'
		),
		'ar-suc' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'suc',
			'title'          => 'Ship-To User Code',
			'summary'        => 'View / Edit Ship-To User Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'suc'
		),
		'ar-sic' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'sic',
			'title'          => 'Standard Industrial Class',
			'summary'        => 'View / Edit Standard Industrial Class',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'sic'
		),
		'ar-cuc' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'cuc',
			'title'          => 'Customer User Code',
			'summary'        => 'View / Edit Customer User Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'cuc'
		),
		'ar-cmm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'cmm',
			'title'          => 'Customer Maintenance',
			'summary'        => 'View / Edit Customer Maintenance',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'cmm'
		),
		'ar-trm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'trm',
			'title'          => 'Customer Terms Code',
			'summary'        => 'View / Edit Customer Terms Code',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'trm'
		),
		'ar-crcd' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ar-code-table',
			'name'           => 'crcd',
			'title'          => 'Customer Credit Card Code',
			'summary'        => 'View / Edit Customer Credit Card',
			'parent'         => '/mar/armain/',
			'dplus_function' => 'crcd'
		),
		'ar-crcd-validate' => array(
			'template'       => 'dplus-json',
			'pw_template'    => 'ar-code-table-crcd-validate',
			'name'           => 'validate',
			'title'          => 'Validate CRCD',
			'summary'        => 'JSON validation for CRCD',
			'parent'         => '/mar/armain/crcd/',
			'dplus_function' => ''
		),
	);

/* =============================================================
	URL Functions
============================================================= */
	/**
	 * Return View Code Table URL
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return string
	 */
	public function get_codetable_viewURL($table, $code = false) {
		$url = new Url($this->wire('pages')->get("pw_template=ar-code-table, name=$table")->url);
		$url->query->set('code', $code);
		return $url->getUrl();
	}

	/**
	 * Return View Code Table List URL
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return string
	 */
	public function get_codetable_listURL($table, $code = '') {
		$url = new Url($this->wire('pages')->get("pw_template=ar-code-table, name=$table")->url);
		$url->query->set('focus', $code);
		return $url->getUrl();
	}

	/**
	 * Return Code Table Code Delete URL
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return string
	 */
	public function get_codetable_code_deleteURL($table, $code) {
		$url = new Url($this->wire('pages')->get("pw_template=ar-code-table, name=$table")->url);
		$url->query->set('action', 'remove-code');
		$url->query->set('table', $table);
		$url->query->set('code', $code);
		return $url->getUrl();
	}

	/**
	 * Return Code Table Edit Code URL
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return string
	 */
	public function get_codetable_code_editURL($table, $code) {
		$url = new Url($this->wire('pages')->get("pw_template=ar-code-table, name=$table")->url);
		$url->query->set('code', $code);
		return $url->getUrl();
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus AR Pages Modules',
			'version' => 101,
			'summary' => 'Installs and creates AR Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
			'installs' => array(),
		);
	}

	public function init() {
		$this->addHook('Page(pw_template=ar-code-table-menu|ar-code-table)::get_codetable_viewURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_viewURL($table, $code);
		});

		$this->addHook('Page(pw_template=ar-code-table)::get_codetable_code_deleteURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_code_deleteURL($table, $code);
		});

		$this->addHook('Page(pw_template=ar-code-table)::get_codetable_code_editURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_code_editURL($table, $code);
		});

		$this->addHook('Page(pw_template=ar-code-table)::get_codetable_listURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_listURL($table, $code);
		});

		$this->addHookProperty('Page(pw_template=ar-code-table)::codetable', function($event) {
			$page = $event->object;
			$event->return = $page->name;
		});
	}
}
