<?php namespace ProcessWire;

use Purl\Url;
use QuoteQuery, Quote;
use LogpermQuery, Logperm;

/**
 * class DpagesMqo
 *
 * Installs fields, templates, pages, hooks necessary for Mqo Pages
 * Adds Hooks for getting URLs to Mqo pages
 */
class DpagesMqo extends Dpages implements Module {
	const FIELDS = array();

	const TEMPLATES = array(
		'quotes' => array(
			'name'   => 'quotes',
			'fields' => array()
		),
		'quote-view' => array(
			'name'   => 'quote-view',
			'fields' => array()
		),
		'quote-order' => array(
			'name'   => 'quote-order',
			'fields' => array()
		),
	);

	const PAGES = array(
		'mqo-menu' => array(
			'template'       => 'dplus-menu',
			'name'           => 'mqo',
			'title'          => 'Quotes',
			'summary'        => 'Quotes Menu',
			'parent'         => '/',
			'dplus_function' => 'mqo'
		),
		'quotes' => array(
			'template'         => 'dplus-function',
			'name'             => 'quotes',
			'title'            => 'Quotes',
			'summary'          => 'View / Search through Quotes',
			'parent'           => '/mqo/',
			'dplus_function'   => '',
			'dplus_permission' => 'mqo',
			'pw_template'      => 'quotes'
		),
		'quote-view' => array(
			'template'         => 'dplus-function',
			'name'             => 'quote',
			'title'            => 'Quote',
			'summary'          => 'View Quote',
			'parent'           => '/mqo/',
			'dplus_function'   => '',
			'dplus_permission' => 'mqo',
			'pw_template'      => 'quote-view'
		),
		'quote-order' => array(
			'template'       => 'dplus-function',
			'name'           => 'order',
			'title'          => 'Push Quote to Order',
			'summary'        => 'Push Quote to Order',
			'parent'         => '/mqo/quote/',
			'dplus_function' => 'eqo',
			'pw_template'    => 'quote-order'
		),
	);

	public function init_mqopage() {
		// $this->addHook('Page::get_redirURL', function($event) {
		// 	$p = $event->object;
		// 	$event->return = $p->parent('template=dplus-menu')->child('template=redir')->url;
		// });
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Online Quote Pages',
			'version' => 101,
			'summary' => 'Installs and creates Dplus Online Quote Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
		);
	}

}
