<?php namespace ProcessWire;

use Purl\Url;

/**
 * class DpagesMvi
 *
 * Installs fields, templates, pages, hooks necessary for Mvi Pages
 * Adds Hooks for getting URLs to Mvi pages
 */
class DpagesMvi extends Dpages implements Module {
	const FIELDS = array(
		'jsoncode' => array(
			'name'  => 'jsoncode',
			'type'  => 'text',
			'label' => 'JSON Datafile Code'
		),
		'is_formattable' => array(
			'name'        => 'is_formattable',
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Is screen formattable?',
			'description' => 'Allow Screen Formatter to be used',
			'notes'       => ""
		),
	);

	const TEMPLATES = array(
		'dplus-menu' => array(
			'name'   => 'dplus-menu',
			'fields' => array('dplus_function', 'summary'),
			'paginated' => false
		),
		'dplus-function' => array(
			'name'   => 'dplus-function',
			'fields' => array('dplus_function', 'pw_template', 'summary'),
			'paginated' => true
		),
	);

	const PAGES = array(
		'vendor-menu' => array(
			'template'       => 'dplus-menu',
			'name'           => 'mvi',
			'title'          => 'Vendors',
			'summary'        => 'Vendor Menu',
			'parent'         => '/',
			'dplus_function' => 'mvi'
		),
		'vi-admin' => array(
			'template'       => 'dplus-menu',
			'name'           => 'admin',
			'title'          => 'VI Administration',
			'summary'        => 'Vendor Information Administration',
			'parent'         => '/mvi/',
			'dplus_function' => 'viadmn'
		),
		'vi' => array(
			'template'       => 'dplus-function',
			'name'           => 'vi',
			'title'          => 'Vendor Information',
			'summary'        => 'View Vendor Information',
			'parent'         => '/mvi/',
			'dplus_function' => 'vi',
			'pw_template'    => 'vi'
		),
	);

/* =============================================================
	URL Functions
============================================================= */

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus MVI Pages',
			'version' => 101,
			'summary' => 'Installs and creates Dplus MVI Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
		);
	}
}
