<?php namespace ProcessWire;

use Purl\Url;

/**
 * class DpagesMci
 *
 * Installs fields, templates, pages, hooks necessary for Mci Pages
 * Adds Hooks for getting URLs to Mci pages
 */
class DpagesMci extends Dpages implements Module {
	const FIELDS = array(
		'jsoncode' => array(
			'name'  => 'jsoncode',
			'type'  => 'text',
			'label' => 'JSON Datafile Code'
		),
		'is_formattable' => array(
			'name'        => 'is_formattable',
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Is screen formattable?',
			'description' => 'Allow Screen Formatter to be used',
			'notes'       => ""
		),
	);

	const TEMPLATES = array(
		'ci' => array(
			'name'   => 'ci',
			'fields' => array(),
		),
		'ci-customer-phonebook' => array(
			'name'   => 'ci-customer-phonebook',
			'fields' => array(),
		),
		'mci-lookup' => array(
			'name'   => 'mci-lookup',
			'fields' => array(),
		),
		'cio' => array(
			'name'   => 'cio',
			'fields' => array(),
		),
	);

	const PAGES = array(
		'customer-menu' => array(
			'template'       => 'dplus-menu',
			'name'           => 'mci',
			'title'          => 'Customers',
			'summary'        => 'Customer Menu',
			'parent'         => '/',
			'dplus_function' => 'mci'
		),
		'ci-admin' => array(
			'template'       => 'dplus-menu',
			'name'           => 'admin',
			'title'          => 'CI Administration',
			'summary'        => 'Customer Information Administration',
			'parent'         => '/mci/',
			'dplus_function' => 'ciadmn'
		),
		'cio' => array(
			'template'       => 'dplus-function',
			'name'           => 'cio',
			'title'          => 'CI Options',
			'summary'        => 'Customer Information Options',
			'parent'         => '/mci/admin/',
			'dplus_function' => 'cio',
			'pw_template'    => 'cio'
		),
		'mci-lookup' => array(
			'template'       => 'dplus-function',
			'name'           => 'lookup',
			'title'          => 'Customer Lookup',
			'summary'        => 'Lookup Customers',
			'parent'         => '/mci/',
			'dplus_function' => '',
			'pw_template'    => 'mci-lookup'
		),
		'ci' => array(
			'template'       => 'dplus-function',
			'name'           => 'ci',
			'title'          => 'Customer Information',
			'summary'        => 'View Customer Information',
			'parent'         => '/mci/',
			'dplus_function' => 'ci',
			'pw_template'    => 'ci'
		),
		'ci-customer-phonebook' => array(
			'template'       => 'dplus-function',
			'name'           => 'phonebook',
			'title'          => 'Phonebook',
			'summary'        => 'View Customer Phonebook',
			'parent'         => '/mci/ci/',
			'dplus_function' => 'ci-gen',
			'pw_template'    => 'ci-customer-phonebook'
		),
	);


/* =============================================================
	URL Functions
============================================================= */
	/**
	 * Returns URL to CI Customer Page
	 * @param  string $custID Customer ID
	 * @return string
	 */
	public function get_ci_customerURL($custID) {
		$url = new Url($this->wire('pages')->get('pw_template=ci')->url);
		$url->query->set('custID', $custID);
		return $url->getUrl();
	}

	/**
	 * Returns URL to CI Customer Shipto Page
	 * @param  string $custID   Customer ID
	 * @param  string $shiptoID Customer Shipto ID
	 * @return string
	 */
	public function get_ci_customershiptoURL($custID, $shiptoID) {
		$url = new Url($this->wire('pages')->get('pw_template=ci')->url);
		$url->path->add('ship-tos');
		$url->query->set('custID', $custID);
		$url->query->set('shiptoID', $shiptoID);
		return $url->getUrl();
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus MCI Pages',
			'version' => 101,
			'summary' => 'Installs and creates Dplus MCI Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
		);
	}
}
