<?php namespace ProcessWire;

use Purl\Url;
use SalesOrder, SalesOrderQuery;
use SalesHistory, SalesHistoryQuery;

/**
 * class DpagesMso
 *
 * Installs fields, templates, pages, hooks necessary for Mso Pages
 * Adds Hooks for getting URLs to Mso pages
 * Adds Hooks for Sales Order Editing Access
 */
class DpagesMso extends Dpages implements Module {
	const FIELDS = array();

	const TEMPLATES = array(
		'sales-orders' => array(
			'name'   => 'sales-orders',
			'fields' => array()
		),
		'sales-history-orders' => array(
			'name'   => 'sales-history-orders',
			'fields' => array()
		),
		'sales-orders-customer' => array(
			'name'   => 'sales-orders-customer',
			'fields' => array()
		),
		'sales-history-orders-customer' => array(
			'name'   => 'sales-history-orders-customer',
			'fields' => array()
		),
		'sales-order-view' => array(
			'name'   => 'sales-order-view',
			'fields' => array()
		),
		'sales-order-print' => array(
			'name'   => 'sales-order-print',
			'fields' => array()
		),
		'sales-order-edit' => array(
			'name'   => 'sales-order-edit',
			'fields' => array()
		),
		'sales-order-documents' => array(
			'name'   => 'sales-order-documents',
			'fields' => array()
		),
		'sales-order-notes' => array(
			'name'   => 'sales-order-notes',
			'fields' => array()
		),
		'so-code-table' => array(
			'name'   => 'so-code-table',
			'fields' => array()
		),
		'so-code-table-soptm' => array(
			'name'   => 'so-code-table-soptm',
			'fields' => array()
		),
		'so-code-table-code' => array(
			'name'   => 'so-code-table-code',
			'fields' => array()
		),
		'cxm' => array(
			'name'   => 'cxm',
			'fields' => array()
		),
	);

	const PAGES = array(
		'mso' => array(
			'template'       => 'dplus-menu',
			'name'           => 'mso',
			'title'          => 'Sales Orders',
			'summary'        => 'Sales Order Menu',
			'parent'         => '/',
			'dplus_function' => 'mso'
		),
		'somain' => array(
			'template'       => 'dplus-menu',
			'name'           => 'somain',
			'title'          => 'Maintenance',
			'summary'        => 'Sales Order Maintenance',
			'parent'         => '/mso/',
			'dplus_function' => 'somain'
		),
		'so-lsm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'so-code-table',
			'name'           => 'lsm',
			'title'          => 'Lost Sales Reason Code',
			'summary'        => 'View / Edit Lost Sales Reason Code',
			'parent'         => '/mso/somain/',
			'dplus_function' => 'lsm'
		),
		'so-mfcm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'so-code-table',
			'name'           => 'mfcm',
			'title'          => 'Motor Freight Code',
			'summary'        => 'View / Edit Motor Freight Code',
			'parent'         => '/mso/somain/',
			'dplus_function' => 'mfcm'
		),
		'so-rgarc' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'so-code-table',
			'name'           => 'rgarc',
			'title'          => 'RGA/Return Reason Code',
			'summary'        => 'View / Edit RGA/Return Reason Code',
			'parent'         => '/mso/somain/',
			'dplus_function' => 'rgarc'
		),
		'so-rgasc' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'so-code-table',
			'name'           => 'rgasc',
			'title'          => 'RGA/Return Ship Via Code',
			'summary'        => 'View / Edit RGA/Return Ship Via Code',
			'parent'         => '/mso/somain/',
			'dplus_function' => 'rgasc'
		),
		'so-soptm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'so-code-table',
			'name'           => 'soptm',
			'title'          => 'Sales Order Optional Code',
			'summary'        => 'View / Edit Sales Order Optional Code',
			'parent'         => '/mso/somain/',
			'dplus_function' => 'soptm'
		),
		'cxm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'cxm',
			'name'           => 'cxm',
			'title'          => 'Customer Item X-Reference',
			'summary'        => 'View / Edit Customer Item X-Ref',
			'parent'         => '/mso/somain/',
			'dplus_function' => 'cxm'
		),
		'sales-orders' => array(
			'template'         => 'dplus-function',
			'name'             => 'sales-orders',
			'title'            => 'Sales Orders',
			'summary'          => 'View / Search through Open Orders',
			'parent'           => '/mso/',
			'dplus_function'   => '',
			'dplus_permission' => 'mso',
			'pw_template'      => 'sales-orders'
		),
		'sales-orders-customer' => array(
			'template'         => 'dplus-function',
			'name'             => 'customer',
			'title'            => 'Customer Sales Orders',
			'summary'          => 'View / Search through Open Orders for a Customer',
			'parent'           => '/mso/sales-orders/',
			'dplus_function'   => '',
			'dplus_permission' => 'mso',
			'pw_template'      => 'sales-orders-customer'
		),
		'sales-order' => array(
			'template'         => 'dplus-function',
			'name'             => 'sales-order',
			'title'            => 'Sales Order',
			'summary'          => 'View Sales Order',
			'parent'           => '/mso/',
			'dplus_function'   => '',
			'dplus_permission' => 'mso',
			'pw_template'      => 'sales-order-view'
		),
		'sales-order-print' => array(
			'template'         => 'dplus-function',
			'name'             => 'print',
			'title'            => 'Print Sales Order',
			'summary'          => 'Print Sales Order',
			'parent'           => '/mso/sales-order/',
			'dplus_function'   => '',
			'dplus_permission' => 'mso',
			'pw_template'      => 'sales-order-print'
		),
		'sales-order-edit' => array(
			'template'       => 'dplus-function',
			'name'           => 'edit',
			'title'          => 'Edit Sales Order',
			'summary'        => 'Edit Sales Order',
			'parent'         => '/mso/sales-order/',
			'dplus_function' => 'eso',
			'pw_template'    => 'sales-order-edit'
		),
		'sales-order-documents' => array(
			'template'         => 'dplus-function',
			'name'             => 'documents',
			'title'            => 'Sales Order Documents',
			'summary'          => 'View Sales Order Documents',
			'parent'           => '/mso/sales-order/',
			'dplus_function'   => '',
			'dplus_permission' => 'mso',
			'pw_template'      => 'sales-order-documents'
		),
		'sales-order-notes' => array(
			'template'         => 'dplus-function',
			'name'             => 'notes',
			'title'            => 'Sales Order Notes',
			'summary'          => 'View Sales Order Notes',
			'parent'           => '/mso/sales-order/',
			'dplus_function'   => '',
			'dplus_permission' => 'mso',
			'pw_template'      => 'sales-order-notes'
		),
		'sales-history' => array(
			'template'         => 'dplus-function',
			'name'             => 'sales-history',
			'title'            => 'Sales History',
			'summary'          => 'View Sales History Orders',
			'parent'           => '/mso/',
			'dplus_function'   => '',
			'dplus_permission' => 'mso',
			'pw_template'      => 'sales-history-orders'
		),
		'sales-history-customer' => array(
			'template'         => 'dplus-function',
			'name'             => 'customer',
			'title'            => 'Customer Sales History',
			'summary'          => 'View Sales History Orders for a Customer',
			'parent'           => '/mso/sales-history/',
			'dplus_function'   => '',
			'dplus_permission' => 'mso',
			'pw_template'      => 'sales-history-orders-customer'
		),
	);

	public function init_salesorder_hooks() {

		$this->addHook('Page::view_notesURL', function($event) {
			$p = $event->object;
			$ordn = $event->arguments(0);
			$linenbr = $event->arguments(1);
			$url = new Url($this->wire('pages')->get('pw_template=sales-order-notes')->url);
			$url->query->set('ordn', $ordn);
			$hash = $linenbr > 0 ? "#line-$linenbr" : '';
			$event->return = $url->getUrl()."$hash";
		});

		$this->addHook('Page::edit_orderURL', function($event) {
			$p = $event->object;
			$ordn = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=sales-order-edit')->url);
			$url->query->set('ordn', $ordn);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::view_orderURL', function($event) {
			$ordn = $event->arguments(0);
			$event->return = $this->get_salesorder_viewURL($ordn);
		});

		$this->addHook('Page::unlock_orderURL', function($event) {
			$ordn = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('template=dplus-menu,name=mso')->child('template=redir')->url);
			$url->query->set('action', 'unlock-order');
			$url->query->set('ordn', $ordn);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::ii_itemURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$event->return = $this->wire('modules')->get('DpagesMii')->get_ii_itemURL($itemID);
		});

		$this->addHook('Page::ci_customerURL', function($event) {
			$p = $event->object;
			$custID = $event->arguments(0);
			$event->return = $this->wire('modules')->get('DpagesMci')->get_ci_customerURL($custID);
		});

		$this->addHook('Page::ci_customershiptoURL', function($event) {
			$p = $event->object;
			$custID = $event->arguments(0);
			$shiptoID = $event->arguments(1);
			$event->return = $this->wire('modules')->get('DpagesMci')->get_ci_customershiptoURL($custID, $shiptoID);
		});
	}

	public function init_cxm_hooks() {
		$this->addHook("Page(pw_template=cxm)::cxmURL", function($event) {
			$p = $event->object;
			$custID = $event->arguments(0);
			$event->return = $this->get_cxmURL($custID);
		});

		$this->addHook("Page(pw_template=cxm)::cxm_itemURL", function($event) {
			$p = $event->object;
			$custID = $event->arguments(0);
			$custitemID = $event->arguments(1);
			$event->return = $this->get_cxm_itemURL($custID, $custitemID);
		});

		$this->addHook("Page(pw_template=cxm)::cxm_itemIDURL", function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$event->return = $this->get_cxm_itemIDURL($itemID);
		});

		$this->addHook("Page(pw_template=cxm)::cxm_item_newURL", function($event) {
			$p = $event->object;
			$custID = $event->arguments(0);
			$event->return = $this->get_cxm_itemURL($custID,'new');
		});

		$this->addHook('Page(pw_template=cxm)::cxm_customerURL', function($event) {
			$custID = $event->arguments(0);
			$key = $event->arguments(1);
			$event->return = $this->get_cxm_customerURL($custID, $key);
		});

		$this->addHookProperty('Page(pw_template=cxm)::custID', function($event) {
			$p = $event->object;
			$custID = $p->fullURL->query->get('custID') ? $p->fullURL->query->get('custID') : '';
			$event->return = $custID;
		});

		$this->addHookProperty('Page(pw_template=cxm)::custitemID', function($event) {
			$p = $event->object;
			$event->return = $p->fullURL->query->get('custitemID');
		});

		$this->addHookProperty('Page(pw_template=cxm)::itemID', function($event) {
			$p = $event->object;
			$event->return = $p->fullURL->query->get('itemID');
		});

		$this->addHook('Page(pw_template=cxm)::cxm_item_deleteURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$custID = $event->arguments(1);
			$custitemID = $event->arguments(2);

			$event->return = $this->get_cxm_item_deleteURL($itemID, $custID, $custitemID);
		});

		$this->addHook('Page(pw_template=cxm)::cxm_item_exitURL', function($event) {
			$item = $event->arguments(0);
			$custID = $item->custid;
			$custitemID = $item->custitemid;
			$cxm = $this->wire('modules')->get('XrefCxm');
			$event->return = $this->get_cxm_customerURL($custID, $cxm->get_recordlocker_key($item));
		});
	}

/* =============================================================
	URL Functions
============================================================= */

	/**
	 * Return Paginated URL to CXM Item Page
	 * @param  string $custID Customer ID to focus / highlight
	 * @return string
	 */
	public function get_cxmURL($custID = '') {
		$page = $this->wire('pages')->get('pw_template=cxm');
		$url = new Url($page->url);

		$cxm = $this->wire('modules')->get('XrefCxm');
		$filter = $this->wire('modules')->get('FilterCustomers');

		if ($filter->exists($custID)) {
			$url->query->set('focus', $custID);
			$filter->custid($cxm->custids());
			$position = $filter->position($custID);
			$pagenbr = ceil($position / ($this->wire('session')->display - 1));
			$url = $this->wire('modules')->get('Dpurl')->paginate($url, $page->name, $pagenbr);
		}
		return $url->getUrl();
	}
	/**
	 * Return URL for CXM items filtered by Customer ID
	 * @param  string $custID Customer ID
	 * @return string
	 */
	public function get_cxm_customerURL($custID, $focus = '') {
		$url = new Url($this->wire('pages')->get('pw_template=cxm')->url);
		$url->query->set('custID', $custID);
		if ($focus) {
			return $this->get_cxm_customer_focusURL($custID, $focus);
		}
		return $url->getUrl();
	}

	/**
	 * Return Paginated URL to CXM Item Page
	 * @param  string $itemID Item ID
	 * @param  string $focus  Record Locker Key for Item
	 * @return string
	 */
	public function get_cxm_customer_focusURL($custID, $focus) {
		$page = $this->wire('pages')->get('pw_template=cxm');
		$url = new Url($page->url);
		$url->query->set('custID', $custID);

		if ($this->wire('session')->response_xref) {
			if ($this->wire('session')->response_xref->key != $focus) {
				$url->query->set('focus', $focus);
			}
		} else {
			$url->query->set('focus', $focus);
		}

		$cxm = $this->wire('modules')->get('XrefCxm');
		$item = $cxm->xref_by_recordlocker_key($focus);

		if ($item) {
			$filter = $this->wire('modules')->get('FilterXrefItemCxm');
			$filter->custid($custID);
			$position = $filter->position($item);
			$pagenbr = ceil($position / ($this->wire('session')->display - 1));
			$url = $this->wire('modules')->get('Dpurl')->paginate($url, $page->name, $pagenbr);
		}
		return $url->getUrl();
	}

	/**
	 * Return URL for CXM items filtered by Item ID
	 * @param  string $itemID Item ID
	 * @return string
	 */
	public function get_cxm_itemIDURL($itemID) {
		$url = new Url($this->wire('pages')->get('pw_template=cxm')->url);
		$url->query->set('itemID', $itemID);
		return $url->getUrl();
	}

	/**
	 * Return URL for CXM Item
	 * @param  string $custID     Vendor ID
	 * @param  string $custitemID Vendor Item ID
	 * @return string
	 */
	public function get_cxm_itemURL($custID, $custitemID) {
		$url = new Url($this->wire('pages')->get('pw_template=cxm')->url);

		if ($custID) {
			$url->query->set('custID', $custID);
		}

		$url->query->set('custitemID', $custitemID);
		return $url->getUrl();
	}

	/**
	 * Return URL to Delete CXM Item
	 * @param  string  $itemID     Item ID
	 * @param  string  $custID     Vendor ID
	 * @param  string  $custitemID Vendor's Item ID
	 * @return string
	 */
	public function get_cxm_item_deleteURL($itemID, $custID, $custitemID) {
		$url = new Url($this->wire('pages')->get('pw_template=cxm')->url);
		$url->query->set('action', 'delete-cxm-item');
		$url->query->set('itemID', $itemID);

		if ($custID) {
			$url->query->set('custID', $custID);
		}

		$url->query->set('custitemID', $custitemID);
		return $url->getUrl();
	}

	/**
	 * Returns URL to view Sales Order
	 * @param  string $ordn Sales Order Number
	 * @return string
	 */
	public function get_salesorder_viewURL($ordn) {
		$url = new Url($this->wire('pages')->get('pw_template=sales-order-view')->url);
		$url->query->set('ordn', $ordn);
		return $url->getUrl();
	}

	/**
	 * Return View Code Table URL
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return string
	 */
	public function get_codetable_viewURL($table, $code = '') {
		$url = new Url($this->wire('pages')->get("pw_template=so-code-table, name=$table")->url);

		if ($table == 'soptm') {
			$url->query->set('sysop', $code);
		} else {
			$url->query->set('code', $code);
		}
		return $url->getUrl();
	}

	/**
	 * Return View Code Table List URL
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return string
	 */
	public function get_codetable_listURL($table, $code = '') {
		$url = new Url($this->wire('pages')->get("pw_template=so-code-table, name=$table")->url);
		$code = str_replace(' ', '-', $code);
		if ($table == 'soptm') {
			$url->query->set('sysop', $code);
		} else {
			$url->query->set('socus', $code);
		}
		return $url->getUrl();
	}

	/**
	 * Return Code Table Code Delete URL
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return string
	 */
	public function get_codetable_code_deleteURL($table, $code) {
		$url = new Url($this->wire('pages')->get("pw_template=so-code-table, name=$table")->url);
		$url->query->set('action', 'remove-code');
		$url->query->set('table', $table);
		$url->query->set('code', $code);
		return $url->getUrl();
	}

	/**
	 * Return Code Table Edit Code URL
	 * @param  string $table Code Table
	 * @param  string $code  Code
	 * @return string
	 */
	public function get_codetable_code_editURL($table, $code) {
		$url = new Url($this->wire('pages')->get("pw_template=so-code-table, name=$table")->url);
		$url->query->set('code', $code);
		return $url->getUrl();
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso MSO Pages',
			'version' => 101,
			'summary' => 'Installs and creates Dplus MSO Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
		);
	}

	public function init() {
		/**
		 * Returns Sales Order Page URL
		 */
		$this->addHook('Page(pw_template=so-code-table-menu|so-code-table)::get_codetable_viewURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_viewURL($table, $code);
		});

		$this->addHook('Page(pw_template=so-code-table)::get_codetable_code_deleteURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_code_deleteURL($table, $code);
		});

		$this->addHook('Page(pw_template=so-code-table)::get_codetable_code_editURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_code_editURL($table, $code);
		});

		$this->addHook('Page(pw_template=so-code-table)::get_codetable_listURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_listURL($table, $code);
		});

		$this->addHookProperty('Page(pw_template=so-code-table)::codetable', function($event) {
			$page = $event->object;
			$event->return = $page->name;
		});
	}
}
