<?php namespace ProcessWire;

use Purl\Url;

/**
 * class DpagesMap
 *
 * Installs fields, templates, pages, hooks necessary for the MAP pages
 * NOTE: Also installs the basic fields, templates, to build the rest of the Application
 */
class DpagesMap extends Dpages implements Module {
	const FIELDS = array();

	const TEMPLATES = array(
		'vxm' => array(
			'name'   => 'vxm',
			'fields' => array(),
			'paginated' => true
		),
		'ap-code-table' => array(
			'name'   => 'ap-code-table',
			'fields' => array()
		),
		'ap-code-table-aoptm' => array(
			'name'   => 'ap-code-table-aoptm',
			'fields' => array()
		),
	);

	const PAGES = array(
		'map' => array(
			'template'       => 'dplus-menu',
			'name'           => 'map',
			'title'          => 'Accounts Payable',
			'summary'        => 'Accounts Payable Menu',
			'parent'         => '/',
			'dplus_function' => 'map'
		),
		'apmain' => array(
			'template'       => 'dplus-menu',
			'name'           => 'apmain',
			'title'          => 'Maintenance',
			'summary'        => 'Accounts Payable Maintenance',
			'parent'         => '/map/',
			'dplus_function' => 'apmain'
		),
		'ap-vxm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'vxm',
			'name'           => 'vxm',
			'title'          => 'VXM',
			'summary'        => 'View Vendor Item Xref',
			'parent'         => '/map/apmain/',
			'dplus_function' => ''
		),
		'ap-vxm-validate' => array(
			'template'       => 'dplus-json',
			'pw_template'    => 'vxm-validate',
			'name'           => 'validate',
			'title'          => 'VXM Validate',
			'summary'        => 'Validate VXM',
			'parent'         => '/map/apmain/vxm/',
			'dplus_function' => ''
		),
		'ap-bum' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ap-code-table',
			'name'           => 'bum',
			'title'          => 'Vendor Buyer',
			'summary'        => 'View / Edit Vendor Buyer',
			'parent'         => '/map/apmain/',
			'dplus_function' => 'bum'
		),
		'ap-vtm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ap-code-table',
			'name'           => 'vtm',
			'title'          => 'Vendor Type Code',
			'summary'        => 'View / Edit Vendor Type Code',
			'parent'         => '/map/apmain/',
			'dplus_function' => 'vtm'
		),
		'ap-aoptm' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'ap-code-table',
			'name'           => 'aoptm',
			'title'          => 'Accounts Payable Optional Code',
			'summary'        => 'View / Edit Accounts Payable Optional Code',
			'parent'         => '/map/apmain/',
			'dplus_function' => 'aoptm'
		),
	);

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public function init() {
		/**
		 * Returns Sales Order Page URL
		 */
		$this->addHook('Pages::vxm_vendorURL', function($event) {
			$vendorID = $event->arguments(0);
			$event->return = $this->get_vxm_vendorURL($vendorID);
		});

		/**
		 * Returns Sales Order Page URL
		 */
		$this->addHook('Page(pw_template=vxm)::vxm_vendorURL', function($event) {
			$vendorID = $event->arguments(0);
			$event->return = $this->get_vxm_vendorURL($vendorID);
		});

		/**
		 * Returns Sales Order Page URL
		 */
		$this->addHook('Pages::vxm_vendors_itemURL', function($event) {
			$vendorID = $event->arguments(0);
			$itemID = $event->arguments(1); // VENDOR ITEM ID
			$event->return = $this->get_vxm_vendors_itemURL($vendorID, $itemID);
		});

		/**
		 * Returns Sales Order Page URL
		 */
		$this->addHook('Page(pw_template=vxm)::vxm_vendors_itemURL', function($event) {
			$vendorID = $event->arguments(0);
			$itemID = $event->arguments(1); // VENDOR ITEM ID
			$event->return = $this->get_vxm_vendors_itemURL($vendorID, $itemID);
		});

		/**
		 * Returns Sales Order Page URL
		 */
		$this->addHook('Pages::vxm_itemURL', function($event) {
			$itemID = $event->arguments(0);
			$event->return = $this->get_vxm_itemURL($itemID);
		});

		/**
		 * Returns Sales Order Page URL
		 */
		$this->addHook('Page(pw_template=vxm)::vxm_itemURL', function($event) {
			$itemID = $event->arguments(0);
			$event->return = $this->get_vxm_itemURL($itemID);
		});

		/**
		 * Returns Sales Order Page URL
		 */
		$this->addHook('Page(pw_template=vxm)::get_itemURL', function($event) {
			$itemID = $event->arguments(0);
			$event->return = $this->get_vxm_itemURL($itemID);
		});


		$this->addHookProperty('Page(pw_template=vxm)::vendorID', function($event) {
			$p = $event->object;
			$event->return = $p->fullURL->query->get('vendorID');
		});

		$this->addHookProperty('Page(pw_template=vxm)::vendoritemID', function($event) {
			$p = $event->object;
			$event->return = $p->fullURL->query->get('vendoritemID');
		});

		$this->addHookProperty('Page(pw_template=vxm)::itemID', function($event) {
			$p = $event->object;
			$event->return = $p->fullURL->query->get('itemID');
		});

		// Code Tables
		$this->addHook('Page(pw_template=ap-code-table-menu|ap-code-table)::get_codetable_viewURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_viewURL($table, $code);
		});


		$this->addHook('Page(pw_template=ap-code-table)::get_codetable_code_deleteURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_code_deleteURL($table, $code);
		});

		$this->addHook('Page(pw_template=ap-code-table)::get_codetable_code_editURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_code_editURL($table, $code);
		});

		$this->addHook('Page(pw_template=ap-code-table)::get_codetable_listURL', function($event) {
			$table = $event->arguments(0);
			$code = $event->arguments(1);
			$event->return = $this->get_codetable_listURL($table, $code);
		});

		$this->addHookProperty('Page(pw_template=ap-code-table)::codetable', function($event) {
			$page = $event->object;
			$event->return = $page->name;
		});
	}

	public function get_vxm_vendorURL($vendorID) {
		$url = new Url($this->wire('pages')->get('pw_template=vxm')->url);
		$url->query->set('vendorID', $vendorID);
		return $url->getUrl();
	}

	public function get_vxm_vendors_itemURL($vendorID, $vendoritemID) {
		$url = new Url($this->wire('pages')->get('pw_template=vxm')->url);
		$url->query->set('vendorID', $vendorID);
		$url->query->set('vendoritemID', $vendoritemID);
		return $url->getUrl();
	}

	public function get_vxm_itemURL($itemID) {
		$url = new Url($this->wire('pages')->get('pw_template=vxm')->url);
		$url->query->set('itemID', $itemID);
		return $url->getUrl();
	}

	public function get_codetable_viewURL($table, $code = false) {
		$url = new Url($this->wire('pages')->get("pw_template=ap-code-table, name=$table")->url);

		if ($table == 'aoptm') {
			$url->query->set('sysop', $code);
		} else {
			$url->query->set('code', $code);
		}
		return $url->getUrl();
	}

	public function get_codetable_listURL($table, $code = false) {
		$url = new Url($this->wire('pages')->get("pw_template=ap-code-table, name=$table")->url);
		$code = str_replace(' ', '-', $code);
		if ($table == 'aoptm') {
			$url->query->set('sysop', $code);
		} else {
			$url->query->set('focus', $code);
		}
		return $url->getUrl();
	}

	public function get_codetable_code_deleteURL($table, $code) {
		$url = new Url($this->wire('pages')->get("pw_template=ap-code-table, name=$table")->url);
		$url->query->set('action', 'remove-code');
		$url->query->set('table', $table);
		$url->query->set('code', $code);
		return $url->getUrl();
	}

	public function get_codetable_code_editURL($table, $code) {
		$url = new Url($this->wire('pages')->get("pw_template=ap-code-table, name=$table")->url);
		$url->query->set('code', $code);
		return $url->getUrl();
	}

	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus AP Pages Modules',
			'version' => 101,
			'summary' => 'Installs and creates AP Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
			'installs' => array(),
		);
	}
}
