<?php namespace ProcessWire;

use Purl\Url;

/**
 * class DpagesMpo
 *
 * Installs fields, templates, pages, hooks necessary for Mpo Pages
 * Adds Hooks for getting URLs to Mpo pages
 */
class DpagesMpo extends Dpages implements Module {
	const FIELDS = array();

	const TEMPLATES = array(
		'purchase-orders' => array(
			'name'   => 'purchase-orders',
			'fields' => array(),
			'paginated' => true
		),
		'purchase-order-view' => array(
			'name'   => 'purchase-order-view',
			'fields' => array(),
			'paginated' => true
		),
	);

	const PAGES = array(
		'po-menu' => array(
			'template'       => 'dplus-menu',
			'name'           => 'mpo',
			'title'          => 'Purchase Orders',
			'summary'        => 'Purchase Orders Menu',
			'parent'         => '/',
			'dplus_function' => 'mpo'
		),
		'poadmn' => array(
			'template'       => 'poadmn',
			'name'           => 'poadmn',
			'title'          => 'Administration',
			'summary'        => 'Purchase Order Administration',
			'parent'         => '/mpo/',
			'dplus_function' => 'poadmn'
		),
		'po-list' => array(
			'template'         => 'dplus-function',
			'name'             => 'purchase-orders',
			'title'            => 'Purchase Orders',
			'summary'          => 'View Purchase Order List',
			'parent'           => '/mpo/',
			'dplus_function'   => '',
			'dplus_permission' => 'mpo',
			'pw_template'      => 'purchase-orders'
		),
		'po-view' => array(
			'template'         => 'dplus-function',
			'name'             => 'purchase-order',
			'title'            => 'Purchase Order',
			'summary'          => 'View a Purchase Order',
			'parent'           => '/mpo/',
			'dplus_function'   => '',
			'dplus_permission' => 'mpo',
			'pw_template'      => 'purchase-order-view'
		),
		'po-epo' => array(
			'template'         => 'dplus-function-link',
			'name'             => 'epo',
			'title'            => 'Purchase Order Entry',
			'summary'          => 'Edit / Create Purchase Order',
			'parent'           => '/mpo/',
			'dplus_function'   => 'epo',
			'dplus_permission' => 'epo',
			'pw_template'      => '',
			'function_url'     => '/mpo/purchase-orders/epo/'
		)
	);

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Online Purchase Order Pages',
			'version' => 101,
			'summary' => 'Installs and creates Dplus Online Purchase Order Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
		);
	}

	public function init() {

		$this->addHook('User::permitted_edit_po', function($event) {
			$user = $event->object;
			$event->return = $this->wire('modules')->get('PurchaseOrderEdit')->user_has_permission($user);
		});

		$this->addHook('User::can_edit_po', function($event) {
			$user  = $event->object;
			$ponbr = $event->arguments(0);
			$event->return = $this->wire('modules')->get('PurchaseOrderEdit')->is_po_editable($ponbr);
		});
	}
}
