<?php namespace ProcessWire;
use Purl\Url;

/**
 * class DpagesMii
 *
 * Installs fields, templates, pages, hooks necessary for Mii Pages
 * Adds Hooks for getting URLs to Mii pages
 */
class DpagesMii extends Dpages implements Module {
	const REQUIREMENTS_OPTIONS = array(
		"REQ" => "requirements",
		"AVL" => 'available'
	);

	const FIELDS = array(
		'jsoncode' => array(
			'name'  => 'jsoncode',
			'type'  => 'text',
			'label' => 'JSON Datafile Code'
		),
		'is_formattable' => array(
			'name'        => 'is_formattable',
			'type'        => 'checkbox',  // TRUE OR FALSE
			'label'       => 'Is screen formattable?',
			'description' => 'Allow Screen Formatter to be used',
			'notes'       => ""
		),
	);

	const TEMPLATES = array(
		'ii-function' => array(
			'name'   => 'dplus-menu',
			'fields' => array('title', 'dplus_function', 'pw_template', 'jsoncode', 'is_formattable', 'summary'),
			'paginated' => true
		),
		'ii-item' => array(
			'name'   => 'ii-item',
			'fields' => array(),
		),
		'ii-sales-orders' => array(
			'name'   => 'ii-sales-orders',
			'fields' => array(),
		),
		'ii-sales-history' => array(
			'name'   => 'ii-sales-history',
			'fields' => array(),
		),
		'ii-quotes' => array(
			'name'   => 'ii-quotes',
			'fields' => array(),
		),
		'ii-purchase-orders' => array(
			'name'   => 'ii-purchase-orders',
			'fields' => array(),
		),
		'ii-purchase-history' => array(
			'name'   => 'ii-purchase-history',
			'fields' => array(),
		),
		'ii-item-lookup' => array(
			'name'   => 'ii-item-lookup',
			'fields' => array(),
		),
		'iio' => array(
			'name'   => 'iio',
			'fields' => array(),
		)
	);

	const PAGES = array(
		'ii-menu' => array(
			'template'       => 'dplus-menu',
			'name'           => 'mii',
			'title'          => 'Item Information',
			'summary'        => 'Item Information Menu',
			'parent'         => '/',
			'dplus_function' => 'mii'
		),
		'ii-admin' => array(
			'template'       => 'dplus-menu',
			'name'           => 'admin',
			'title'          => 'II Administration',
			'summary'        => 'Item Information Administration',
			'parent'         => '/mii/',
			'dplus_function' => 'iiadmn'
		),
		'iio' => array(
			'template'       => 'dplus-function',
			'name'           => 'iio',
			'title'          => 'II Options',
			'summary'        => 'Item Information Options',
			'parent'         => '/mii/admin/',
			'dplus_function' => 'iio',
			'pw_template'    => 'iio'
		),
		'ii' => array(
			'template'       => 'dplus-function',
			'name'           => 'ii',
			'title'          => 'Item Information',
			'summary'        => 'View Item Information',
			'parent'         => '/mii/',
			'dplus_function' => 'ii',
			'pw_template'    => 'ii-item'
		),
		'ii-sales-orders' => array(
			'template'       => 'ii-function',
			'name'           => 'sales-orders',
			'title'          => 'Sales Orders',
			'summary'        => 'View Item Sales Orders',
			'parent'         => '/mii/ii/',
			'dplus_function' => 'ii-sor',
			'pw_template'    => 'ii-sales-orders',
			'jsoncode'       => 'ii-sales-orders'
		),
		'ii-sales-history' => array(
			'template'       => 'ii-function',
			'name'           => 'sales-history',
			'title'          => 'Sales History',
			'summary'        => 'View Item Sales History',
			'parent'         => '/mii/ii/',
			'dplus_function' => 'ii-sht',
			'pw_template'    => 'ii-sales-history',
			'jsoncode'       => 'ii-sales-history'
		),
		'ii-quotes' => array(
			'template'       => 'ii-function',
			'name'           => 'quotes',
			'title'          => 'Quotes',
			'summary'        => 'View Item Quotes',
			'parent'         => '/mii/ii/',
			'dplus_function' => 'ii-qte',
			'pw_template'    => 'ii-quotes',
			'jsoncode'       => 'ii-quotes'
		),
		'ii-purchase-orders' => array(
			'template'       => 'ii-function',
			'name'           => 'purchase-orders',
			'title'          => 'Purchase Orders',
			'summary'        => 'View Item Purchase Orders',
			'parent'         => '/mii/ii/',
			'dplus_function' => 'ii-pur',
			'pw_template'    => 'ii-purchase-orders',
			'jsoncode'       => 'ii-purchase-orders'
		),
		'ii-purchase-history' => array(
			'template'       => 'ii-function',
			'name'           => 'purchase-history',
			'title'          => 'Purchase History',
			'summary'        => 'View Item Purchase History',
			'parent'         => '/mii/ii/',
			'dplus_function' => 'ii-pht',
			'pw_template'    => 'ii-purchase-history',
			'jsoncode'       => 'ii-purchase-history'
		),
		'ii-item-lookup'     => array(
			'template'       => 'dplus-json',
			'name'           => 'Item Lookup',
			'title'          => 'Item Lookup',
			'summary'        => 'Look up Items',
			'parent'         => '/mii/',
			'dplus_function' => '',
			'pw_template'    => 'ii-item-lookup',
		)
	);

	public function init_iipage() {
		$this->addHook('Page(pw_template=ii-item)::children_user_allowed', function($event) {
			$user = $this->wire('user');
			$event->return = $this->get_ii_user_allowed_functions($user);
		});

		$this->addHook('Page::url_itemID', function($event) {
			$p = $event->object;
			$itemID   = $event->arguments(0);
			$url = new Url($p->url);
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_redirURL', function($event) {
			$p = $event->object;
			$event->return = $p->parent('template=dplus-menu')->child('template=redir')->url;
		});

		$this->addHook('Page::get_itempageURL', function($event) {
			$itemID = $event->arguments(0);
			$event->return = $this->get_ii_itemURL($itemID);
		});

		$this->addHook('Page::get_itemURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemstockURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->path->add('stock');
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemrequirementsURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->path->add('requirements');
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itempricingURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$custID = $event->arguments(1);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->path->add('requirements');
			$url->query->set('itemID', $itemID);
			if ($custID) {
				$url->query->set('custID', $custID);
			}
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemcostingURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->path->add('costing');
			$url->query->set('itemID', $itemID);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemusageURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->path->add('usage');
			$url->query->set('itemID', $itemID);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemactivityURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->path->add('activity');
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemkitURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->path->add('kit');
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itembomURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->path->add('bom');
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemwhereusedURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->path->add('where-used');
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemlotserialURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->path->add('lotserial');
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemgeneralURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->path->add('general');
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemsubstitutesURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->path->add('substitutes');
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemdocumentsURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->path->add('documents');
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemsalesordersURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
			$url->query->set('action','ii-sales-orders');
			$url->query->set('itemID', $itemID);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemsaleshistoryURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$date = $event->arguments(1);
			$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
			$url->query->set('action','ii-sales-history');
			$url->query->set('itemID', $itemID);
			$url->query->set('date', $date);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itemquotesURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$date = $event->arguments(1);
			$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
			$url->query->set('action','ii-quotes');
			$url->query->set('itemID', $itemID);
			$url->query->set('date', $date);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itempurchaseordersURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$date = $event->arguments(1);
			$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
			$url->query->set('action','ii-purchase-orders');
			$url->query->set('itemID', $itemID);
			$url->query->set('date', $date);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_itempurchasehistoryURL', function($event) {
			$p = $event->object;
			$itemID = $event->arguments(0);
			$date = $event->arguments(1);
			$url = new Url($p->parent('template=dplus-menu')->child('template=redir')->url);
			$url->query->set('action','ii-purchase-history');
			$url->query->set('itemID', $itemID);
			$url->query->set('date', $date);
			$url->query->set('page', $p->fullURL->getUrl());
			$event->return = $url->getUrl();
		});

		$this->addHook('Page::get_backURL', function($event) {
			$p = $event->object;
			$itemID = $p->fullURL->query->get('itemID');
			$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
			$url->query->set('itemID', $itemID);
			$event->return = $url->getUrl();
		});
	}

/* =============================================================
	Supplemental Functions
============================================================= */
	/**
	 * Return II Subfunction pages that user has permissions to
	 * @param  User   $user User
	 * @return Pages
	 */
	public function get_ii_user_allowed_functions(User $user) {
		$p = $this->wire('pages')->get('pw_template=ii-item');
		$dplus_functions = array_unique($p->children()->explode('dplus_function'));
		$filtered_functions = $user->filter_functions($dplus_functions);
		return $p->children('dplus_function='.implode('|', $filtered_functions));
	}

	public function get_requirementsoptions() {
		return self::REQUIREMENTS_OPTIONS;
	}

/* =============================================================
	URL Functions
============================================================= */
	/**
	 * Returns URL to II item page
	 * @param  string $itemID Item ID
	 * @return string
	 */
	public function get_ii_itemURL($itemID) {
		$url = new Url($this->wire('pages')->get('pw_template=ii-item')->url);
		$url->query->set('itemID', $itemID);
		return $url->getUrl();
	}

	/**
	 * Returns URL to II item page
	 * @param  string $itemID Item ID
	 * @return string
	 */
	public function get_ii_loaditemURL($itemID) {
		$url = new Url($this->wire('pages')->get('template=redir, redir_file=ii')->url);
		$url->query->set('action','ii-item');
		$url->query->set('itemID', $itemID);
		return $url->getUrl();
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus Online Item Information Pages',
			'version' => 101,
			'summary' => 'Installs and creates Dplus Online Item Information  Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
		);
	}
}
