<?php namespace ProcessWire;

use Purl\Url as Purl;

/**
 * class DpagesMsa
 *
 * Installs fields, templates, pages, hooks necessary for the MAP pages
 * NOTE: Also installs the basic fields, templates, to build the rest of the Application
 */
class DpagesMsa extends Dpages implements Module {
	const FIELDS = array();

	const TEMPLATES = array(
		'msa-sysop' => array(
			'name'   => 'msa-sysop',
			'fields' => array(),
			'paginated' => true
		),
		'msa-lgrp' => array(
			'name'   => 'msa-lgrp',
			'fields' => array(),
			'paginated' => true
		),
		'msa-noce' => array(
			'name'   => 'msa-noce',
			'fields' => array(),
			'paginated' => true
		),
		'msa-noce-ajax' => array(
			'name'   => 'msa-noce-ajax',
			'fields' => array(),
			'paginated' => true
		),
	);

	const PAGES = array(
		'msa' => array(
			'template'       => 'dplus-menu',
			'name'           => 'msa',
			'title'          => 'System Administration',
			'summary'        => 'System Administration Menu',
			'parent'         => '/',
			'dplus_function' => 'msa'
		),
		'msa-sysop' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'msa-sysop',
			'name'           => 'sysop',
			'title'          => 'System Optional Codes',
			'summary'        => 'View / Edit System Optional Codes',
			'parent'         => '/msa/',
			'dplus_function' => 'sysop'
		),
		'msa-lgrp' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'msa-lgrp',
			'name'           => 'lgrp',
			'title'          => 'Login Group Entry',
			'summary'        => 'View / Edit Login Group Entry',
			'parent'         => '/msa/',
			'dplus_function' => 'lgrp'
		),
		'msa-noce' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'msa-noce',
			'name'           => 'noce',
			'title'          => 'Pre-Defined Notes Entry',
			'summary'        => 'View / Edit Pre-Defined Notes',
			'parent'         => '/msa/',
			'dplus_function' => 'noce'
		),
		'msa-noce-ajax' => array(
			'template'       => 'dplus-function',
			'pw_template'    => 'msa-noce-ajax',
			'name'           => 'ajax',
			'title'          => 'Pre-Defined Notes AJAX',
			'summary'        => 'View / Edit Pre-Defined Notes through AJAX',
			'parent'         => '/msa/noce/',
			'dplus_function' => ''
		),
	);

/* =============================================================
	URL Module Functions
============================================================= */
	public function getNoceAjaxUrl() {
		$url = new Purl($this->wire('pages')->get('pw_template=msa')->httpUrl);
		$url->path->add('noce');
		$url->path->add('ajax');
		return $url->getUrl();
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public function init() {
		$this->addHook('Page::search_noceURL', function($event) {
			$p = $event->object;

			$event->return = $this->getNoceAjaxUrl();
		});
	}

	public static function getModuleInfo() {
		return array(
			'title' => 'Dplus MSA Pages Modules',
			'version' => 101,
			'summary' => 'Installs and creates MSA Pages',
			'singular' => true,
			'autoload' => true,
			'requires' => array('DplusPwPages', 'Dpages'),
			'installs' => array(),
		);
	}
}
