<?php namespace ProcessWire;

use Purl\Url;

use DocumentFoldersQuery, DocumentFolders;
use DocumentsQuery, Documents;
use PurchaseOrderQuery, PurchaseOrder;
use ApInvoiceQuery, ApInvoice;

/**
 * Document Management PO
 *
 * Handles Purchase Order Document Retrieval for Dplus
 */
class DocumentManagementPo extends DocumentManagement implements Module {
	/**
	 * Return Documents
	 * filtered by the tag1, reference1 fields for a Purchase Order Number
	 * @param  string $ponbr                 Purchase Order Number
	 * @return Documents[]|ObjectCollection
	 */
	public function get_documents_po($ponbr) {
		$ponbr = PurchaseOrder::get_paddedponumber($ponbr);
		$docs_query = DocumentsQuery::create();
		$docs_query->filterByTag(self::TAG_VENDORPO);
		$docs_query->filterByReference1($ponbr);
		return $docs_query->find();
	}

	/**
	 * Return the number of Documents
	 * filtered by the tag1, reference1 fields for a Purchase Order
	 * @param  string $ponbr Purchase Order Number
	 * @return int           Number of Purchase Order Documents found
	 */
	public function count_documents_po($ponbr) {
		$ponbr = PurchaseOrder::get_paddedponumber($ponbr);
		$docs_query = DocumentsQuery::create();
		$docs_query->filterByTag(self::TAG_VENDORPO);
		$docs_query->filterByReference1($ponbr);
		return $docs_query->count();
	}

	/**
	 * Return Documents
	 * filtered by the tag1, reference1 fields for an AP Invoice #
	 * @param  string $invnbr Purchase Order Number
	 * @return Documents[]|Object Collection
	 */
	public function get_documents_invoice($invnbr) {
		$docs_query = DocumentsQuery::create();
		$this->filter_invoice($docs_query, $invnbr);
		return $docs_query->find();
	}

	/**
	 * Return the number of Documents
	 * filtered by the tag1, reference1 fields for a AP Invoice Number
	 * @uses self::filter_invoice()
	 *
	 * @param  string $invnbr AP Invoice Number
	 * @return int            Number of Documents found associated with AP Invoice Number
	 */
	public function count_documents_invoice($invnbr) {
		$docs_query = DocumentsQuery::create();
		$this->filter_invoice($docs_query, $invnbr);
		return $docs_query->count();
	}

	/**
	 * Adds Filter Conditions to the Documents Query
	 * to find Documents associated with an AP Invoice Number
	 *
	 * @param  DocumentsQuery $docs_query  Query to add filters to
	 * @param  string         $invnbr            AP Invoice Number
	 * @return void
	 */
	protected function filter_invoice(DocumentsQuery $docs_query, $invnbr) {
		$invnbr = PurchaseOrder::get_paddedponumber($invnbr);
		$validate_inv = $this->wire('modules')->get('ValidatePurchaseOrderNbr');

		$this->columns = new WireData();
		$this->columns->reference1 = Documents::get_aliasproperty('reference1');
		$this->columns->reference2 = Documents::get_aliasproperty('reference2');

		$conditions = array();

		/**
		 * Check if it's an Invoice #
		 */
		if ($validate_inv->validate_invoice($invnbr)) {
			$this->columns->tag = Documents::get_aliasproperty('tag');

			$conditions[] = filter_condition_invoice_reference1($docs_query, $invnbr);
			$conditions[] = filter_condition_invoice_reference2($docs_query, $invnbr);
			$conditions[] = filter_condition_invoice_po($docs_query, $invnbr);
			$docs_query->where($conditions, 'or');
		} else {
			$docs_query->filterByTag(self::TAG_VENDORPO);

			// Create Vendor PO OR Filter
			$docs_query->condition('reference1_invoices', "Documents.{$this->columns->reference1} = ?", $invnbr);
			$docs_query->condition('reference2_invoices', "Documents.{$this->columns->reference2} = ?", $invnbr);
			$docs_query->combine(array('reference1_invoices', 'reference2_invoices'), 'or', 'cond_invoices');
			$docs_query->where(array('cond_invoices'));
		}
	}

	/**
	 * Add AP Invoice Condition to Documents Query
	 * @param  DocumentsQuery $docs_query Documents Query
	 * @param  string         $invnbr     AP Invoice Number
	 * @return string
	 */
	protected function filter_condition_invoice_reference1(DocumentsQuery $docs_query, $invnbr) {
		$name = 'cond_invoices';
		$docs_query->condition('tag_invoices', "Documents.{$this->columns->tag} = ?", self::TAG_APINVOICE);
		$docs_query->condition('reference1_invoices', "Documents.{$this->columns->reference1} = ?", $invnbr);
		$docs_query->combine(array('tag_invoices', 'reference1_invoices'), 'and', $name);
		return $name;
	}

	/**
	 * Add AP Invoice Condition to Documents Query
	 * @param  DocumentsQuery $docs_query Documents Query
	 * @param  string         $invnbr     AP Invoice Number
	 * @return string
	 */
	protected function filter_condition_invoice_reference2(DocumentsQuery $docs_query, $invnbr) {
		$name = 'cond_invoices2';
		$docs_query->condition('tag_invoices', "Documents.{$this->columns->tag} = ?", self::TAG_APINVOICE);
		$docs_query->condition('reference2_invoices', "Documents.{$this->columns->reference2} = ?", $invnbr);
		$docs_query->combine(array('tag_invoices', 'reference2_invoices'), 'and', $name);
		return $name;
	}

	/**
	 * Add Vendor PO Condition to Documents Query
	 * @param  DocumentsQuery $docs_query Documents Query
	 * @param  string         $invnbr     AP Invoice Number
	 * @return string
	 */
	protected function filter_condition_invoice_po(DocumentsQuery $docs_query, $invnbr) {
		$apinvoice = $this->get_invoice($invnbr);
		$ponbr = $apinvoice->ponbr;
		$name = 'cond_vendorpo';
		$docs_query->condition('tag_vendorpo', "Documents.{$this->columns->tag} = ?", self::TAG_VENDORPO);
		$docs_query->condition('reference1_vendorpo', "Documents.{$this->columns->reference1} = ?", $ponbr);
		$docs_query->combine(array('tag_vendorpo', 'reference1_vendorpo'), 'and', $name);
		return $name;
	}

/* =============================================================
	Supplemental Functions
============================================================= */
	/**
	 * Return AP Invoice
	 * @param  string $invnbr AP Invoice Number
	 * @return ApInvoice
	 */
	public function get_invoice($invnbr) {
		$q = ApInvoiceQuery::create();
		return $q->findOneByInvoicenumber($invnbr);
	}

/* =============================================================
	URL Functions
============================================================= */
	/**
	 * Return URL to Purchase Order Documents Page
	 * @param  string $ponbr    Purchase Order Number
	 * @param  string $folder   Folder Tag to Look for Document (default: PO)
	 * @param  string $document Document Name
	 * @return string
	 */
	public function get_purchaseorder_docsURL($ponbr, $folder, $document) {
		$url = new Url($this->wire('pages')->get('pw_template=purchase-order-documents')->url);
		$url->query->set('ponbr', $ponbr);
		$url->query->set('folder', $folder ? $folder : self::TAG_VENDORPO);
		$url->query->set('document', $document);
		return $url->getUrl();
	}

	/**
	 * Return URL to AP Invoice Documents Page
	 * @param  string $invnbr    AP Invoice Number
	 * @param  string $folder    Folder Tag to Look for Document (default: self::TAG_APINVOICE)
	 * @param  string $document  Document Name
	 * @return string
	 */
	public function get_apinvoice_docsURL($invnbr, $folder, $document) {
		$url = new Url($this->wire('pages')->get('pw_template=purchase-order-documents')->url);
		$url->query->set('invnbr', $invnbr);
		$url->query->set('folder', $folder ? $folder : self::TAG_APINVOICE);
		$url->query->set('document', $document);
		return $url->getUrl();
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Document Management Purchase Order',
			'version' => 101,
			'summary' => 'Module for getting Purchase Order Documents / Document Info out of Dplus',
			'singular' => true,
			'autoload' => true,
			'requires' => 'DocumentManagement'
		);
	}

	public function init() {
		$this->addHook('Page(pw_template=purchase-order-view)::documentload', function($event) {
			$page = $event->object;
			$folder   = $event->arguments(0);
			$document = $event->arguments(1);
			$ponbr    = $event->arguments(2);

			if (PurchaseOrderQuery::create()->filterByPonbr($ponbr)->count()) {
				$event->return = $this->get_purchaseorder_docsURL($ponbr, $folder, $document);
			} elseif (ApInvoiceQuery::create()->filterByInvoicenumber($ponbr)->count()) {
				$event->return = $this->get_apinvoice_docsURL($ponbr, $folder, $document);
			}
		});

		$this->addHook('Page(pw_template=purchase-order-documents)::documentload', function($event) {
			$page = $event->object;
			$folder   = $event->arguments(0);
			$document = $event->arguments(1);
			$ponbr    = $event->arguments(2);

			if (PurchaseOrderQuery::create()->filterByPonbr($ponbr)->count()) {
				$event->return = $this->get_purchaseorder_docsURL($ponbr, $folder, $document);
			} elseif (ApInvoiceQuery::create()->filterByInvoicenumber($ponbr)->count()) {
				$event->return = $this->get_apinvoice_docsURL($ponbr, $folder, $document);
			}
		});
	}
}
