<?php namespace ProcessWire;

use Purl\Url;

use Dplus\CodeValidators\Mpo as MpoValidator;

use DocumentFolderQuery, DocumentFolder;
use DocumentQuery, Document;
use PurchaseOrderQuery, PurchaseOrder;
use ApInvoiceQuery, ApInvoice;

/**
 * Document Management PO
 *
 * Handles Purchase Order Document Retrieval for Dplus
 */
class DocumentManagementPo extends DocumentManagement implements Module {
	/**
	 * Return Documents
	 * filtered by the tag1, reference1 fields for a Purchase Order Number
	 * @param  string $ponbr                 Purchase Order Number
	 * @return Documents[]|ObjectCollection
	 */
	public function get_documents_po($ponbr) {
		$ponbr = PurchaseOrder::get_paddedponumber($ponbr);
		$docs_query = DocumentQuery::create();
		$docs_query->filterByTag(self::TAG_VENDORPO);
		$docs_query->filterByReference1($ponbr);
		return $docs_query->find();
	}

	/**
	 * Return the number of Documents
	 * filtered by the tag1, reference1 fields for a Purchase Order
	 * @param  string $ponbr Purchase Order Number
	 * @return int           Number of Purchase Order Documents found
	 */
	public function count_documents_po($ponbr) {
		$ponbr = PurchaseOrder::get_paddedponumber($ponbr);
		$docs_query = DocumentQuery::create();
		$docs_query->filterByTag(self::TAG_VENDORPO);
		$docs_query->filterByReference1($ponbr);
		return $docs_query->count();
	}

	/**
	 * Return Documents
	 * filtered by the tag1, reference1 fields for an AP Invoice #
	 * @param  string $invnbr Purchase Order Number
	 * @return Documents[]|Object Collection
	 */
	public function get_documents_invoice($invnbr) {
		$docs_query = DocumentQuery::create();
		$this->filter_invoice($docs_query, $invnbr);
		return $docs_query->find();
	}

	/**
	 * Return the number of Documents
	 * filtered by the tag1, reference1 fields for a AP Invoice Number
	 * @uses self::filter_invoice()
	 *
	 * @param  string $invnbr AP Invoice Number
	 * @return int            Number of Documents found associated with AP Invoice Number
	 */
	public function count_documents_invoice($invnbr) {
		$docs_query = DocumentQuery::create();
		$this->filter_invoice($docs_query, $invnbr);
		return $docs_query->count();
	}

	/**
	 * Adds Filter Conditions to the Documents Query
	 * to find Documents associated with an AP Invoice Number
	 *
	 * @param  DocumentQuery $docs_query  Query to add filters to
	 * @param  string         $invnbr            AP Invoice Number
	 * @return void
	 */
	protected function filter_invoice(DocumentQuery $docs_query, $invnbr) {
		$invnbr = PurchaseOrder::get_paddedponumber($invnbr);
		$validate_inv = new MpoValidator();

		$this->columns = new WireData();
		$this->columns->reference1 = Document::get_aliasproperty('reference1');
		$this->columns->reference2 = Document::get_aliasproperty('reference2');

		$conditions = array();

		/**
		 * Check if it's an Invoice #
		 */
		if ($validate_inv->invoice($invnbr)) {
			$this->columns->tag = Document::get_aliasproperty('tag');

			$conditions[] = filter_condition_invoice_reference1($docs_query, $invnbr);
			$conditions[] = filter_condition_invoice_reference2($docs_query, $invnbr);
			$conditions[] = filter_condition_invoice_po($docs_query, $invnbr);
			$docs_query->where($conditions, 'or');
		} else {
			$docs_query->filterByTag(self::TAG_VENDORPO);

			// Create Vendor PO OR Filter
			$docs_query->condition('reference1_invoices', "Document.{$this->columns->reference1} = ?", $invnbr);
			$docs_query->condition('reference2_invoices', "Document.{$this->columns->reference2} = ?", $invnbr);
			$docs_query->combine(array('reference1_invoices', 'reference2_invoices'), 'or', 'cond_invoices');
			$docs_query->where(array('cond_invoices'));
		}
	}

	/**
	 * Add AP Invoice Condition to Documents Query
	 * @param  DocumentQuery $docs_query Documents Query
	 * @param  string         $invnbr     AP Invoice Number
	 * @return string
	 */
	protected function filter_condition_invoice_reference1(DocumentQuery $docs_query, $invnbr) {
		$name = 'cond_invoices';
		$docs_query->condition('tag_invoices', "Document.{$this->columns->tag} = ?", self::TAG_APINVOICE);
		$docs_query->condition('reference1_invoices', "Document.{$this->columns->reference1} = ?", $invnbr);
		$docs_query->combine(array('tag_invoices', 'reference1_invoices'), 'and', $name);
		return $name;
	}

	/**
	 * Add AP Invoice Condition to Documents Query
	 * @param  DocumentQuery $docs_query Documents Query
	 * @param  string         $invnbr     AP Invoice Number
	 * @return string
	 */
	protected function filter_condition_invoice_reference2(DocumentQuery $docs_query, $invnbr) {
		$name = 'cond_invoices2';
		$docs_query->condition('tag_invoices', "Document.{$this->columns->tag} = ?", self::TAG_APINVOICE);
		$docs_query->condition('reference2_invoices', "Document.{$this->columns->reference2} = ?", $invnbr);
		$docs_query->combine(array('tag_invoices', 'reference2_invoices'), 'and', $name);
		return $name;
	}

	/**
	 * Add Vendor PO Condition to Documents Query
	 * @param  DocumentQuery $docs_query Documents Query
	 * @param  string         $invnbr     AP Invoice Number
	 * @return string
	 */
	protected function filter_condition_invoice_po(DocumentQuery $docs_query, $invnbr) {
		$apinvoice = $this->get_invoice($invnbr);
		$ponbr = $apinvoice->ponbr;
		$name = 'cond_vendorpo';
		$docs_query->condition('tag_vendorpo', "Document.{$this->columns->tag} = ?", self::TAG_VENDORPO);
		$docs_query->condition('reference1_vendorpo', "Document.{$this->columns->reference1} = ?", $ponbr);
		$docs_query->combine(array('tag_vendorpo', 'reference1_vendorpo'), 'and', $name);
		return $name;
	}

/* =============================================================
	Supplemental Functions
============================================================= */
	/**
	 * Return AP Invoice
	 * @param  string $invnbr AP Invoice Number
	 * @return ApInvoice
	 */
	public function get_invoice($invnbr) {
		$q = ApInvoiceQuery::create();
		return $q->findOneByInvoicenumber($invnbr);
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Document Management Purchase Order',
			'version' => 101,
			'summary' => 'Module for getting Purchase Order Documents / Document Info out of Dplus',
			'singular' => true,
			'autoload' => true,
			'requires' => 'DocumentManagement'
		);
	}
}
