<?php namespace ProcessWire;

use Purl\Url;
use DocumentFolderQuery, DocumentFolder;
use DocumentQuery, Document;

/**
 * Document Management Quotes
 *
 * Handles Quote Documents Retrieval for Dplus
 */
class DocumentManagementQt extends DocumentManagement implements Module {
	/**
	 * Return Documents
	 * filtered by the tag1, reference1 fields for a Quote
	 * @param  string $qnbr                  Quote Number
	 * @return Documents[]|ObjectCollection
	 */
	public function get_documents($qnbr) {
		$docs_query = DocumentQuery::create();
		$docs_query->filterByTag(self::TAG_QUOTE);
		$docs_query->filterByReference1($this->qnbr($qnbr));
		return $docs_query->find();
	}

	/**
	 * Return the number of Documents
	 * filtered by the tag1, reference1 fields for a Quote
	 * @param  string $qnbr Quote Number
	 * @return int          Number of Sales Order Documents found
	 */
	public function count_documents($qnbr) {
		$docs_query = DocumentQuery::create();
		$docs_query->filterByTag(self::TAG_QUOTE);
		$docs_query->filterByReference1($this->qnbr($qnbr));
		return $docs_query->count();
	}

	public function qnbr($qnbr) {
		return substr($qnbr, -4);
	}

/* =============================================================
	URL Functions
============================================================= */
	/**
	 * Return URL to the Quote Documents Page
	 * @param  string $qnbr     Quote Number
	 * @param  string $folder   Folder Tag
	 * @param  string $document File Name
	 * @return string
	 */
	public function get_docsURL($qnbr, $folder, $document) {
		$url = new Url($this->wire('pages')->get('pw_template=quote-documents')->url);
		$url->query->set('qnbr', $qnbr);
		$url->query->set('folder', $folder);
		$url->query->set('document', $document);
		return $url->getUrl();
	}
/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Document Management Quotes',
			'version' => 101,
			'summary' => 'Module for getting Quote Documents / Document Info out of Dplus',
			'singular' => true,
			'autoload' => true,
			'requires' => 'DocumentManagement'
		);
	}

	public function init() {
		$this->addHook('Page(pw_template=quote-view)::documentload', function($event) {
			$page = $event->object;
			$folder   = $event->arguments(0);
			$document = $event->arguments(1);
			$qnbr     = $event->arguments(2);
			$event->return = $this->get_docsURL($qnbr, $folder, $document);
		});

		$this->addHook('Page(pw_template=quote-documents)::documentload', function($event) {
			$page = $event->object;
			$folder   = $event->arguments(0);
			$document = $event->arguments(1);
			$qnbr     = $event->arguments(2);
			$event->return = $this->get_docsURL($qnbr, $folder, $document);
		});
	}
}
