<?php namespace ProcessWire;

use TariffCodeQuery, TariffCode;

use Propel\Runtime\ActiveQuery\Criteria;

class FilterInvTariffCodes extends WireData implements Module {
	/**
	 * Returns Query
	 * @return TariffCodeQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * NOTE: Filters by Sales Rep if provided user is a Sales rep
	 *
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return void
	 */
	public function init_query(User $user) {
		$this->query = TariffCodeQuery::create();
	}

	/**
	 * Searches the Tariff Code Table to find vendors that match the query provided
	 * @param  string $q Search Query
	 * @return void
	 */
	public function filter_search($q) {
		$columns = array(
			TariffCode::get_aliasproperty('id'),
			TariffCode::get_aliasproperty('number'),
			TariffCode::get_aliasproperty('description'),
			TariffCode::get_aliasproperty('duty_rate'),
		);
		$this->query->search_filter($columns, strtoupper($q));
	}

	/**
	 * Adds the Sort By to the query
	 * @param  Page   $page
	 * @return void
	 */
	public function apply_sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;

			$tablecolumn = TariffCode::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		}
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso Filter Tariff Codes Module',
			'version' => 101,
			'summary' => 'Handles Tariff Codes Filtering',
			'singular' => true,
			'autoload' => true,
		);
	}
}
