<?php namespace ProcessWire;

	class CiSalesHistory extends ScreenFormatter implements Module {

	protected $code = 'ci-sales-history';


	/**
	 * Key Value array of Sections that exist I.E. header => Header, detail => Detail
	 * @var string
	 */
	protected $datasections = array(
		"header" => "Header",
		"detail" => "Detail",
		"lotserial" => "Lot / Serial",
		"total" => "Totals",
		"shipments" => "Shipments"
	);

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
		/**
		 * ProcessWire Module Info
		 *
		 * @return void
		 */
		public static function getModuleInfo() {
			return array(
				'title' => 'Dpluso CI Sales History Formatter Module',
				'version' => 101,
				'summary' => 'Handles CI Sales History Formatter',
				'singular' => true,
				'autoload' => true,
			);
		}
	}
