<?php namespace ProcessWire;

/**
 * Class for formatting the CI Sales Orders Screen
 */
class SfCiSalesOrders extends ScreenFormatter implements Module {
	protected $code = 'ci-sales-orders';

	/**
	 * Key Value array of Sections that exist I.E. header => Header, detail => Detail
	 * @var string
	 */
	protected $datasections = array(
		"header" => "Header",
		"detail" => "Detail",
		"itemstatus" => "Item Status",
		"purchaseorder" => "Purchase Order",
		"total" => "Total",
		"shipments" => "Shipments"
	);

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso CI Sales Orders Formatter Module',
			'version' => 101,
			'summary' => 'Handles CI Sales Orders Formatter',
			'singular' => true,
			'autoload' => false,
			'requires' => 'ScreenFormatter'
		);
	}
}
