<?php namespace ProcessWire;

/**
 * Class for formatting the CI Open Invoices Screen
 */
class SfCiOpenInvoices extends ScreenFormatter implements Module {
	protected $code = 'ci-open-invoices';

	/**
	 * Key Value array of Sections that exist I.E. header => Header, detail => Detail
	 * @var string
	 */
	protected $datasections = array(
		"detail" => "Detail"
	);

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso CI Open Invoices Formatter Module',
			'version' => 101,
			'summary' => 'Handles CI Open Invoices Formatter',
			'singular' => true,
			'autoload' => false,
			'requires' => 'ScreenFormatter'
		);
	}
}
