<?php namespace ProcessWire;

class SfCiPurchaseOrders extends ScreenFormatter implements Module {

	protected $code = 'ci-customer-po';


	/**
	 * Key Value array of Sections that exist I.E. header => Header, detail => Detail
	 * @var string
	 */
	protected $datasections = array(
		'header'  => 'Header',
		"details" => "Details",
		"totals"  => "Totals"
	);

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso CI Purchase Orders Formatter Module',
			'version' => 101,
			'summary' => 'Handles CI Purchase Orders Formatter',
			'singular' => true,
			'autoload' => false,
			'requires' => 'ScreenFormatter'
		);
	}
}
