<?php namespace ProcessWire;

/**
 * Class for formatting the II Purchase Orders Screen
 */
class SfIiPurchaseOrders extends ScreenFormatter implements Module {
	protected $code = 'ii-purchase-orders';

	/**
	 * Key Value array of Sections that exist I.E. header => Header, detail => Detail
	 * @var string
	 */
	protected $datasections = array(
		"detail" => "Detail"
	);

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso II Purchase Orders Formatter Module',
			'version' => 101,
			'summary' => 'Handles II Purchase Orders Formatter',
			'singular' => true,
			'autoload' => false,
			'requires' => 'ScreenFormatter'
		);
	}
}
