<?php namespace ProcessWire;

include_once(__DIR__.'/ScreenFormatter.module');

/**
 * Class for formatting the II Quotes Screen
 */
class SfIiItem extends ScreenFormatter implements Module {
	protected $code = 'ii-item';

	/**
	 * Key Value array of Sections that exist I.E. header => Header, detail => Detail
	 * @var string
	 */
	protected $datasections = array(
		"item" => "item",
	);

	/**
	 * Return if the Column weight is formatted
	 * @return bool
	 */
	public function is_weight_formatted() {
		return $this->is_column_formatted('Weight');
	}

	/**
	 * Return if the Column is formatted
	 * @return bool
	 */
	public function is_column_formatted($col) {
		$formatter = $this->get_formatter();
		if (array_key_exists($col, $formatter['item']['columns']) == false) {
			return false;
		}
		$column = $formatter['item']['columns'][$col];
		if ($column['line'] == 0 || $column['column'] == 0) {
			return false;
		}
		return true;
	}


/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso II Item Formatter Module',
			'version' => 101,
			'summary' => 'Handles II Item Formatter',
			'singular' => true,
			'autoload' => false,
			'requires' => 'ScreenFormatter'
		);
	}
}
