<?php namespace ProcessWire;

/**
 * Class for formatting the II Purchase History Screen
 */
class SfIiPurchaseHistory extends ScreenFormatter implements Module {
	protected $code = 'ii-purchase-history';

	/**
	 * Key Value array of Sections that exist I.E. header => Header, detail => Detail
	 * @var string
	 */
	protected $datasections = array(
		"detail"    => "Detail",
		"lotserial" => "Lot / Serial"
	);

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	/**
	 * ProcessWire Module Info
	 *
	 * @return void
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso II Purchase History Formatter Module',
			'version' => 101,
			'summary' => 'Handles II Purchase History Formatter',
			'singular' => true,
			'autoload' => false,
			'requires' => 'ScreenFormatter'
		);
	}
}
