<?php namespace ProcessWire;

/**
 * Class for formatting the VI Purchase Orders Screen
 */
class SfViPurchaseOrders extends ScreenFormatter implements Module {
	protected $code = 'vi-purchase-orders';

	/**
	 * Key Value array of Sections that exist I.E. header => Header, detail => Detail
	 * @var string
	 */
	protected $datasections = array(
		"header" => "Header",
		"detail" => "Detail"
	);

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
		/**
		 * ProcessWire Module Info
		 *
		 * @return void
		 */
		public static function getModuleInfo() {
			return array(
				'title' => 'Dpluso VI Purchase Orders Formatter Module',
				'version' => 101,
				'summary' => 'Handles VI Purchase Orders Formatter',
				'singular' => true,
				'autoload' => false,
				'requires' => 'ScreenFormatter'
			);
		}
}
