<?php namespace ProcessWire;

/**
 * Class for formatting the VI Open Invoices Screen
 */
class ViOpenInvoices extends ScreenFormatter implements Module {
	protected $code = 'vi-open-invoices';

	/**
	 * Key Value array of Sections that exist I.E. header => Header, detail => Detail
	 * @var string
	 */
	protected $datasections = array(
		"detail" => "Detail"
	);

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
		/**
		 * ProcessWire Module Info
		 *
		 * @return void
		 */
		public static function getModuleInfo() {
			return array(
				'title' => 'Dpluso VI Open Invoices Formatter Module',
				'version' => 101,
				'summary' => 'Handles VI Open Invoices Formatter',
				'singular' => true,
				'autoload' => true,
			);
		}
}
