<?php namespace ProcessWire;

class ViUnreleasedPO extends ScreenFormatter implements Module {

	protected $code = 'vi-unreleased';

	/**
	 * Key Value array of Sections that exist I.E. header => Header, detail => Detail
	 * @var string
	 */
	protected $datasections = array(
		"header" => "Header",
		"detail" => "Detail"
	);

	/* =============================================================
		ProcessWire Module Functions
	============================================================= */
		/**
		 * ProcessWire Module Info
		 *
		 * @return void
		 */
		public static function getModuleInfo() {
			return array(
				'title' => 'Dpluso VI Unreleased Purchase Orders Formatter Module',
				'version' => 101,
				'summary' => 'Handles VI Unreleased Purchase Orders Formatter',
				'singular' => true,
				'autoload' => true,
			);
		}
}
